### ISSUE TITLE
[BUG] Volume Restore from S3 Minio into another cluster

### ISSUE THREAD

**Issue by j4y4r** [longhorn/longhorn#1075]
**Describe the bug**

I discoverd some issues when trying to restore a backupd volume from one cluster into another when using S3 Minio for Backup.

**To Reproduce**

##### Follwing actions were performed on cluster a:

 1. navigate to the volumes tab in the Longhorn UI.

 2. create a backup of a volume.

 3. go to backup tab, click the volume name

  - here is the first issue , when i choose get url from operations menu, i get something like s3://backupbucket@us-east-1/?backup=backup-c92394asdfs3dfg8&volume=pvc-483f49c1-123a-5532-7899-45205ud1246b.

   is it possible to display the correct url to the actual S3 Minio instance, like https://minio.example.com:9000/minio/backupbucket/backupstore/volumes/1v/90/pvc-483f49c1-123a-5532-7899-45205ud1246b ?

 4. from the opertations menu, choose restore, enter an name and click OK.

 5. the volume is in state detached and pv/pvc is not bound.

 6. from the operations menu, choose create pv/pvc , enter a namespace and click OK.

 7. the volume is in state detached, the pv/pvc is bound, it is now ready to be used by any workload.

##### Follwing actions were performed on cluster b:

 1. navigate to the volumes tab in the Longhorn UI.

 3. go to backup tab, click the volume name.

 4. from the opertations menu, choose restore, enter an name and click OK.

 5. the volume is in state faulted, and pv/pvc is not bound.

 6. from the operations menu, select salavge, choose replica/s and click ok.

 7. the volume is not in state healthy and the pv/pvc is not bound.

 8. the event log in the dashbaord states the replicas has started rebuilding and rebuiled a few seconds later, however the volume stays in state healthy, it is not possible to detach the volume.  

 9. from the operations menu, choose create pv/pvc , enter a namespace and click OK.

 10. the volume is still in state healthy, the pv/pvc is in state bound, the volume can not be detached nor can it be mounted by any workload, FailedAttachVolume AttachVolume.Attach failed for volume "" : rpc error: code = Aborted desc = The volume "" is restoring backup.    

The same steps have been performed with an nfs share as backup.I was able to restore the volume on cluster b and mount it on a workload with the issue.

If you need any further information let me know.

**Expected behavior**
Being able to restore volume from backup into any cluster from s3 mino 

**Environment:**
 - Longhorn version: 0.7.0
 - Kubernetes version: v1.17.0
 - Node OS type and version: RacherO Srancher/os:v1.5.5 /Ubuntu 18.04

two seperate Rancher Clusters with Longhorn and a configured S3 Minio outside of the Cluster,

**Comment by yasker** [comment]
@j4y4r Is cluster b using RancherOS? Since there are a bunch of known issues with RancherOS, we don't recommend using RancherOS for Longhorn.

**Comment by j4y4r** [comment]
@yasker No, cluster b ist using Ubuntu.
As mentioned in the issue, is Backup und Restore Szenario works when using NFS as backup target, which would suggest the problem is not the OS.

**Comment by yasker** [comment]
@j4y4r We haven't updated the document yet about RancherOS, and we will update it soon.

Also, it's weird that S3 doesn't work but NFS works. If you can reproduce the issue, can you send us a support bundle to longhorn-support-bundle@rancher.com ? We want to take a look.

**Comment by j4y4r** [comment]
@yasker 
As requested i send you an Email regarding the issue.

**Comment by yasker** [comment]
@j4y4r It seems there are some misconfiguration or network issue (probably DNS issue) on S3
```
Fail to list s3: AWS Error:  RequestError send request failed Get https://minio1k8s1.d
igimagical.com:9000/longhorn?delimiter=%!F(MISSING)&prefix=%!F(MISSING): dial tcp: lookup minio1k8s1.digimagical.com on 10.43.0.10:53: no such host\\n\" pkg=s3"
```

The full log from `longhorn-manager-4cjnw`
```
2020-02-27T09:49:36.670922679Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: time=\"2020-02-27T09:49:30Z\" level=info msg=\"Creating volume /host/var/lib/rancher/longhorn/replicas/testrestiore-a02c5d35, size 10
73741824/512\""
2020-02-27T09:49:36.671322715Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: time=\"2020-02-27T09:49:31Z\" level=info msg=\"Listening on data server 0.0.0.0:10016\""
2020-02-27T09:49:36.671572987Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: time=\"2020-02-27T09:49:31Z\" level=info msg=\"Listening on sync agent server 0.0.0.0:10017\""
2020-02-27T09:49:36.671598399Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: time=\"2020-02-27T09:49:31Z\" level=info msg=\"Listening on gRPC Replica server 0.0.0.0:10015\""
2020-02-27T09:49:36.671828013Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: time=\"2020-02-27T09:49:31Z\" level=info msg=\"Listening on sync 0.0.0.0:10017\""
2020-02-27T09:49:36.671849438Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: time=\"2020-02-27T09:49:34Z\" level=info msg=\"New connection from: 10.42.0.8:51468\""
2020-02-27T09:49:36.671974583Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: time=\"2020-02-27T09:49:34Z\" level=info msg=\"Opening volume /host/var/lib/rancher/longhorn/replicas/testrestiore-a02c5d35, size 107
3741824/512\""
2020-02-27T09:49:36.671997104Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: time=\"2020-02-27T09:49:36Z\" level=error msg=\"{\\n\\n}\" pkg=s3"
2020-02-27T09:49:36.672201413Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: time=\"2020-02-27T09:49:36Z\" level=error msg=\"Fail to list s3: AWS Error:  RequestError send request failed Get https://minio1k8s1.
digimagical.com:9000/longhorn?delimiter=%!F(MISSING)&prefix=%!F(MISSING): dial tcp: lookup minio1k8s1.digimagical.com on 10.43.0.10:53: no such host\\n\" pkg=s3"
2020-02-27T09:49:36.673265852Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: panic: runtime error: invalid memory address or nil pointer dereference"
2020-02-27T09:49:36.673357242Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fbb5d]"
2020-02-27T09:49:36.673404193Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: "
2020-02-27T09:49:36.673418045Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: goroutine 31 [running]:"
2020-02-27T09:49:36.673430703Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: sync.(*Mutex).Lock(...)"
2020-02-27T09:49:36.673443292Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: \t/usr/local/go/src/sync/mutex.go:74"
2020-02-27T09:49:36.673481791Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: github.com/longhorn/longhorn-engine/pkg/engine/replica.(*RestoreStatus).FinishRestore(0x0)"
2020-02-27T09:49:36.673501009Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: \t/go/src/github.com/longhorn/longhorn-engine/pkg/engine/replica/backup.go:68 +0x2d"
2020-02-27T09:49:36.673514974Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: github.com/longhorn/longhorn-engine/pkg/engine/sync/rpc.(*SyncAgentServer).finishRestoreNoLock(0xc0000f77a0, 0x0, 0x0, 0x34, 0xc00031
8280)"
2020-02-27T09:49:36.673527107Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: \t/go/src/github.com/longhorn/longhorn-engine/pkg/engine/sync/rpc/server.go:195 +0x5d"
2020-02-27T09:49:36.673540764Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: github.com/longhorn/longhorn-engine/pkg/engine/sync/rpc.(*SyncAgentServer).BackupRestore(0xc0000f77a0, 0x109e300, 0xc000312b10, 0xc00
033eaf0, 0x0, 0x0, 0x0)"
2020-02-27T09:49:36.673593711Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: \t/go/src/github.com/longhorn/longhorn-engine/pkg/engine/sync/rpc/server.go:454 +0x5fe"
2020-02-27T09:49:36.673610899Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: github.com/longhorn/longhorn-engine/pkg/engine/sync/rpc._SyncAgentService_BackupRestore_Handler(0xe7f120, 0xc0000f77a0, 0x109e300, 0xc000312b10, 0xc00033eaa0, 0x0, 0x109e300, 0xc000312b10, 0xc0003c4000, 0x15c)"
2020-02-27T09:49:36.673628206Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: \t/go/src/github.com/longhorn/longhorn-engine/pkg/engine/sync/rpc/rpc.pb.go:1202 +0x217"
2020-02-27T09:49:36.673669877Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001e00, 0x10a6720, 0xc0002c2a80, 0xc00035a200, 0xc0002a46f0, 0x18979f0, 0x0, 0x0, 0x0)"
2020-02-27T09:49:36.673688747Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: \t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:998 +0x46a"
2020-02-27T09:49:36.673705203Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: google.golang.org/grpc.(*Server).handleStream(0xc000001e00, 0x10a6720, 0xc0002c2a80, 0xc00035a200, 0x0)"
2020-02-27T09:49:36.673724813Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: \t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:1278 +0xd97"
2020-02-27T09:49:36.673784465Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003441e0, 0xc000001e00, 0x10a6720, 0xc0002c2a80, 0xc00035a200)"
2020-02-27T09:49:36.673802564Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: \t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:717 +0xbb"
2020-02-27T09:49:36.673815929Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: created by google.golang.org/grpc.(*Server).serveStreams.func1"
2020-02-27T09:49:36.673860366Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: \t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:715 +0xa1"
2020-02-27T09:49:36.673874379Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: time=\"2020-02-27T09:49:36Z\" level=warning msg=\"Replica sync agent at 0.0.0.0:10017 is down: exit status 2\""
2020-02-27T09:49:36.673886028Z time="2020-02-27T09:49:36Z" level=warning msg="testrestiore-r-e9930b71: time=\"2020-02-27T09:49:36Z\" level=fatal msg=\"Error running start replica command: exit status 2\""
2020-02-27T09:49:36.781447526Z time="2020-02-27T09:49:36Z" level=warning msg="Instance testrestiore-r-e9930b71 is state error, error message: exit status 1"
```

**Comment by j4y4r** [comment]
@yasker 
indeed, there was an issue with dns, i fixed that later, otherwise i would not have been able to perform the steps mentioned on cluster b.

Please take a look at the logfiles from yesterday afternoon, i tried to restore and backup a volume beofre creating the support bundle.

**Comment by j4y4r** [comment]
@yasker thanks for looking into this, indeed interesting that only some pods seems to have the dns issue, since both clusters are in the same network.
I will review the configurations and update the issue with my findings.

**Comment by j4y4r** [comment]
@yasker 
in this case RancherOS works better than Ubuntu, because of a DNS resolution problem when it comes to the default configuration of Ubuntu.
Since the Minio i use is not public available i hit this issue , which is mentioned here 
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues

I tried to reproduce the issue with a fresh deployed Cluster running on RancherOS, added Longhorn and setup the Minio as Backup.
The steps above were performed again, i was able to backup a new volume and restore a volume from another cluster.

When using Ubuntu the config passed to the pods by the nodes has localhost as DNS, so the instance-manager can't reach the minio node.
I tired this workaround for legacy reslov.conf
https://www.freedesktop.org/software/systemd/man/systemd-resolved.html#/etc/resolv.conf
i was able to restore the volume properly with this workaround and use it inside a workload.
