### ISSUE TITLE
[BUG] Replica crash with NPE when restoring sometime

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1162]
**Describe the bug**
Replica crash with NPE when restoring invalid backup.

**To Reproduce**
1. Make a backup
2. Corrupt the backup, e.g.change the size to not the multiple of 2MiB.
3. Restore the backup.

**Expected behavior**
Should error out but replica shouldn't crash.

**Log**
```
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="Instance tr-r-5d4f37c8 is state error, error message: exit status 1"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=debug msg="Instance handler updated instance tr-r-5d4f37c8 state, old state running, new state error"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="Instance tr-r-5d4f37c8 crashed on Instance Manager instance-manager-r-8804d68a at yasker-longhorn-dev-1, try to get log"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Creating volume /host/opt/host-vol1/replicas/tr-3425fdc3, size 107376640/512""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Listening on gRPC Replica server 0.0.0.0:10045""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Listening on data server 0.0.0.0:10046""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Listening on sync agent server 0.0.0.0:10047""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Listening on sync 0.0.0.0:10047""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:18Z" level=info msg="New connection from: 10.42.2.71:43484""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:18Z" level=info msg="Opening volume /host/opt/host-vol1/replicas/tr-3425fdc3, size 107376640/512""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: panic: runtime error: invalid memory address or nil pointer dereference"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fddbd]"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: "
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: goroutine 14 [running]:"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: sync.(*Mutex).Lock(...)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/usr/local/go/src/sync/mutex.go:74"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: github.com/longhorn/longhorn-engine/pkg/replica.(*RestoreStatus).FinishRestore(0x0)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/pkg/replica/backup.go:68 +0x2d"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: github.com/longhorn/longhorn-engine/pkg/sync/rpc.(*SyncAgentServer).finishRestoreNoLock(0xc0002c17a0, 0x0, 0x0, 0x34, 0xc000032280)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/pkg/sync/rpc/server.go:222 +0x5d"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: github.com/longhorn/longhorn-engine/pkg/sync/rpc.(*SyncAgentServer).BackupRestore(0xc0002c17a0, 0x109d5e0, 0xc00033a750, 0xc0003545a0, 0x0, 0x0, 0x0)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/pkg/sync/rpc/server.go:555 +0x5fe"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: github.com/longhorn/longhorn-engine/proto/ptypes._SyncAgentService_BackupRestore_Handler(0xe825e0, 0xc0002c17a0, 0x109d5e0, 0xc00033a750, 0xc000354550, 0x0, 0x109d5e0, 0xc00033a750, 0xc0003c2000, 0x120)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/proto/ptypes/syncagent.pb.go:1379 +0x217"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000094900, 0x10a5a00, 0xc000095500, 0xc000366100, 0xc000118750, 0x188ea08, 0x0, 0x0, 0x0)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:998 +0x46a"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: google.golang.org/grpc.(*Server).handleStream(0xc000094900, 0x10a5a00, 0xc000095500, 0xc000366100, 0x0)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:1278 +0xd97"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00011c550, 0xc000094900, 0x10a5a00, 0xc000095500, 0xc000366100)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:717 +0xbb"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: created by google.golang.org/grpc.(*Server).serveStreams.func1"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:715 +0xa1"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:19Z" level=warning msg="Replica sync agent at 0.0.0.0:10047 is down: exit status 2""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:19Z" level=fatal msg="Error running start replica command: exit status 2""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="Instance tr-r-5d4f37c8 is state error, error message: exit status 1"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="Instance tr-r-5d4f37c8 crashed on Instance Manager instance-manager-r-8804d68a at yasker-longhorn-dev-1, try to get log"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Creating volume /host/opt/host-vol1/replicas/tr-3425fdc3, size 107376640/512""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Listening on gRPC Replica server 0.0.0.0:10045""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Listening on data server 0.0.0.0:10046""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Listening on sync agent server 0.0.0.0:10047""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Listening on sync 0.0.0.0:10047""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:18Z" level=info msg="New connection from: 10.42.2.71:43484""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:18Z" level=info msg="Opening volume /host/opt/host-vol1/replicas/tr-3425fdc3, size 107376640/512""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: panic: runtime error: invalid memory address or nil pointer dereference"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fddbd]"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: "
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: goroutine 14 [running]:"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: sync.(*Mutex).Lock(...)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/usr/local/go/src/sync/mutex.go:74"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: github.com/longhorn/longhorn-engine/pkg/replica.(*RestoreStatus).FinishRestore(0x0)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/pkg/replica/backup.go:68 +0x2d"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: github.com/longhorn/longhorn-engine/pkg/sync/rpc.(*SyncAgentServer).finishRestoreNoLock(0xc0002c17a0, 0x0, 0x0, 0x34, 0xc000032280)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/pkg/sync/rpc/server.go:222 +0x5d"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: github.com/longhorn/longhorn-engine/pkg/sync/rpc.(*SyncAgentServer).BackupRestore(0xc0002c17a0, 0x109d5e0, 0xc00033a750, 0xc0003545a0, 0x0, 0x0, 0x0)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/pkg/sync/rpc/server.go:555 +0x5fe"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: github.com/longhorn/longhorn-engine/proto/ptypes._SyncAgentService_BackupRestore_Handler(0xe825e0, 0xc0002c17a0, 0x109d5e0, 0xc00033a750, 0xc000354550, 0x0, 0x109d5e0, 0xc00033a750, 0xc0003c2000, 0x120)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/proto/ptypes/syncagent.pb.go:1379 +0x217"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000094900, 0x10a5a00, 0xc000095500, 0xc000366100, 0xc000118750, 0x188ea08, 0x0, 0x0, 0x0)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:998 +0x46a"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: google.golang.org/grpc.(*Server).handleStream(0xc000094900, 0x10a5a00, 0xc000095500, 0xc000366100, 0x0)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:1278 +0xd97"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00011c550, 0xc000094900, 0x10a5a00, 0xc000095500, 0xc000366100)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:717 +0xbb"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: created by google.golang.org/grpc.(*Server).serveStreams.func1"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:715 +0xa1"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:19Z" level=warning msg="Replica sync agent at 0.0.0.0:10047 is down: exit status 2""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:20Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:19Z" level=fatal msg="Error running start replica command: exit status 2""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="Try to get requested log for tr-r-5d4f37c8 on node yasker-longhorn-dev-1"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Creating volume /host/opt/host-vol1/replicas/tr-3425fdc3, size 107376640/512""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Listening on gRPC Replica server 0.0.0.0:10045""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Listening on data server 0.0.0.0:10046""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Listening on sync agent server 0.0.0.0:10047""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:17Z" level=info msg="Listening on sync 0.0.0.0:10047""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:18Z" level=info msg="New connection from: 10.42.2.71:43484""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:18Z" level=info msg="Opening volume /host/opt/host-vol1/replicas/tr-3425fdc3, size 107376640/512""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: panic: runtime error: invalid memory address or nil pointer dereference"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fddbd]"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: "
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: goroutine 14 [running]:"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: sync.(*Mutex).Lock(...)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: t/usr/local/go/src/sync/mutex.go:74"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: github.com/longhorn/longhorn-engine/pkg/replica.(*RestoreStatus).FinishRestore(0x0)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/pkg/replica/backup.go:68 +0x2d"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: github.com/longhorn/longhorn-engine/pkg/sync/rpc.(*SyncAgentServer).finishRestoreNoLock(0xc0002c17a0, 0x0, 0x0, 0x34, 0xc000032280)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/pkg/sync/rpc/server.go:222 +0x5d"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: github.com/longhorn/longhorn-engine/pkg/sync/rpc.(*SyncAgentServer).BackupRestore(0xc0002c17a0, 0x109d5e0, 0xc00033a750, 0xc0003545a0, 0x0, 0x0, 0x0)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/pkg/sync/rpc/server.go:555 +0x5fe"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: github.com/longhorn/longhorn-engine/proto/ptypes._SyncAgentService_BackupRestore_Handler(0xe825e0, 0xc0002c17a0, 0x109d5e0, 0xc00033a750, 0xc000354550, 0x0, 0x109d5e0, 0xc00033a750, 0xc0003c2000, 0x120)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/proto/ptypes/syncagent.pb.go:1379 +0x217"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000094900, 0x10a5a00, 0xc000095500, 0xc000366100, 0xc000118750, 0x188ea08, 0x0, 0x0, 0x0)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:998 +0x46a"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: google.golang.org/grpc.(*Server).handleStream(0xc000094900, 0x10a5a00, 0xc000095500, 0xc000366100, 0x0)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:1278 +0xd97"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00011c550, 0xc000094900, 0x10a5a00, 0xc000095500, 0xc000366100)"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:717 +0xbb"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: created by google.golang.org/grpc.(*Server).serveStreams.func1"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: t/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:715 +0xa1"
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:19Z" level=warning msg="Replica sync agent at 0.0.0.0:10047 is down: exit status 2""
[longhorn-manager-jm2s8] time="2020-04-04T02:25:24Z" level=warning msg="tr-r-5d4f37c8: time="2020-04-04T02:25:19Z" level=fatal msg="Error running start replica command: exit status 2""
```

**Environment:**
 - Longhorn version: v0.8.1-dev
 - Kubernetes version: v1.16.7
 - Node OS type and version: Ubuntu 18.04

**Additional context**

**Comment by yasker** [comment]
Fixed.
