### ISSUE TITLE
[BUG] Longhorn v1.0.0 can't be installed in the same set up where longhorn v1.0.2 was installed and deleted.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1779]
**Describe the bug**
Longhorn v1.0.0 can't be installed in the same set up where longhorn v1.0.2 was installed and deleted.

**To Reproduce**
1. Install longhorn v1.0.2 on a cluster.
2. Delete/uninstall longhorn.
3. Try to install v1.0.0.
4. Installation fails.

**Expected behavior**
Installation should be successful.

**Log**
```
time="2020-09-09T23:26:17Z" level=info msg="Start overwriting built-in settings with customized values"
time="2020-09-09T23:26:17Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/3517/ns/mnt --net=/host/proc/3517/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
E0909 23:26:17.509851       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:967
/usr/local/go/src/runtime/panic.go:212
/usr/local/go/src/runtime/signal_unix.go:695
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go:108
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go:45
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:303
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:219
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:218
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:177
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:196
/go/src/github.com/longhorn/longhorn-manager/upgrade/upgrade.go:88
/go/src/github.com/longhorn/longhorn-manager/upgrade/upgrade.go:66
/go/src/github.com/longhorn/longhorn-manager/app/daemon.go:120
/go/src/github.com/longhorn/longhorn-manager/app/daemon.go:60
/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:525
/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/command.go:174
/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:276
/go/src/github.com/longhorn/longhorn-manager/main.go:59
/usr/local/go/src/runtime/proc.go:203
/usr/local/go/src/runtime/asm_amd64.s:1373
time="2020-09-09T23:26:17Z" level=info msg="Upgrade leader lost: khush-test-lh-wk1"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x143a5ca]

goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x15f5d60, 0x2623f60)
        /usr/local/go/src/runtime/panic.go:967 +0x166
k8s.io/client-go/tools/leaderelection/resourcelock.LeaseSpecToLeaderElectionRecord(...)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go:108
k8s.io/client-go/tools/leaderelection/resourcelock.(*LeaseLock).Get(0xc0000e8000, 0xc00004006a, 0x11, 0xc00035cf90)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go:45 +0x18a
k8s.io/client-go/tools/leaderelection.(*LeaderElector).tryAcquireOrRenew(0xc0001de000, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:303 +0x13e
k8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire.func1()
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:219 +0x65
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00051ea40)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00051ea40, 0x77359400, 0x3ff3333333333333, 0x1, 0xc0000822a0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire(0xc0001de000, 0x1a908a0, 0xc00037e200, 0x1a9a700)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:218 +0x1ee
k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc0001de000, 0x1a908a0, 0xc00037e1c0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:177 +0x6b
k8s.io/client-go/tools/leaderelection.RunOrDie(0x1a908a0, 0xc00037e1c0, 0x1a99ac0, 0xc0000e8000, 0x4a817c800, 0x2540be400, 0x77359400, 0xc0004b77d0, 0xc0000bc460, 0xc0000bc480, ...)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:196 +0x96
github.com/longhorn/longhorn-manager/upgrade.upgrade(0xc00004006a, 0x11, 0xc00004002e, 0xf, 0xc0001b0960, 0xc0002d1570, 0xc000148a00, 0x0, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/upgrade/upgrade.go:88 +0x302
github.com/longhorn/longhorn-manager/upgrade.Upgrade(0x0, 0x0, 0xc00004006a, 0x11, 0x0, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/upgrade/upgrade.go:66 +0x191
github.com/longhorn/longhorn-manager/app.startManager(0xc000122840, 0x1800e2d, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/app/daemon.go:120 +0x3b5
github.com/longhorn/longhorn-manager/app.DaemonCmd.func1(0xc000122840)
        /go/src/github.com/longhorn/longhorn-manager/app/daemon.go:60 +0x2f
github.com/urfave/cli.HandleAction(0x1558f40, 0x18b06a8, 0xc000122840, 0xc000122840, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:525 +0x7c
github.com/urfave/cli.Command.Run(0x1801ea2, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/command.go:174 +0x56e
github.com/urfave/cli.(*App).Run(0xc0001e4540, 0xc00010c000, 0xb, 0xb, 0x0, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:276 +0x7ae
main.main()
        /go/src/github.com/longhorn/longhorn-manager/main.go:59 +0x590
```

**Environment:**
 - Longhorn version: Longhorn v1.0.2
 - Kubernetes version: 18.6
 - Node OS type and version: Ubuntu 18.04

**Comment by yasker** [comment]
We should be able to clear up the `lease` object `longhorn-manager-upgrade-lock` in the `longhorn-system` namespace as a part of uninstallation, so the NPE can be avoided.

**Comment by khushboo-rancher** [comment]
@yasker @meldafrawi This issue is seen when longhorn v1.0.2 is upgraded to master. Raising the priority.

**Comment by yasker** [comment]
@khushboo-rancher I missed a few patches we need to apply on vendor changes. Will fix it soon.

**Comment by yasker** [comment]
@khushboo-rancher Updated vendor merged. Can you retest it?

**Comment by khushboo-rancher** [comment]
The upgrade from v1.0.2 to master is working now.

**Comment by PhanLe1010** [comment]
**Test steps:**
1. Install Longhorn master
1. Simulate a Helm uninstallation by doing:
   1. `kubectl apply -f deploy/uninstall/uninstall.yaml`. Wait for the uninstallation job to finish
   1. `kubectl delete -f deploy/install/01-prerequisite/02-serviceaccount.yaml`
   1. `kubectl delete -f deploy/install/01-prerequisite/03-crd.yaml`
   1. `kubectl delete -f deploy/install/01-prerequisite/04-default-setting.yaml`
   1. `kubectl delete -f deploy/install/01-prerequisite/05-podsecuritypolicy.yaml`
   1.  `kubectl delete -f deploy/install/01-prerequisite/06-storageclass.yaml`
   1.  `kubectl delete -f deploy/install/02-components/ -R`
   1.   `kubectl delete -f deploy/uninstall/uninstall.yaml`
1. Install Longhorn v1.0.0
1. Verify that the installation succeeds with no error. Basic functionalities work ok.
1. Upgrade to Longhorn v1.0.2
1. Verify that the upgrade succeeds with no error. Basic functionalities work ok.

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master ```11/19/2020```

Validation - **Pass**

Longhorn v1.0.0 can be installed in a set up where longhorn v1.0.2 was installed and deleted. The `lease` object `longhorn-manager-upgrade-lock` is getting removed on uninstallation.
