### ISSUE TITLE
[Question] disk failure/volume failed fsck check.

### ISSUE THREAD

**Issue by arturmon** [longhorn/longhorn#1911]
Good afternoon.
For some unknown reason, we have the following error in the pod:
```
  Normal   Scheduled               94m                default-scheduler        Successfully assigned jenkins-test/jenkins-deployment-785fbb7f55-27lch to kube-worker-01
  Normal   SuccessfulAttachVolume  94m                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-c86191c6-b5a8-4b51-3333-d31eb5bf3333"
  Warning  FailedMount             93m                kubelet                  MountVolume.SetUp failed for volume "pvc-c86191c6-b5a8-4b51-3333-d31eb5bf3333" : rpc error: code = Internal desc = 'fsck' found errors on device /dev/longhorn/pvc-c86191c6-b5a8-4b51-3333-d31eb5bf3333 but could not correct them: fsck from util-linux 2.31.1
/dev/longhorn/pvc-c86191c6-b5a8-4b51-3333-d31eb5bf3333: recovering journal
/dev/longhorn/pvc-c86191c6-b5a8-4b51-3333-d31eb5bf3333 contains a file system with errors, check forced.
/dev/longhorn/pvc-c86191c6-b5a8-4b51-3333-d31eb5bf3333: Deleted inode 4896 has zero dtime.  FIXED.
/dev/longhorn/pvc-c86191c6-b5a8-4b51-3333-d31eb5bf3333: Inode 7428 has an invalid extent node (blk 34239, lblk 0)


/dev/longhorn/pvc-c86191c6-b5a8-4b51-3333-d31eb5bf3333: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
  (i.e., without -a or -p options)
.
```
at the same time in the container, it turns out that the file system is corrupted, jenkins gives the following error:
```
2020-10-26T13:55:38.586375439Z 2020-10-26 13:55:38.585+0000 [id=39]     WARNING hudson.model.RunMap#retrieve: could not load /var/jenkins_home/jobs/pfr-process-engine/jobs/document/branches/master/builds/2
2020-10-26T13:55:38.586407898Z java.io.IOException: Input/output error
2020-10-26T13:55:38.586415896Z  at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
2020-10-26T13:55:38.586423340Z  at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
2020-10-26T13:55:38.586441181Z  at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
2020-10-26T13:55:38.586450449Z  at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
2020-10-26T13:55:38.586457275Z  at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:223)
2020-10-26T13:55:38.586463902Z  at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
2020-10-26T13:55:38.586470691Z  at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
2020-10-26T13:55:38.586477110Z  at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
2020-10-26T13:55:38.586483899Z  at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
2020-10-26T13:55:38.586490450Z  at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
2020-10-26T13:55:38.586497031Z  at java.base/java.io.FilterInputStream.read(FilterInputStream.java:83)
2020-10-26T13:55:38.586503586Z  at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:136)
2020-10-26T13:55:38.586510103Z  at com.thoughtworks.xstream.core.util.XmlHeaderAwareReader.getHeader(XmlHeaderAwareReader.java:79)
2020-10-26T13:55:38.586516740Z  at com.thoughtworks.xstream.core.util.XmlHeaderAwareReader.<init>(XmlHeaderAwareReader.java:61)
2020-10-26T13:55:38.586523937Z  at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65)
2020-10-26T13:55:38.586530489Z Caused: com.thoughtworks.xstream.io.StreamException:  : Input/output error
2020-10-26T13:55:38.586536835Z  at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:69)
2020-10-26T13:55:38.586543431Z  at hudson.XmlFile.unmarshal(XmlFile.java:180)
2020-10-26T13:55:38.586550075Z Caused: java.io.IOException: Unable to read /var/jenkins_home/jobs/pfr-process-engine/jobs/document/branches/master/builds/2/build.xml
2020-10-26T13:55:38.586569309Z  at hudson.XmlFile.unmarshal(XmlFile.java:183)
2020-10-26T13:55:38.586577412Z  at hudson.XmlFile.unmarshal(XmlFile.java:163)
2020-10-26T13:55:38.586584226Z  at org.jenkinsci.plugins.workflow.job.WorkflowRun.reload(WorkflowRun.java:528)
2020-10-26T13:55:38.586591038Z  at hudson.model.Run.<init>(Run.java:351)
2020-10-26T13:55:38.586598077Z  at org.jenkinsci.plugins.workflow.job.WorkflowRun.<init>(WorkflowRun.java:252)
2020-10-26T13:55:38.586606386Z  at jdk.internal.reflect.GeneratedConstructorAccessor74.newInstance(Unknown Source)
2020-10-26T13:55:38.586613573Z  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2020-10-26T13:55:38.586620522Z  at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
2020-10-26T13:55:38.586627108Z  at jenkins.model.lazy.LazyBuildMixIn.loadBuild(LazyBuildMixIn.java:166)
2020-10-26T13:55:38.586633891Z  at jenkins.model.lazy.LazyBuildMixIn$1.create(LazyBuildMixIn.java:143)
2020-10-26T13:55:38.586640488Z  at hudson.model.RunMap.retrieve(RunMap.java:224)
2020-10-26T13:55:38.586647046Z  at hudson.model.RunMap.retrieve(RunMap.java:57)
```
We had the oldest backups and we restored them, but this error was already there, which means the pvc was damaged earlier. The question is why this could happen? and how to avoid it in the future?
our architecture is not quite standard. There are two servers connected to a 1G network, 1 server contains 3 Master, 1 worker, 1 pv. The second server contains: Master 1 piece, Worker 3 pieces, 3 pv. The reason for this `architecture`, these servers are very different in performance, both computational and disk. The third question, is it possible the reason for the output of the file system to pvc, the difference in disk performance on different servers?

https://drive.google.com/file/d/1aecR0jGEVOSL2ENnRxKnvGF1zcJj7tl1/view?usp=sharing

forgot to clarify the servers are zoned.

**Comment by yasker** [comment]
@arturmon You can try to repair the volume manually using fsck first (attach the volume using UI to a node, then you can access it as a normal block device). If that doesn't work, check https://longhorn.io/docs/1.0.2/advanced-resources/data-recovery/data-error/ for a detail steps to recover from corrupted data.

How did you set the backup scheduled? When was your oldest backup? You can have three different schedules, e.g. per month, per week, per day to ensure the best availability of the data.

Sometimes the corrupted disk can be running for a while, then fsck caught the error when remounting it. So make sure you have a good backup schedule to cover short/mid/long term corruption is good.

Also, it can due to one of the underlying disk is bad. See the doc for more details.

**Comment by arturmon** [comment]
Good afternoon.
Daily backups were made. plus sometimes they did it themselves with pens.
Just after the restoration (reconnection is obtained), it was discovered that the disk was damaged.
The disks were physically checked on all replicas in good condition.
The only difference between disks is that on one replica they are slow ((
The question is, can the damage be due to the fact that the backup was made by handles during any disk operations with PVC?
how can you protect yourself from broken backups? maybe you should add a FS check before creating a backup?

**Comment by yasker** [comment]
You meant the physical underlying disk is damaged? The damaged disk is not related to manual backup if that's what did you mean.

Disk failure is in fact a tough question for now. Doing fsck before backup might be helpful but it won't apply to all the setup since Longhorn volume can be used without a filesystem.

Does the SMART system of disk report anything?

**Comment by willzhang** [comment]
prometheus have similar error
```
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Normal   Scheduled    15m                    default-scheduler  Successfully assigned kubesphere-monitoring-system/prometheus-k8s-1 to k8s-master1
  Warning  FailedMount  13m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[prometheus-k8s-db], unattached volumes=[prometheus-k8s-rulefiles-0 prometheus-k8s-token-n2nws config config-out tls-assets prometheus-k8s-db]: timed out waiting for the condition
  Warning  FailedMount  6m49s (x3 over 11m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[prometheus-k8s-db], unattached volumes=[config-out tls-assets prometheus-k8s-db prometheus-k8s-rulefiles-0 prometheus-k8s-token-n2nws config]: timed out waiting for the condition
  Warning  FailedMount  2m19s (x2 over 4m33s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[prometheus-k8s-db], unattached volumes=[config config-out tls-assets prometheus-k8s-db prometheus-k8s-rulefiles-0 prometheus-k8s-token-n2nws]: timed out waiting for the condition
  Warning  FailedMount  6s (x8 over 14m)       kubelet            MountVolume.SetUp failed for volume "pvc-b62a16c1-6d47-4bad-8369-9bd98c473ee6" : rpc error: code = Internal desc = 'fsck' found errors on device /dev/longhorn/pvc-b62a16c1-6d47-4bad-8369-9bd98c473ee6 but could not correct them: fsck from util-linux 2.31.1
/dev/longhorn/pvc-b62a16c1-6d47-4bad-8369-9bd98c473ee6 contains a file system with errors, check forced.
/dev/longhorn/pvc-b62a16c1-6d47-4bad-8369-9bd98c473ee6: Inode 262155 extent tree (at level 1) could be shorter.  IGNORED.
/dev/longhorn/pvc-b62a16c1-6d47-4bad-8369-9bd98c473ee6: Inode 262171 extent tree (at level 1) could be shorter.  IGNORED.
/dev/longhorn/pvc-b62a16c1-6d47-4bad-8369-9bd98c473ee6: Inode 262179 extent tree (at level 1) could be shorter.  IGNORED.
/dev/longhorn/pvc-b62a16c1-6d47-4bad-8369-9bd98c473ee6: Inode 262184 extent tree (at level 1) could be shorter.  IGNORED.
/dev/longhorn/pvc-b62a16c1-6d47-4bad-8369-9bd98c473ee6: Inode 262188 extent tree (at level 1) could be shorter.  IGNORED.
/dev/longhorn/pvc-b62a16c1-6d47-4bad-8369-9bd98c473ee6: Inode 262198 extent tree (at level 1) could be shorter.  IGNORED.
/dev/longhorn/pvc-b62a16c1-6d47-4bad-8369-9bd98c473ee6: Inode 262208 extent tree (at level 1) could be shorter.  IGNORED.
/dev/longhorn/pvc-b62a16c1-6d47-4bad-8369-9bd98c473ee6: Inode 262216 has an invalid extent node (blk 1081353, lblk 0)


/dev/longhorn/pvc-b62a16c1-6d47-4bad-8369-9bd98c473ee6: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
  (i.e., without -a or -p options)
.
  Warning  FailedMount  4s  kubelet  Unable to attach or mount volumes: unmounted volumes=[prometheus-k8s-db], unattached volumes=[prometheus-k8s-token-n2nws config config-out tls-assets prometheus-k8s-db prometheus-k8s-rulefiles-0]: timed out waiting for the condition
```

**Comment by willzhang** [comment]
today i restart a node , and jenkins have error again

```
[root@jenkins argocd]# kubectl -n kubesphere-devops-system describe pods  ks-jenkins-54455f5db8-glhbs
Name:           ks-jenkins-54455f5db8-glhbs
Namespace:      kubesphere-devops-system
Priority:       0
Node:           k8s-node1/10.39.140.251
Start Time:     Fri, 23 Oct 2020 11:59:41 +0800
Labels:         app=ks-jenkins
                chart=jenkins-0.19.0
                component=ks-jenkins-jenkins-master
                heritage=Helm
                pod-template-hash=54455f5db8
                release=ks-jenkins
Annotations:    checksum/config: 95228f5ea09d3b77b59901c52c65636e8cc72c966c597c16b97fac8fb46132e9
                cni.projectcalico.org/podIP: 100.111.156.149/32
Status:         Running
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/ks-jenkins-54455f5db8
Init Containers:
  copy-default-config:
    Container ID:  docker://78cc314d804e1d5360b4ee067a8069822da049d28cdefa11a9ed80d9cbf16b84
    Image:         jenkins/jenkins:2.176.2
    Image ID:      docker-pullable://jenkins/jenkins@sha256:5a1ac8381051dc430dcc90077f648ed1e1b91149b5808a8dea507639eefc563f
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      /var/jenkins_config/apply_config.sh
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 26 Nov 2020 21:54:48 +0800
      Finished:     Thu, 26 Nov 2020 21:55:32 +0800
    Ready:          True
    Restart Count:  2
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:     100m
      memory:  1500Mi
    Environment:
      JENKINS_UC_DOWNLOAD:  http://uc-jenkins-update-center
    Mounts:
      /usr/share/jenkins/ref/secrets/ from secrets-dir (rw)
      /var/jenkins_config from jenkins-config (rw)
      /var/jenkins_home from jenkins-home (rw)
      /var/jenkins_plugins from plugin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ks-jenkins-token-zzhd5 (ro)
Containers:
  ks-jenkins:
    Container ID:  docker://32f2f66b72dc6199f1d765b1373e0c8e6f4d9998e6bfdf853d43d79c16a0593a
    Image:         jenkins/jenkins:2.176.2
    Image ID:      docker-pullable://jenkins/jenkins@sha256:5a1ac8381051dc430dcc90077f648ed1e1b91149b5808a8dea507639eefc563f
    Ports:         8080/TCP, 50000/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)
      --argumentsRealm.roles.$(ADMIN_USER)=admin
    State:          Terminated
      Reason:       Error
      Exit Code:    143
      Started:      Thu, 26 Nov 2020 21:55:37 +0800
      Finished:     Fri, 27 Nov 2020 09:12:21 +0800
    Ready:          False
    Restart Count:  2
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:     100m
      memory:  1500Mi
    Environment:
      JAVA_TOOL_OPTIONS:                  -Xms512m -Xmx512m -XX:MaxRAM=2g -Dhudson.slaves.NodeProvisioner.initialDelay=20 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dhudson.model.LoadStatistics.clock=5000 -Dhudson.model.LoadStatistics.decay=0.2 -Dhudson.slaves.NodeProvisioner.recurrencePeriod=5000 -Dio.jenkins.plugins.casc.ConfigurationAsCode.initialDelay=10000 -verbose:gc -Xloggc:/var/jenkins_home/gc-%t.log -XX:NumberOfGCLogFiles=2 -XX:+UseGCLogFileRotation -XX:GCLogFileSize=100m -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCCause -XX:+PrintTenuringDistribution -XX:+PrintReferenceGC -XX:+PrintAdaptiveSizePolicy -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions 
      JENKINS_OPTS:                       
      ADMIN_PASSWORD:                     <set to the key 'jenkins-admin-password' in secret 'ks-jenkins'>  Optional: false
      ADMIN_USER:                         <set to the key 'jenkins-admin-user' in secret 'ks-jenkins'>      Optional: false
      CASC_JENKINS_CONFIG:                /var/jenkins_home/casc_configs/jenkins.yaml
      com.sun.jndi.ldap.connect.timeout:  15000
      com.sun.jndi.ldap.read.timeout:     60000
      kubernetes.connection.timeout:      60000
      kubernetes.request.timeout:         60000
      EMAIL_SMTP_HOST:                    mail.example.com
      EMAIL_SMTP_PORT:                    465
      EMAIL_USE_SSL:                      False
      EMAIL_FROM_NAME:                    KubeSphere
      EMAIL_FROM_ADDR:                    admin@example.com
      EMAIL_FROM_PASS:                    P@ssw0rd
    Mounts:
      /usr/share/jenkins/ref/plugins/ from plugin-dir (rw)
      /usr/share/jenkins/ref/secrets/ from secrets-dir (rw)
      /var/jenkins_config from jenkins-config (ro)
      /var/jenkins_home from jenkins-home (rw)
      /var/jenkins_home/casc_configs from casc-config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from ks-jenkins-token-zzhd5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  casc-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      jenkins-casc-config
    Optional:  false
  jenkins-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      ks-jenkins
    Optional:  false
  plugin-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  secrets-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  jenkins-home:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  ks-jenkins
    ReadOnly:   false
  ks-jenkins-token-zzhd5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ks-jenkins-token-zzhd5
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                      From     Message
  ----     ------       ----                     ----     -------
  Warning  FailedMount  27m (x14 over 4h12m)     kubelet  Unable to attach or mount volumes: unmounted volumes=[jenkins-home], unattached volumes=[casc-config jenkins-home jenkins-config plugin-dir secrets-dir ks-jenkins-token-zzhd5]: timed out waiting for the condition
  Warning  FailedMount  23m (x17 over 4h21m)     kubelet  Unable to attach or mount volumes: unmounted volumes=[jenkins-home], unattached volumes=[jenkins-config plugin-dir secrets-dir ks-jenkins-token-zzhd5 casc-config jenkins-home]: timed out waiting for the condition
  Warning  FailedMount  8m37s (x120 over 4h17m)  kubelet  MountVolume.SetUp failed for volume "pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf" : rpc error: code = Internal desc = 'fsck' found errors on device /dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf but could not correct them: fsck from util-linux 2.31.1
/dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf contains a file system with errors, check forced.
/dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf: Inode 131224 has an invalid extent node (blk 557148, lblk 0)


/dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
  (i.e., without -a or -p options)
.
  Warning  FailedMount  3m (x20 over 4h23m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[jenkins-home], unattached volumes=[ks-jenkins-token-zzhd5 casc-config jenkins-home jenkins-config plugin-dir secrets-dir]: timed out waiting for the condition
[root@jenkins argocd]# 
```

**Comment by willzhang** [comment]
## jenkins问题

升级系统，重启了下kubesphere devops服务器节点，发现jenkins pod挂掉了

```
[root@jenkins argocd]# kubectl -n kubesphere-devops-system get pods
NAME                                       READY   STATUS    RESTARTS   AGE
ks-jenkins-54455f5db8-glhbs                0/1     Error     2          35d
s2ioperator-0                              1/1     Running   2          35d
uc-jenkins-update-center-cd9464fff-r5txz   1/1     Running   2          11d
```

查看日志，又是longhorn pv无法挂载，像是文件系统坏掉得样子

```
[root@jenkins argocd]# kubectl -n kubesphere-devops-system describe pods  ks-jenkins-54455f5db8-glhbs   
......
Events:
  Type     Reason       Age                     From     Message
  ----     ------       ----                    ----     -------
  Warning  FailedMount  51m (x17 over 3h27m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[jenkins-home], unattached volumes=[plugin-dir secrets-dir ks-jenkins-token-zzhd5 casc-config jenkins-home jenkins-config]: timed out waiting for the condition
  Warning  FailedMount  46m (x20 over 3h52m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[jenkins-home], unattached volumes=[jenkins-home jenkins-config plugin-dir secrets-dir ks-jenkins-token-zzhd5 casc-config]: timed out waiting for the condition
  Warning  FailedMount  42m (x15 over 3h57m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[jenkins-home], unattached volumes=[ks-jenkins-token-zzhd5 casc-config jenkins-home jenkins-config plugin-dir secrets-dir]: timed out waiting for the condition
  Warning  FailedMount  26m (x13 over 3h55m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[jenkins-home], unattached volumes=[jenkins-config plugin-dir secrets-dir ks-jenkins-token-zzhd5 casc-config jenkins-home]: timed out waiting for the condition
  Warning  FailedMount  7m1s (x108 over 3h51m)  kubelet  MountVolume.SetUp failed for volume "pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf" : rpc error: code = Internal desc = 'fsck' found errors on device /dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf but could not correct them: fsck from util-linux 2.31.1
/dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf contains a file system with errors, check forced.
/dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf: Inode 131224 has an invalid extent node (blk 557148, lblk 0)


/dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
  (i.e., without -a or -p options)
.
  Warning  FailedMount  97s (x14 over 3h46m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[jenkins-home], unattached volumes=[casc-config jenkins-home jenkins-config plugin-dir secrets-dir ks-jenkins-token-zzhd5]: timed out waiting for the condition
```

最后提示让使用fsck修复，报错，e2fsck版本太低

```
[root@k8s-node1 ~]# fsck -cvf /dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf 
fsck from util-linux 2.23.2
e2fsck 1.42.9 (28-Dec-2013)
/dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf has unsupported feature(s): metadata_csum
e2fsck: Get a newer version of e2fsck!
```

下载最新版本e2fsprogs

https://distfiles.macports.org/e2fsprogs/

```
wget https://distfiles.macports.org/e2fsprogs/e2fsprogs-1.45.6.tar.gz
tar -zxvf e2fsprogs-1.45.6.tar.gz
cd e2fsprogs-1.45.6
make && make install
```

再次执行

```
[root@k8s-node1 ~]# fsck.ext4 -y /dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf  
e2fsck 1.45.6 (20-Mar-2020)
/dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf contains a file system with errors, check forced.
Pass 1: Checking inodes, blocks, and sizes
Inode 131224 has an invalid extent node (blk 557148, lblk 0)
Clear? yes

Inode 131224 extent tree (at level 1) could be shorter.  Optimize? yes

Inode 131224, i_blocks is 992, should be 0.  Fix? yes

Inode 131227 extent block passes checks, but checksum does not match extent
        (logical block 16, physical block 107664, len 50)
Fix? yes

Inode 131227, i_blocks is 1080, should be 536.  Fix? yes


Running additional passes to resolve blocks claimed by more than one inode...
Pass 1B: Rescanning for multiply-claimed blocks
Multiply-claimed block(s) in inode 131227: 112333
Multiply-claimed block(s) in inode 131343: 112333
Pass 1C: Scanning directories for inodes with multiply-claimed blocks
Pass 1D: Reconciling multiply-claimed blocks
(There are 2 inodes containing multiply-claimed blocks.)

File /support/all_2020-11-24_20.29.26.log (inode #131227, mod time Wed Nov 25 21:00:09 2020) 
  has 1 multiply-claimed block(s), shared with 1 file(s):
        /jobs/demo-devops4t6ff/jobs/demo-pipeline/builds/7/workflow/4.xml (inode #131343, mod time Thu Nov 26 22:33:19 2020)
Clone multiply-claimed blocks? yes

File /jobs/demo-devops4t6ff/jobs/demo-pipeline/builds/7/workflow/4.xml (inode #131343, mod time Thu Nov 26 22:33:19 2020) 
  has 1 multiply-claimed block(s), shared with 1 file(s):
        /support/all_2020-11-24_20.29.26.log (inode #131227, mod time Wed Nov 25 21:00:09 2020)
Multiply-claimed blocks already reassigned or cloned.

Pass 1E: Optimizing extent trees
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Block bitmap differences:  -(87056--87071) -(87088--87167) -(87296--87354) -(87424--87482) -(106512--106618) -(106624--106629) -(107024--107135) +(107664--107713) -108092 +110755 +110769 +110811 +110815 +110846 +110862 +112328 +112342 +112369 +112377 +112382 -123851 -123856 -123897 -(123899--123901) -124722 -124756 -126409 -126435 -126459 -129237 -129246 -129267 -129271 -129284 -129293 -130369 -130377 -130419 -130432 -130471 -132717 -132720 -132774 -132778 -132796 -133198 -133210 -557145 -557148 -557168 -559108 -559165 -559194 -559204 -560608 -560611 -560625 -560628 -563206 -563229 -563259 -563272 -564614 -564645 -564657 -564677 -564743 -564749 -564758 -564763 -564788 -565628 -565918 -565952 +566488 +566493 +566951 +566964 -567308 -568137 -568140 -568144 -568146 -568172 -568198 -568721 -568765 -568779
Fix? yes

Free blocks count wrong for group #0 (22415, counted=22414).
Fix? yes

Free blocks count wrong for group #2 (292, counted=506).
Fix? yes

Free blocks count wrong for group #3 (17798, counted=17985).
Fix? yes

Free blocks count wrong for group #4 (32761, counted=32768).
Fix? yes

Free blocks count wrong for group #17 (31489, counted=31522).
Fix? yes

Free blocks count wrong (1900427, counted=1900858).
Fix? yes


/dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf: ***** FILE SYSTEM WAS MODIFIED *****
/dev/longhorn/pvc-364adde3-9e86-42ee-95e6-c2d9e12a6bdf: 5862/524288 files (0.6% non-contiguous), 196294/2097152 blocks

```

重启pod恢复正常

```
[root@jenkins longhorn]# kubectl -n kubesphere-devops-system get pods
NAME                                       READY   STATUS    RESTARTS   AGE
ks-jenkins-54455f5db8-w7rqw                1/1     Running   0          13m
s2ioperator-0                              1/1     Running   2          35d
uc-jenkins-update-center-cd9464fff-r5txz   1/1     Running   2          11d
```

**Comment by voarsh2** [comment]
Instructions about fsck is a bit vague.
mount: /mnt/pvc-b8122fa6-5d0b-4c21-aa03-5ea24369f254-48955e3e: /mnt/longhorn1/replicas/pvc-b8122fa6-5d0b-4c21-aa03-5ea24369f254-48955e3e is not a block device.

I wasn't able to mount my replica, I also had two similarly named ones on the node which makes it confusing which to choose from
![image](https://user-images.githubusercontent.com/60437695/160266754-fe6ecfe3-8cc0-46da-ad00-bef8ca9b1672.png)
