### ISSUE TITLE
[BUG] Panic down longhorn-csi-plugin by no param in SC

### ISSUE THREAD

**Issue by ysakashita** [longhorn/longhorn#2154]
**Describe the bug**
When parametes in StorageClass are omitted, I try to create RWX PV using it.
Then the longhorn-csi-plugin is down for panic.
Also the following pods are down. 

- csi-attacher
- csi-provisioner
- csi-resizer
- csi-snapshot

**To Reproduce**

1. Deploy the following the manifest.

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-failed
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: failed
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: lh-failed
  volumeMode: Block
```

2. Occer panic down  longhorn-csi-plugin and csi pods.
3. See error log in longhorn-csi-plugin

**Expected behavior**
Correct error handling and no down any pods.

**Log**

```
time="2021-01-05T06:57:39Z" level=info msg="GRPC response: {}"
time="2021-01-05T06:57:39Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerGetCapabilities"
time="2021-01-05T06:57:39Z" level=info msg="GRPC request: {}"
time="2021-01-05T06:57:39Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Rpc\":{\"type\":1}}},{\"Type\":{\"Rpc\":{\"type\":2}}},{\"Type\":{\"Rpc\":{\"type\":9}}},{\"Type\":{\"Rpc\":{\"type\":5}}}]}"
time="2021-01-05T06:58:14Z" level=info msg="GRPC call: /csi.v1.Controller/CreateVolume"
time="2021-01-05T06:58:14Z" level=info msg="GRPC request: {\"capacity_range\":{\"required_bytes\":1073741824},\"name\":\"pvc-df7960eb-a9ec-4501-b994-f789c6fceade\",\"volume_capabilities\":[{\"AccessType\":{\"Block\":{}},\"access_mode\":{\"mode\":5}}]}"
time="2021-01-05T06:58:14Z" level=info msg="ControllerServer create volume req: name:\"pvc-df7960eb-a9ec-4501-b994-f789c6fceade\" capacity_range:<required_bytes:1073741824 > volume_capabilities:<block:<> access_mode:<mode:MULTI_NODE_MULTI_WRITER > > "
panic: assignment to entry in nil map

goroutine 57 [running]:
github.com/longhorn/longhorn-manager/csi.(*ControllerServer).CreateVolume(0xc0002b4000, 0x1d44400, 0xc0002a0b10, 0xc0000d4000, 0xc0002b4000, 0x1, 0xc0003da000)
        /go/src/github.com/longhorn/longhorn-manager/csi/controller_server.go:132 +0x2bd
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler.func1(0x1d44400, 0xc0002a0b10, 0x19a2980, 0xc0000d4000, 0xc0000b99b8, 0x1, 0x1, 0xc00005a700)
        /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:4947 +0x86
github.com/longhorn/longhorn-manager/csi.logGRPC(0x1d44400, 0xc0002a0b10, 0x19a2980, 0xc0000d4000, 0xc00009e4a0, 0xc00009e4c0, 0xc00056ea48, 0x4f5058, 0x1947be0, 0xc0002a0b10)
        /go/src/github.com/longhorn/longhorn-manager/csi/server.go:119 +0x1b2
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler(0x19d7aa0, 0xc0002b4000, 0x1d44400, 0xc0002a0b10, 0xc0002982a0, 0x1b23a78, 0x1d44400, 0xc0002a0b10, 0xc0002fa040, 0x3a)
        /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:4949 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002f22c0, 0x1d5c760, 0xc0002c7c80, 0xc000160000, 0xc000340f00, 0x2a94920, 0x0, 0x0, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/google.golang.org/grpc/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc0002f22c0, 0x1d5c760, 0xc0002c7c80, 0xc000160000, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/google.golang.org/grpc/server.go:1275 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00059cff0, 0xc0002f22c0, 0x1d5c760, 0xc0002c7c80, 0xc000160000)
        /go/src/github.com/longhorn/longhorn-manager/vendor/google.golang.org/grpc/server.go:710 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/longhorn/longhorn-manager/vendor/google.golang.org/grpc/server.go:708 +0xa1
```

**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.18.6
 - Node config
   - OS type and version: Ubuntu 18.04.5 LTS

**Additional context**

I think the issue is a minor problem.
Because longhorn is not intended to be no parameter in StorageClass.
However the down of any CSI pods and longhorn-csi-plugin are not good.

As the root couse of bug, I believe that longhorn-csi-plugin(longhorn-manager) access volumeParameters without nil check.

https://github.com/longhorn/longhorn-manager/blob/v1.1.0/csi/controller_server.go#L132

When the longhorn-csi-plugin is down, it delete csi.socket. 
As result, any CSI pods are down too.

**Comment by joshimoo** [comment]
Thanks for reporting, your analysis is correct and we will fix this in the next release.
As a workaround you should be able to define any dummy parameter for the storage class, so the that CSI driver receives a non nil param map.

**Comment by khushboo-rancher** [comment]
Validated with Longhorn master `01/12/2020`

Validation - **Pass**

Validated creation of PV with a storage class with and without parameters.
