### ISSUE TITLE
[BUG] Longhorn crash due to adding disk to a node that's in evicting/unschedulable 

### ISSUE THREAD

**Issue by bbarclay** [longhorn/longhorn#2250]
I'm not sure what caused this. But it happened twice. 
1. Adding a drive to a node that is set to unscheduled and evict, causes the drive that your adding to crash longhorn, taking down all your drives. Or 
2. When trying to add a drive while draining and unscheduling the main drive on that node, causes it to bug. 

I had this happen twice. You get a white screen of death, all your pods crash and they won't come back online. Uninstalling and reinstalling Longhorn seemed to be the only thing that fixed it. 

There is also the other case, which I thought it might have been, but it didn't seem to be a problem the second go around. That was adding a thin provisioned ZFS pool to longhorn as a drive. This was in Proxmox. But I don't think proxmox is the issue. I think it has to do, with the adding and removing of drives at the same time. But possibly, having to do with the evicting of a drive while also adding a drive. 

This maybe has something to do with RKE2. The third time I setup my cluster with K3s instead of RKE2 because I liked the idea of hosting my datastore on Mysql instead of Etcd. Plus having it external, incase it was something i could fix in the database. That being said, "this is important too" is that, the third time. I did not drain the nodes and try to add a drive at the same time. The other thing I'm fearing. Is that there might be an issue with having the Node set to evict and not schedule, but then not realizing this, and trying to add a drive to an evicted node. Maybe there is an error where it is trying to add, and trying to evict at the same time. Kind of a tug of war between the two systems. "Add" no "Evict". "Add" no "Evict" on and on. Like that. 

I was brave enough to try and see if my speculation on this was causing it to crash.

**Comment by yasker** [comment]
Thanks for the reporting @bbarclay , we will try to reproduce the issue first.

**Comment by joshimoo** [comment]
@khushboo-rancher @meldafrawi once you have capacity can you have a look to see if we can reproduce this issue.

**Comment by meldafrawi** [comment]
Reproduce steps:

- Deploy RKE2 cluster (1 master node, 3 worker nodes)  Ref: https://docs.rke2.io/install/quickstart
- Install Longhorn V1.1.0
- Create a volume and attach it to a node
- Choose a worker node, and set `Eviction Requested: True` and `Node Scheduling: disabled`
- Create a new disk to the chosen worker node instance, attach it, format it and mount it.
- On longhorn UI, add new disk to the chosen node, specify the new disk mount point.
- check longhorn-manager logs

logs:
```
E0301 22:32:02.090586       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 323 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x18238e0, 0x2a87900)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x18238e0, 0x2a87900)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/longhorn/longhorn-manager/controller.(*ReplicaController).enqueueNodeChange(0xc00017f2d0, 0x1a236e0, 0xc000f88a80)
	/go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:588 +0x338
github.com/longhorn/longhorn-manager/controller.NewReplicaController.func3(0x1a236e0, 0xc000f88780, 0x1a236e0, 0xc000f88a80)
	/go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:113 +0x3e
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:205
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x1f4, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:656 +0x1e8
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00095fe18, 0x188fb80, 0xc000759e01)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000759f60)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00095ff60, 0xdf8475800, 0x0, 0x1, 0xc0006d8180)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0000e1b00)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00017e8b0, 0xc0006a9da0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x15ba5a8]

goroutine 323 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x18238e0, 0x2a87900)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/longhorn/longhorn-manager/controller.(*ReplicaController).enqueueNodeChange(0xc00017f2d0, 0x1a236e0, 0xc000f88a80)
	/go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:588 +0x338
github.com/longhorn/longhorn-manager/controller.NewReplicaController.func3(0x1a236e0, 0xc000f88780, 0x1a236e0, 0xc000f88a80)
	/go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:113 +0x3e
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:205
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x1f4, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:656 +0x1e8
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000f81e18, 0x188fb80, 0xc000759e01)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000759f60)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000f81f60, 0xdf8475800, 0x0, 0x1, 0xc0006d8180)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0000e1b00)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00017e8b0, 0xc0006a9da0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

**Comment by yasker** [comment]
Thank you @meldafrawi .

@bbarclay we are able to reproduce the issue. Will fix it in v1.1.1.

**Comment by joshimoo** [comment]
@meldafrawi can you verify, I think this might have been fixed as part of https://github.com/longhorn/longhorn/issues/2208

**Comment by meldafrawi** [comment]
Couldn't reproduce it on `master`
