### ISSUE TITLE
[BUG] sparse tool crash

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2426]
**Describe the bug**

Replace the longhorn-engine with lastest commit `98a2ee802384cf387d0d91d453e5e8d1d795e2c5`, the replica instance manager show panic message
```shell
instance-manager-r-5f7e27e9 replica-manager time="2021-03-31T03:18:15Z" level=info msg="GetReplicaStat: volume-head-003.img"
instance-manager-r-5f7e27e9 replica-manager time="2021-03-31T03:18:15Z" level=info msg="Launching receiver for file volume-head-003.img.meta"
instance-manager-r-5f7e27e9 replica-manager time="2021-03-31T03:18:15Z" level=info msg="Running ssync server for file volume-head-003.img.meta at port 10020"
instance-manager-r-5f7e27e9 replica-manager time="2021-03-31T03:18:15Z" level=info msg="Creating Ssync service"
instance-manager-r-5f7e27e9 replica-manager time="2021-03-31T03:18:15Z" level=error msg="open failed, err: server.getQueryDirectIO failed, err: directIO does not exist in the queries: map[begin:[0] end:[178]]"
instance-manager-r-5f7e27e9 replica-manager 2021/03/31 03:18:15 http: panic serving 10.42.3.240:57022: runtime error: invalid memory address or nil pointer dereference
instance-manager-r-5f7e27e9 replica-manager goroutine 24 [running]:
instance-manager-r-5f7e27e9 replica-manager net/http.(*conn).serve.func1(0xc0000c6e60)
instance-manager-r-5f7e27e9 replica-manager 	/usr/local/go/src/net/http/server.go:1772 +0x139
instance-manager-r-5f7e27e9 replica-manager panic(0xd6b180, 0x18750f0)
instance-manager-r-5f7e27e9 replica-manager 	/usr/local/go/src/runtime/panic.go:975 +0x3e3
instance-manager-r-5f7e27e9 replica-manager github.com/longhorn/sparse-tools/sparse/rest.(*SyncServer).close(0xc000376140, 0x1080de0, 0xc0000e21c0, 0xc0000ca700)
instance-manager-r-5f7e27e9 replica-manager 	/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go:119 +0x63
instance-manager-r-5f7e27e9 replica-manager net/http.HandlerFunc.ServeHTTP(0xc0001d39e0, 0x1080de0, 0xc0000e21c0, 0xc0000ca700)
instance-manager-r-5f7e27e9 replica-manager 	/usr/local/go/src/net/http/server.go:2012 +0x44
instance-manager-r-5f7e27e9 replica-manager github.com/gorilla/mux.(*Router).ServeHTTP(0xc0003660c0, 0x1080de0, 0xc0000e21c0, 0xc0000ca500)
instance-manager-r-5f7e27e9 replica-manager 	/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
instance-manager-r-5f7e27e9 replica-manager net/http.serverHandler.ServeHTTP(0xc000360380, 0x1080de0, 0xc0000e21c0, 0xc0000ca500)
instance-manager-r-5f7e27e9 replica-manager 	/usr/local/go/src/net/http/server.go:2807 +0xa3
instance-manager-r-5f7e27e9 replica-manager net/http.(*conn).serve(0xc0000c6e60, 0x1085d20, 0xc000098700)
instance-manager-r-5f7e27e9 replica-manager 	/usr/local/go/src/net/http/server.go:1895 +0x86c
instance-manager-r-5f7e27e9 replica-manager created by net/http.(*Server).Serve
instance-manager-r-5f7e27e9 replica-manager 	/usr/local/go/src/net/http/server.go:2933 +0x35c
instance-manager-r-5f7e27e9 replica-manager [pvc-7905411c-6df8-4c48-bf46-f3dd82ae58c8-r-2721690e] time="2021-03-31T03:18:15Z" level=info msg="Closing volume"
```

**To Reproduce**
1. Replace the longhorn-engine with lastest commit `98a2ee802384cf387d0d91d453e5e8d1d795e2c5`
2. Watch the log of replica instance manager
3. Delete some replicas

**Expected behavior**
No crash log should be displayed,

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**
It should be the side effect with PR https://github.com/longhorn/sparse-tools/pull/70

**Comment by joshimoo** [comment]
@cclhsu This happens because the request is missing the directIO query param, see
https://github.com/longhorn/sparse-tools/blob/deeff402e893e8af727b6f75ae1db3286303bf80/sparse/rest/handlers.go#L77

**Comment by jenting** [comment]
Updates: all images I used are v1.1.1-preview1 version expect the engine-image is build from the latest master branch.

**Comment by jenting** [comment]
Sorry, I can't find a reproduce way now, I'll update it once I can reproduce it.
Close it.
