### ISSUE TITLE
[BUG] longhorn-manager command panic when unrecognized command

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#2750]
**Describe the bug**
When running longhorn-manager command with unsupported command it throws error.

**To Reproduce**
1. Log into any longhorn-manager pod (or from Rancher UI, click on Execute Shell)
2. Type: `longhorn-command test`

**Expected behavior**
Program should not panic

**Log**
```
2021/06/30 11:09:36 proto: duplicate proto type registered: VersionResponse
panic: Unrecognized command: test

goroutine 1 [running]:
main.cmdNotFound(0xc00027cf20, 0x7ffca288afa8, 0x5)
	/go/src/github.com/longhorn/longhorn-manager/main.go:16 +0xad
github.com/urfave/cli.ShowCommandHelp(0xc00027cf20, 0x7ffca288afa8, 0x5, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:202 +0x2c1
github.com/urfave/cli.glob..func1(0xc00027cf20, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:21 +0x50
github.com/urfave/cli.HandleAction(0x17ac080, 0x1b1eb50, 0xc00027cf20, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:523 +0x11a
github.com/urfave/cli.(*App).Run(0xc00052ea80, 0xc0000a2020, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:285 +0x630
main.main()
	/go/src/github.com/longhorn/longhorn-manager/main.go:67 +0x644
```

**Environment:**
 - Longhorn version: v1.1.2-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Additional context**
n/a

**Comment by kaxing** [comment]
As this a panic-by-design, I will close this bug if no further discussion, `panic(fmt.Errorf("Unrecognized command: %s", command))` - [link to the code](https://github.com/longhorn/longhorn-manager/blob/27c93ca97bf6966c7a946ef223366f3ac6e70d62/main.go#L16)

Thanks to @jenting for the hat tip!
