### ISSUE TITLE
[BUG] Containers crashing then restarting with RO filesystems

### ISSUE THREAD

**Issue by ghabarid** [longhorn/longhorn#2789]
**Describe the bug**
We have some DB PODs (postgresql, mysql etc.). Some of them just stop working after some days. 
For some of them, if we restart the POD, then it recovers. But this is not the case for all of them.

As example of log we get:
Exception data:
    Severity: FATAL
    SqlState: 42501
    MessageText: could not open file "base/13395/2601": Read-only file system

**Environment:**
 - Longhorn version: 1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro: RKE and version: 17.4

**Comment by ghabarid** [comment]
PS: I tried [recovering ](https://longhorn.io/docs/1.1.0/advanced-resources/data-recovery/data-error/)from a replica, but this did not help either.
It would be nice to get info where we have to look, to define the cause root.

**Comment by PhanLe1010** [comment]
RO filesystem is usually caused by the underlying Longhorn volumes being crashed. There are many reasons which lead to volumes being crashed. Most common are CPU exhaustion, network disconnection, slow disk. Can you check those conditions?

**Comment by joshimoo** [comment]
Deleting the pod (i.e. restart) will lead to a detach -> unmount -> attach -> mount cycle.
That should get them up and running again.

There are some fixes for the attach/mount in v1.1.2 so I suggest to update to that version if you can.

**Comment by lexfrei** [comment]
I'm facing the same issue, but I'm not sure about the reason.

My setup is 5x Raspberry Pi 4 with USB drives in it (850/100 MB/s in my tests) and a dedicated 1G switch. I know, it's not the enterprise setup. But, I can't start a Prometheus with Longhorn storage on this setup, the same problem with VictoriaMetrics. The actual size of the partition is 1.4Gb.

Longhorn version is 1.1.2

Prometheus log:

```
level=info ts=2021-07-18T22:08:46.728Z caller=query_logger.go:79 component=activeQueryTracker msg="These queries didn't finish in prometheus' last run:" queries="[{\"query\":\"count by(node) ((kube_pod_status_phase{job=\\\"kube-state-metrics\\\",phase=\\\"Running\\\"} == 1) * on(instance, pod, namespace, cluster) group_left(node) topk by(instance, pod, namespace, cluster) (1, kube_pod_info{job=\\\"kube-state-metrics\\\"})) / max by(node) (kube_node_status_capacity{job=\\\"kube-state-metrics\\\",resource=\\\"pods\\\"} != 1) \\u003e 0.95\",\"timestamp_sec\":1626646108},{\"query\":\"max_over_time(prometheus_notifications_alertmanagers_discovered{job=\\\"kube-prometheus-stack-prometheus\\\",namespace=\\\"monitoring\\\"}[5m]) \\u003c 1\",\"timestamp_sec\":1626646108},{\"query\":\"((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\\\"apiserver\\\",verb=~\\\"LIST|GET\\\"}[1d])) - ((sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\\\"apiserver\\\",le=\\\"1\\\",scope=~\\\"resource|\\\",verb=~\\\"LIST|GET\\\"}[1d])) or vector(0)) + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\\\"apiserver\\\",le=\\\"5\\\",scope=\\\"namespace\\\",verb=~\\\"LIST|GET\\\"}[1d])) + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\\\"apiserver\\\",le=\\\"40\\\",scope=\\\"cluster\\\",verb=~\\\"LIST|GET\\\"}[1d])))) + sum by(cluster) (rate(apiserver_request_total{code=~\\\"5..\\\",job=\\\"apiserver\\\",verb=~\\\"LIST|GET\\\"}[1d]))) / sum by(cluster) (rate(apiserver_request_total{job=\\\"apiserver\\\",verb=~\\\"LIST|GET\\\"}[1d]))\",\"timestamp_sec\":1626646098},{\"query\":\"kube_deployment_status_observed_generation{job=\\\"kube-state-metrics\\\",namespace=~\\\".*\\\"} != kube_deployment_metadata_generation{job=\\\"kube-state-metrics\\\",namespace=~\\\".*\\\"}\",\"timestamp_sec\":1626646108}]"
level=error ts=2021-07-18T22:08:46.729Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: read-only file system"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0xffffda6d9284, 0xb, 0x14, 0x2df2f28, 0x4000b3a930, 0x2df2f28)
	/app/promql/query_logger.go:117 +0x3a4
main.main()
	/app/cmd/prometheus/main.go:462 +0x4c34
```

Can someone tell me the problem is in the performance? The partition size is perry huge for the home lab, but I can’t believe it can't handle the load.

**Comment by PhanLe1010** [comment]
@lexfrei Can you give us details about your setup env using the following template?
```
**Environment:**
 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
```

**Comment by lexfrei** [comment]
**Environment:**
 - Longhorn version: 1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04.2 LTS
   - CPU per node: 1
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe): TLC
   - Network bandwidth between the nodes: 1G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 3


Also, I did a huge mistake in the previous post. My "storage" USB drives just 160 at reading and 25 at writing. So, the 1.5GB partition can be a problem for this drive. Still not sure it has to fail this way.

**Comment by jenting** [comment]
> Also, I did a huge mistake in the previous post. My "storage" USB drives just 160 at reading and 25 at writing. So, the 1.5GB partition can be a problem for this drive. Still not sure it has to fail this way.

You're using TLC SSD but used by USB drive. So the bottleneck probably becomes the bus between the drive <-> host.
160 at reading and 25 at writing, is this IOPS performance test without Longhorn management _or_ with Longhorn managed?

And from the IOPS, it's pretty slow like HDD (even worse than HDD). If the instance-manager engine to instance-manager replica throughput is too slow, the volume might crash and make the filesystem become ReadOnly.
We've improved the performance issue for the HDD disk and we scheduled it to be released at v1.1.3.
