### ISSUE TITLE
[BUG] Upgrade vendor/k8s.io/client-go/tools/leaderelection makes longhorn-manager can't start

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2828]
**Describe the bug**

Upgrade vendor/k8s.io/client-go/tools/leaderelection makes longhorn-manager can't start.

**To Reproduce**

1. Bump Upgrade vendor/k8s.io/client-go/tools/leaderelection makes longhorn-manager
2. Deploy the new longhorn-manager container image

**Expected behavior**

Longhorn manager starts succesfully.

**Log**

```
2021/07/30 06:53:11 proto: duplicate proto type registered: VersionResponse
time="2021-07-30T06:53:11Z" level=info msg="Start overwriting built-in settings with customized values"
W0730 06:53:11.876401       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-07-30T06:53:11Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
I0730 06:53:11.890183       1 leaderelection.go:241] attempting to acquire leader lease  longhorn-system/longhorn-manager-upgrade-lock...
E0730 06:53:11.910539       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1824fe0, 0x2a8bbb0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1824fe0, 0x2a8bbb0)
	/usr/local/go/src/runtime/panic.go:967 +0x166
k8s.io/client-go/tools/leaderelection/resourcelock.LeaseSpecToLeaderElectionRecord(...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go:108
k8s.io/client-go/tools/leaderelection/resourcelock.(*LeaseLock).Get(0xc0001cadc0, 0xc00004008a, 0x14, 0x43e09c)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go:45 +0x18a
k8s.io/client-go/tools/leaderelection.(*LeaderElector).tryAcquireOrRenew(0xc0001250e0, 0xe2)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:327 +0x13e
k8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire.func1()
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:243 +0x65
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00059e9a8)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004ee9a8, 0x77359400, 0x3ff3333333333333, 0x1, 0xc000142a20)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire(0xc0001250e0, 0x1d507c0, 0xc000319ac0, 0x1d5d100)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:242 +0x1ee
k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc0001250e0, 0x1d507c0, 0xc000319a40)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:201 +0x6b
k8s.io/client-go/tools/leaderelection.RunOrDie(0x1d507c0, 0xc000319a40, 0x1d5c420, 0xc0001cadc0, 0x4a817c800, 0x2540be400, 0x77359400, 0xc000319a80, 0xc00043d780, 0xc00043d7a0, ...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:220 +0x96
github.com/longhorn/longhorn-manager/upgrade.upgrade(0xc00004008a, 0x14, 0xc00004004e, 0xf, 0xc0002b5a00, 0xc000427b20, 0xc0001caa00, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/upgrade/upgrade.go:92 +0x350
github.com/longhorn/longhorn-manager/upgrade.Upgrade(0x0, 0x0, 0xc00004008a, 0x14, 0xc0004263f0, 0xc0003ae850)
	/go/src/github.com/longhorn/longhorn-manager/upgrade/upgrade.go:69 +0x191
github.com/longhorn/longhorn-manager/app.startManager(0xc000362840, 0x1a629f8, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/app/daemon.go:143 +0x4d0
github.com/longhorn/longhorn-manager/app.DaemonCmd.func1(0xc000362840)
	/go/src/github.com/longhorn/longhorn-manager/app/daemon.go:73 +0x2f
github.com/urfave/cli.HandleAction(0x177d8c0, 0x1b28b68, 0xc000362840, 0xc000362840, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:525 +0x7c
github.com/urfave/cli.Command.Run(0x1a63a2b, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/command.go:174 +0x56e
github.com/urfave/cli.(*App).Run(0xc0001c2540, 0xc00003a0f0, 0xf, 0xf, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:276 +0x7ae
main.main()
	/go/src/github.com/longhorn/longhorn-manager/main.go:67 +0x644
time="2021-07-30T06:53:11Z" level=info msg="Upgrade leader lost: jenting-k3s-worker-0"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1523b3a]

goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1824fe0, 0x2a8bbb0)
	/usr/local/go/src/runtime/panic.go:967 +0x166
k8s.io/client-go/tools/leaderelection/resourcelock.LeaseSpecToLeaderElectionRecord(...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go:108
k8s.io/client-go/tools/leaderelection/resourcelock.(*LeaseLock).Get(0xc0001cadc0, 0xc00004008a, 0x14, 0x43e09c)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go:45 +0x18a
k8s.io/client-go/tools/leaderelection.(*LeaderElector).tryAcquireOrRenew(0xc0001250e0, 0xe2)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:327 +0x13e
k8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire.func1()
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:243 +0x65
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00059e9a8)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004ee9a8, 0x77359400, 0x3ff3333333333333, 0x1, 0xc000142a20)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire(0xc0001250e0, 0x1d507c0, 0xc000319ac0, 0x1d5d100)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:242 +0x1ee
k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc0001250e0, 0x1d507c0, 0xc000319a40)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:201 +0x6b
k8s.io/client-go/tools/leaderelection.RunOrDie(0x1d507c0, 0xc000319a40, 0x1d5c420, 0xc0001cadc0, 0x4a817c800, 0x2540be400, 0x77359400, 0xc000319a80, 0xc00043d780, 0xc00043d7a0, ...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:220 +0x96
github.com/longhorn/longhorn-manager/upgrade.upgrade(0xc00004008a, 0x14, 0xc00004004e, 0xf, 0xc0002b5a00, 0xc000427b20, 0xc0001caa00, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/upgrade/upgrade.go:92 +0x350
github.com/longhorn/longhorn-manager/upgrade.Upgrade(0x0, 0x0, 0xc00004008a, 0x14, 0xc0004263f0, 0xc0003ae850)
	/go/src/github.com/longhorn/longhorn-manager/upgrade/upgrade.go:69 +0x191
github.com/longhorn/longhorn-manager/app.startManager(0xc000362840, 0x1a629f8, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/app/daemon.go:143 +0x4d0
github.com/longhorn/longhorn-manager/app.DaemonCmd.func1(0xc000362840)
	/go/src/github.com/longhorn/longhorn-manager/app/daemon.go:73 +0x2f
github.com/urfave/cli.HandleAction(0x177d8c0, 0x1b28b68, 0xc000362840, 0xc000362840, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:525 +0x7c
github.com/urfave/cli.Command.Run(0x1a63a2b, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/command.go:174 +0x56e
github.com/urfave/cli.(*App).Run(0xc0001c2540, 0xc00003a0f0, 0xf, 0xf, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:276 +0x7ae
main.main()
	/go/src/github.com/longhorn/longhorn-manager/main.go:67 +0x644
```

**Comment by yasker** [comment]
See https://github.com/longhorn/longhorn-manager/tree/master/patch

**Comment by innobead** [comment]
Closing because of https://github.com/longhorn/longhorn/issues/2757#issuecomment-905031801
