### ISSUE TITLE
[BUG] Longhorn UI Backup View isn't working after some time using a fresh minio S3

### ISSUE THREAD

**Issue by PatrickHuetter** [longhorn/longhorn#2840]
**Describe the bug**
If we configure a fresh installed minio S3 as backup storage for longhorn everything works. A few hours later, after some backups to the s3 have been done, the backup UI in longhorn isn't working anymore. We already tested wether the minio is working. It's working and we can access all s3 features. It also contains backup data. We also tried to re-install the minio instance but the problem with the longhorn-ui re-occurs. 

In the following the error message which gets displayed in the UI:
`error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.2/longhorn [backup ls --volume-only s3://longhorn-k8s@us-east-1/], output , stderr, fatal error: unexpected signal during runtime execution [signal SIGSEGV: segmentation violation code=0x1 addr=0x47 pc=0x7f308c7bf448] runtime stack: runtime.throw(0xe959f3, 0x2a) /usr/local/go/src/runtime/panic.go:1116 +0x72 runtime.sigpanic() /usr/local/go/src/runtime/signal_unix.go:679 +0x46a goroutine 203 [syscall]: runtime.cgocall(0xbb0b90, 0xc00054a5c0, 0xc0005260f0) /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00054a590 sp=0xc00054a558 pc=0x403feb net._C2func_getaddrinfo(0xc00052a1e0, 0x0, 0xc0005190e0, 0xc0005260f0, 0x0, 0x0, 0x0) _cgo_gotypes.go:92 +0x55 fp=0xc00054a5c0 sp=0xc00054a590 pc=0x590615 net.cgoLookupIPCNAME.func1(0xc00052a1e0, 0x2d, 0x2d, 0xc0005190e0, 0xc0005260f0, 0x0, 0xc00054a6a0, 0x5939f2) /usr/local/go/src/net/cgo_unix.go:161 +0xd2 fp=0xc00054a608 sp=0xc00054a5c0 pc=0x596072 net.cgoLookupIPCNAME(0xe705ae, 0x3, 0xc00052a180, 0x2c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...) /usr/local/go/src/net/cgo_unix.go:161 +0x183 fp=0xc00054a718 sp=0xc00054a608 pc=0x591aa3 net.cgoIPLookup(0xc00052f560, 0xe705ae, 0x3, 0xc00052a180, 0x2c) /usr/local/go/src/net/cgo_unix.go:218 +0x67 fp=0xc00054a7b8 sp=0xc00054a718 pc=0x5921d7 runtime.goexit() /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00054a7c0 sp=0xc00054a7b8 pc=0x464fc1 created by net.cgoLookupIP /usr/local/go/src/net/cgo_unix.go:228 +0xc7 goroutine 1 [chan receive]: github.com/honestbee/jobq.(*job).Result(0xc000540000, 0xc00051f100, 0x4, 0x4, 0x5) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/honestbee/jobq/job.go:69 +0x38 github.com/longhorn/backupstore.getVolumeNames(0xc000364120, 0xdf8475800, 0x1094e00, 0xc000139360, 0x0, 0x0, 0xc00039d288, 0xe73a47, 0x1) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/backupstore/config.go:139 +0x392 github.com/longhorn/backupstore.List(0x0, 0x0, 0x7ffc1ffe8285, 0x22, 0x1, 0x0, 0x0, 0x0) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/backupstore/list.go:146 +0x760 github.com/longhorn/backupstore/cmd.doBackupList(0xc000156f20, 0xc00039d3c8, 0x2) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/backupstore/cmd/list.go:67 +0x111 github.com/longhorn/backupstore/cmd.cmdBackupList(0xc000156f20) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/backupstore/cmd/list.go:44 +0x2b github.com/urfave/cli.HandleAction(0xd11160, 0xeafdb0, 0xc000156f20, 0xc000156f20, 0x0) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/app.go:525 +0x7c github.com/urfave/cli.Command.Run(0xe70d1d, 0x4, 0x0, 0x0, 0xc0001face0, 0x1, 0x1, 0xe9370b, 0x28, 0x0, ...) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/command.go:174 +0x56e github.com/urfave/cli.(*App).RunAsSubcommand(0xc0001d0380, 0xc000156c60, 0x0, 0x0) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/app.go:404 +0x8fc github.com/urfave/cli.Command.startApp(0xe7367b, 0x7, 0xe723e4, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/command.go:329 +0x845 github.com/urfave/cli.Command.Run(0xe7367b, 0x7, 0xe723e4, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/command.go:102 +0xa1f github.com/urfave/cli.(*App).Run(0xc0001d01c0, 0xc000138000, 0x5, 0x5, 0x0, 0x0) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/app.go:276 +0x7ae main.longhornCli() /go/src/github.com/longhorn/longhorn-engine/main.go:126 +0xaa3 main.main() /go/src/github.com/longhorn/longhorn-engine/main.go:33 +0x13b goroutine 25 [select]: github.com/honestbee/jobq.(*worker).start.func1(0xc000347590) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/honestbee/jobq/worker.go:19 +0x1ac created by github.com/honestbee/jobq.(*worker).start /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/honestbee/jobq/worker.go:11 +0x3f goroutine 23 [IO wait]: internal/poll.runtime_pollWait(0x7f308db453c8, 0x72, 0xffffffffffffffff) /usr/local/go/src/runtime/netpoll.go:203 +0x55 internal/poll.(*pollDesc).wait(0xc000168e18, 0x72, 0x1000, 0x1000, 0xffffffffffffffff) /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45 internal/poll.(*pollDesc).waitRead(...) /usr/local/go/src/internal/poll/fd_poll_runtime.go:92 internal/poll.(*FD).Read(0xc000168e00, 0xc000378000, 0x1000, 0x1000, 0x0, 0x0, 0x0) /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b net.(*netFD).Read(0xc000168e00, 0xc000378000, 0x1000, 0x1000, 0x436e9c, 0xc000075b70, 0x461970) /usr/local/go/src/net/fd_unix.go:202 +0x4f net.(*conn).Read(0xc0001341b8, 0xc000378000, 0x1000, 0x1000, 0x0, 0x0, 0x0) /usr/local/go/src/net/net.go:184 +0x8e net/http.(*persistConn).Read(0xc0001f37a0, 0xc000378000, 0x1000, 0x1000, 0xc000098000, 0xc000075c70, 0x405e65) /usr/local/go/src/net/http/transport.go:1825 +0x75 bufio.(*Reader).fill(0xc0003665a0) /usr/local/go/src/bufio/bufio.go:100 +0x103 bufio.(*Reader).Peek(0xc0003665a0, 0x1, 0x0, 0x0, 0x1, 0xc0003f8a00, 0x0) /usr/local/go/src/bufio/bufio.go:138 +0x4f net/http.(*persistConn).readLoop(0xc0001f37a0) /usr/local/go/src/net/http/transport.go:1978 +0x1a8 created by net/http.(*Transport).dialConn /usr/local/go/src/net/http/transport.go:1647 +0xc56 goroutine 24 [select]: net/http.(*persistConn).writeLoop(0xc0001f37a0) /usr/local/go/src/net/http/transport.go:2277 +0x11c created by net/http.(*Transport).dialConn /usr/local/go/src/net/http/transport.go:1648 +0xc7b goroutine 26 [select]: github.com/honestbee/jobq.(*worker).start.func1(0xc0003475c0) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/honestbee/jobq/worker.go:19 +0x1ac created by github.com/honestbee/jobq.(*worker).start /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/honestbee/jobq/worker.go:11 +0x3f goroutine 27 [select]: github.com/honestbee/jobq.(*worker).start.func1(0xc0003475f0) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/honestbee/jobq/worker.go:19 +0x1ac created by github.com/honestbee/jobq.(*worker).start /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/honestbee/jobq/worker.go:11 +0x3f goroutine 28 [select]: github.com/honestbee/jobq.(*worker).start.func1(0xc000347620) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/honestbee/jobq/worker.go:19 +0x1ac created by github.com/honestbee/jobq.(*worker).start /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/honestbee/jobq/worker.go:11 +0x3f goroutine 29 [select]: github.com/honestbee/jobq.(*worker).start.func1(0xc000347650) /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/honestbee/jobq/worker.go:13 +0xe4 created by github.com/honestbee/jobq.(*worker).start /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/honestbee/jobq/worker.go:11 +0x3f goroutine 30 [select]: github.com/honestbee/jobq.(*worker).start.func1(0xc000347680) /go/src/github.com/longhorn/longhorn-`

**To Reproduce**
1. Go to 'Longhorn UI'
2. Click on 'Backup'
3. Wait for the backup page with backup listing to occur.
4. You get the error message you see above.

**Expected behavior**
The list of backups in the UI.

**Environment:**
 - Longhorn version: 1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm via Fleet
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 v1.21.3+rke2r1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04 LTS
   - CPU per node: 10
   - Memory per node: 128GB
   - Disk type(e.g. SSD/NVMe): SSD for OS & RKE2 K8S and fast storage in longhorn, HDD for slow storage in longhorn 
   - Network bandwidth between the nodes: 1Gbit/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 23

**Comment by jenting** [comment]
Please try this workaround https://github.com/longhorn/longhorn/issues/2577#issuecomment-834182411

**Comment by jenting** [comment]
If possible, could you please provide the infra information?
We'd like to address it however we can't reproduce it in our environment.

```shell
**Environment:**
 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
```

**Comment by PatrickHuetter** [comment]
> If possible, could you please provide the infra information?
> We'd like to address it however we can't reproduce it in our environment.
> 
> ```shell
> **Environment:**
>  - Longhorn version:
>  - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
>  - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
>    - Number of management node in the cluster:
>    - Number of worker node in the cluster:
>  - Node config
>    - OS type and version:
>    - CPU per node:
>    - Memory per node:
>    - Disk type(e.g. SSD/NVMe):
>    - Network bandwidth between the nodes:
>  - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
>  - Number of Longhorn volumes in the cluster:
> ```

I added the data to the first post.

**Comment by PatrickHuetter** [comment]
> Please try this workaround [#2577 (comment)](https://github.com/longhorn/longhorn/issues/2577#issuecomment-834182411)

The workaround you mentioned is working. Since we're using the helm chart it's not possible to use this directly via helm and will be overwritten on next helm upgrade but as a manual workaround it's working at this time. Hope to see this fixed in the next release or helm chart release.

**Comment by jenting** [comment]
Link to #1768

**Comment by jenting** [comment]
According to https://pkg.go.dev/net#hdr-Name_Resolution
> When cgo is available, the cgo-based resolver is used instead under a variety of conditions: on systems that do not let programs make direct DNS requests (OS X), when the LOCALDOMAIN environment variable is present (even if empty), when the RES_OPTIONS or HOSTALIASES environment variable is non-empty, when the ASR_CONFIG environment variable is non-empty (OpenBSD only), when /etc/resolv.conf or /etc/nsswitch.conf specify the use of features that the Go resolver does not implement, and when the name being looked up ends in .local or is an mDNS name.

could you please exec it the longhorn-manager Pod and provide us
- `printenv` 
- `cat /etc/resolv.conf`
- `cat /etc/nsswitch.conf`

Thanks for your help.

**Comment by PatrickHuetter** [comment]
> According to https://pkg.go.dev/net#hdr-Name_Resolution
> 
> > When cgo is available, the cgo-based resolver is used instead under a variety of conditions: on systems that do not let programs make direct DNS requests (OS X), when the LOCALDOMAIN environment variable is present (even if empty), when the RES_OPTIONS or HOSTALIASES environment variable is non-empty, when the ASR_CONFIG environment variable is non-empty (OpenBSD only), when /etc/resolv.conf or /etc/nsswitch.conf specify the use of features that the Go resolver does not implement, and when the name being looked up ends in .local or is an mDNS name.
> 
> could you please exec it the longhorn-manager Pod and provide us the following command output?
> 
> * `printenv`
> * `cat /etc/resolv.conf`
> * `cat /etc/nsswitch.conf`
> 
> Thanks for your help.

```
root@longhorn-manager-bwzzh:/# printenv          
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
CSI_RESIZER_PORT_12345_TCP_PORT=12345
LONGHORN_BACKEND_PORT_9500_TCP_PORT=9500
CSI_RESIZER_SERVICE_PORT=12345
CSI_SNAPSHOTTER_PORT_12345_TCP_PORT=12345
CSI_ATTACHER_SERVICE_HOST=10.43.86.7
HOSTNAME=longhorn-manager-bwzzh
CSI_PROVISIONER_SERVICE_PORT=12345
CSI_RESIZER_SERVICE_PORT_DUMMY=12345
CSI_PROVISIONER_SERVICE_PORT_DUMMY=12345
LONGHORN_BACKEND_SERVICE_PORT=9500
CSI_PROVISIONER_SERVICE_HOST=10.43.25.48
LONGHORN_MANAGER_SERVICE_PORT_MANAGER=9500
LONGHORN_MANAGER_PORT_9500_TCP_PROTO=tcp
CSI_ATTACHER_SERVICE_PORT_DUMMY=12345
CSI_ATTACHER_PORT_12345_TCP=tcp://10.43.86.7:12345
KUBERNETES_PORT_443_TCP_PROTO=tcp
LONGHORN_BACKEND_SERVICE_HOST=10.43.214.79
KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
CSI_PROVISIONER_PORT=tcp://10.43.25.48:12345
CSI_RESIZER_PORT_12345_TCP_PROTO=tcp
KUBERNETES_PORT=tcp://10.43.0.1:443
PWD=/
HOME=/root
NODE_NAME=k8s-somenode-3
CSI_SNAPSHOTTER_SERVICE_HOST=10.43.71.224
CSI_RESIZER_PORT_12345_TCP_ADDR=10.43.104.86
CSI_ATTACHER_SERVICE_PORT=12345
LONGHORN_FRONTEND_PORT_80_TCP_ADDR=10.43.142.7
CSI_RESIZER_PORT_12345_TCP=tcp://10.43.104.86:12345
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_PORT=443
DEFAULT_SETTING_PATH=/var/lib/longhorn-setting/default-setting.yaml
CSI_SNAPSHOTTER_PORT=tcp://10.43.71.224:12345
CSI_ATTACHER_PORT_12345_TCP_ADDR=10.43.86.7
CSI_SNAPSHOTTER_SERVICE_PORT=12345
CSI_PROVISIONER_PORT_12345_TCP_ADDR=10.43.25.48
CSI_PROVISIONER_PORT_12345_TCP=tcp://10.43.25.48:12345
CSI_ATTACHER_PORT=tcp://10.43.86.7:12345
LONGHORN_BACKEND_PORT_9500_TCP=tcp://10.43.214.79:9500
LONGHORN_FRONTEND_SERVICE_PORT_HTTP=80
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
LONGHORN_FRONTEND_SERVICE_PORT=80
LONGHORN_FRONTEND_SERVICE_HOST=10.43.142.7
LONGHORN_BACKEND_PORT=tcp://10.43.214.79:9500
CSI_ATTACHER_PORT_12345_TCP_PROTO=tcp
CSI_PROVISIONER_PORT_12345_TCP_PORT=12345
TERM=xterm-256color
CSI_PROVISIONER_PORT_12345_TCP_PROTO=tcp
LONGHORN_FRONTEND_PORT_80_TCP=tcp://10.43.142.7:80
LONGHORN_FRONTEND_PORT_80_TCP_PROTO=tcp
GODEBUG=netdns=go
CSI_SNAPSHOTTER_SERVICE_PORT_DUMMY=12345
LONGHORN_MANAGER_SERVICE_HOST=10.43.242.205
CSI_RESIZER_PORT=tcp://10.43.104.86:12345
SHLVL=1
POD_NAMESPACE=longhorn-system
KUBERNETES_SERVICE_PORT=443
CSI_SNAPSHOTTER_PORT_12345_TCP_ADDR=10.43.71.224
LONGHORN_MANAGER_PORT=tcp://10.43.242.205:9500
CSI_RESIZER_SERVICE_HOST=10.43.104.86
CSI_SNAPSHOTTER_PORT_12345_TCP=tcp://10.43.71.224:12345
LONGHORN_FRONTEND_PORT_80_TCP_PORT=80
LONGHORN_BACKEND_PORT_9500_TCP_PROTO=tcp
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LONGHORN_MANAGER_PORT_9500_TCP_PORT=9500
LONGHORN_MANAGER_SERVICE_PORT=9500
CSI_ATTACHER_PORT_12345_TCP_PORT=12345
LONGHORN_MANAGER_PORT_9500_TCP=tcp://10.43.242.205:9500
LONGHORN_MANAGER_PORT_9500_TCP_ADDR=10.43.242.205
POD_IP=10.42.2.241
LONGHORN_FRONTEND_PORT=tcp://10.43.142.7:80
KUBERNETES_SERVICE_HOST=10.43.0.1
LONGHORN_BACKEND_PORT_9500_TCP_ADDR=10.43.214.79
CSI_SNAPSHOTTER_PORT_12345_TCP_PROTO=tcp
LONGHORN_BACKEND_SERVICE_PORT_MANAGER=9500
_=/usr/bin/printenv
```

```
-bwzzh:/# cat /etc/resolv.conf
search longhorn-system.svc.cluster.local svc.cluster.local cluster.local k8s-somenode
nameserver 10.43.0.10
options ndots:5
```

```
root@longhorn-manager-bwzzh:/# cat /etc/nsswitch.conf
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat
group:          compat
shadow:         compat
gshadow:        files

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

**Comment by jenting** [comment]
Sorry again, could you please check the follows:
- the longhorn-manager DaemonSet has mounted the `/var/run`?
- log in to the longhorn-manager Pod and export the following environment variables and runs
   ```shell
   export AWS_ACCESS_KEY_ID=<your-minio-access-key-id>
   export AWS_SECRET_ACCESS_KEY=<your-minio-secret-access-key>
   export AWS_ENDPOINTS=https://minio-service.default:9000
   export AWS_CERT=<minio-certificate>
   export GODEBUG=netdns=2

   /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.2/longhorn backup ls --volume-only s3://longhorn-k8s@us-east-1/
```

**Comment by PatrickHuetter** [comment]
> Sorry again, could you please check the follows:
> 
> * `ldd --version`
> * `ulimit -a`
> * the longhorn-manager DaemonSet has mounted the `/var/run`?
> * log in to the longhorn-manager Pod and export the following environment variables and runs
>   ```shell
>   export AWS_ACCESS_KEY_ID=<your-minio-access-key-id>
>   export AWS_SECRET_ACCESS_KEY=<your-minio-secret-access-key>
>   export AWS_ENDPOINTS=<the-minio-aws-endpoints>
>   export AWS_CERT=<minio-certificate>
>   # you could reference to above values according to your backup target credential secret
>   export GODEBUG=netdns=2
>   
>   /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.2/longhorn backup ls --volume-only s3://longhorn-k8s@us-east-1/
>   ```

```
root@longhorn-manager-bwzzh:/# ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

```
root@longhorn-manager-bwzzh:/# ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 515208
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

```
root@longhorn-manager-bwzzh:/var# ls -alh
total 48K
drwxr-xr-x 1 root root  4.0K Jun 15 10:24 .
drwxr-xr-x 1 root root  4.0K Aug  4 10:35 ..
drwxr-xr-x 2 root root  4.0K Apr 24  2018 backups
drwxr-xr-x 1 root root  4.0K Jun 15 10:24 cache
drwxr-xr-x 1 root root  4.0K Aug  4 10:35 lib
drwxrwsr-x 2 root staff 4.0K Apr 24  2018 local
lrwxrwxrwx 1 root root     9 Jun 15 10:21 lock -> /run/lock
drwxr-xr-x 1 root root  4.0K Jun 15 10:22 log
drwxrwsr-x 2 root mail  4.0K Jun 15 10:21 mail
drwxr-xr-x 2 root root  4.0K Jun 15 10:21 opt
lrwxrwxrwx 1 root root     4 Jun 15 10:21 run -> /run
drwxr-xr-x 2 root root  4.0K Jun 15 10:21 spool
drwxrwxrwt 2 root root  4.0K Jun 15 10:24 tmp
root@longhorn-manager-bwzzh:/var# cd /run/
root@longhorn-manager-bwzzh:/run# ls
lock  mount  secrets  systemd  utmp
root@longhorn-manager-bwzzh:/run# ls -alh
total 24K
drwxr-xr-x 1 root root 4.0K Aug  4 10:35 .
drwxr-xr-x 1 root root 4.0K Aug  4 10:35 ..
drwxrwxrwt 2 root root 4.0K Jun 15 10:21 lock
drwxr-xr-x 2 root root 4.0K Jun 15 10:21 mount
drwxr-xr-x 3 root root 4.0K Aug  4 10:35 secrets
drwxr-xr-x 2 root root 4.0K Jun 15 10:24 systemd
-rw-rw-r-- 1 root utmp    0 Jun 15 10:21 utmp
root@longhorn-manager-bwzzh:/run# mount -ls
overlay on / type overlay (rw,relatime,lowerdir=/var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/216/fs:/var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/213/fs:/var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/212/fs,upperdir=/var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/3232/fs,workdir=/var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/3232/work,xino=off)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,nr_inodes=8004421,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,size=32017684k,nr_inodes=8004421,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
udev on /host/dev type devtmpfs (rw,nosuid,noexec,relatime,size=65946664k,nr_inodes=16486666,mode=755)
devpts on /host/dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /host/dev/shm type tmpfs (rw,nosuid,nodev,size=65590424k,nr_inodes=16397606)
hugetlbfs on /host/dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /host/dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
proc on /host/proc type proc (rw,nosuid,nodev,noexec,relatime)
systemd-1 on /host/proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=0,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=21325)
/dev/vda1 on /etc/resolv.conf type ext4 (rw,relatime) [cloudimg-rootfs]
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k,nr_inodes=8004421)
/dev/vda1 on /etc/hosts type ext4 (rw,relatime) [cloudimg-rootfs]
/dev/vda1 on /dev/termination-log type ext4 (rw,relatime) [cloudimg-rootfs]
/dev/vda1 on /etc/hostname type ext4 (rw,relatime) [cloudimg-rootfs]
/dev/vda1 on /usr/local/sbin type ext4 (rw,relatime) [cloudimg-rootfs]
/dev/vda1 on /var/lib/longhorn type ext4 (rw,relatime) [cloudimg-rootfs]
/dev/vda1 on /var/lib/longhorn-setting type ext4 (ro,relatime) [cloudimg-rootfs]
tmpfs on /run/secrets/kubernetes.io/serviceaccount type tmpfs (ro,relatime,size=32017684k,nr_inodes=8004421)
```

For the last command suggestions: This is just. for testing backup listing of s3 target? So that the binary gives us some error while listing on the cli?

**Comment by jenting** [comment]
> For the last command suggestions: This is just. for testing backup listing of s3 target? So that the binary gives us some error while listing on the cli?

We'd like to see the debug log when setting `export GODEBUG=netdns=2`, which will be at the top of the command output. Appreciate your help.
