### ISSUE TITLE
SMB Disk - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vinid223** [longhorn/longhorn#2985]
Hello,

I am running a cluster on ARM (Raspberry Pi) using K3S and I use Longhorn to manage the volumes. It works like a charm when using the internal storage of the PIs, but I am limited by speed and space. So I decided to connect my Raspberry Pies to my NAS using SMB. I use the CIFS implementation from the [Ubuntu Guide](https://wiki.ubuntu.com/MountWindowsSharesPermanently) to mount the disks.

But, when I transfer a replica to the NAS disk added to longhorn, it fail and gives me the error below. It rebuild in loop whithout success.

I tried with the engine 1.1.1 and 1.1.2

Any clues ?

> 2021-09-06T18:25:45.615394555-04:00 [longhorn-instance-manager] time="2021-09-06T22:25:45Z" level=info msg="Process Manager: prepare to create process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813"
2021-09-06T18:25:45.615825540-04:00 [longhorn-instance-manager] time="2021-09-06T22:25:45Z" level=info msg="Process Manager: created process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813"
2021-09-06T18:25:45.641549717-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:45Z" level=info msg="Creating volume /host/media/andromeda/replicas/pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-785e1387, size 5368709120/512"
2021-09-06T18:25:45.683530053-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:45Z" level=info msg="Starting to create disk" disk=000
2021-09-06T18:25:45.811898222-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:45Z" level=info msg="Finished creating disk" disk=000
2021-09-06T18:25:45.890675179-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:45Z" level=info msg="Listening on sync agent server 0.0.0.0:10002"
2021-09-06T18:25:45.896650219-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:45Z" level=info msg="Listening on gRPC Replica server 0.0.0.0:10000"
2021-09-06T18:25:45.896718791-04:00 time="2021-09-06T22:25:45Z" level=info msg="Listening on data server 0.0.0.0:10001"
2021-09-06T18:25:45.913789590-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:45Z" level=info msg="Listening on sync 0.0.0.0:10002"
2021-09-06T18:25:46.726140118-04:00 [longhorn-instance-manager] time="2021-09-06T22:25:46Z" level=info msg="wait for gRPC service of process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813 to start at localhost:10000"
2021-09-06T18:25:46.740742500-04:00 [longhorn-instance-manager] time="2021-09-06T22:25:46Z" level=info msg="Process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813 has started at localhost:10000"
2021-09-06T18:25:47.517797168-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:47Z" level=info msg="New connection from: 10.42.2.214:46974"
2021-09-06T18:25:47.531690889-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:47Z" level=info msg="Opening volume /host/media/andromeda/replicas/pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-785e1387, size 5368709120/512"
2021-09-06T18:25:47.666281209-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:47Z" level=info msg="Replica server starts to snapshot [cdf57078-7b1a-4c95-853a-ce93fad04b40] volume, user created false, created time 2021-09-06T22:25:47Z, labels map[]"
2021-09-06T18:25:47.674892495-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:47Z" level=info msg="Starting to create disk" disk=cdf57078-7b1a-4c95-853a-ce93fad04b40
2021-09-06T18:25:47.835173123-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:47Z" level=info msg="Finished creating disk" disk=cdf57078-7b1a-4c95-853a-ce93fad04b40
2021-09-06T18:25:47.962789434-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:47Z" level=info msg="Launching receiver for file volume-head-001.img.meta"
2021-09-06T18:25:47.968498614-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:47Z" level=info msg="Running ssync server for file volume-head-001.img.meta at port 10003"
2021-09-06T18:25:47.968549964-04:00 time="2021-09-06T22:25:47Z" level=info msg="Creating Ssync service"
2021-09-06T18:25:47.974547431-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:47Z" level=info msg="open: receiving fileSize: 178, setting up directIO: false"
2021-09-06T18:25:47.991534882-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:47Z" level=info msg="Ssync server opened and ready"
2021-09-06T18:25:48.007852429-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:48Z" level=info msg="Running ssync server for file volume-snap-75602406-f5d3-4151-93c7-460f837ae5ee.img at port 10004"
2021-09-06T18:25:48.008130402-04:00 time="2021-09-06T22:25:48Z" level=info msg="Creating Ssync service"
2021-09-06T18:25:48.013229454-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:48Z" level=info msg="open: receiving fileSize: 5368709120, setting up directIO: true"
2021-09-06T18:25:48.018528684-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:48Z" level=info msg="Closing ssync server"
2021-09-06T18:25:48.025765832-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:48Z" level=info msg="Done running ssync server for file volume-head-001.img.meta at port 10003"
2021-09-06T18:25:48.040131482-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:48Z" level=info msg="Ssync server opened and ready"
2021-09-06T18:25:48.340324222-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:48Z" level=info msg="Running ssync server for file volume-snap-75602406-f5d3-4151-93c7-460f837ae5ee.img.meta at port 10005"
2021-09-06T18:25:48.340406794-04:00 time="2021-09-06T22:25:48Z" level=info msg="Creating Ssync service"
2021-09-06T18:25:48.351576828-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:48Z" level=info msg="Closing ssync server"
2021-09-06T18:25:48.351637141-04:00 time="2021-09-06T22:25:48Z" level=info msg="Done running ssync server for file volume-snap-75602406-f5d3-4151-93c7-460f837ae5ee.img at port 10004"
2021-09-06T18:25:48.351661085-04:00 time="2021-09-06T22:25:48Z" level=info msg="open: receiving fileSize: 177, setting up directIO: false"
2021-09-06T18:25:48.390983865-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:48Z" level=info msg="Ssync server opened and ready"
2021-09-06T18:25:48.400429957-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:48Z" level=info msg="Running ssync server for file volume-snap-fea970e6-9d30-4f76-a63a-a82b5713da55.img at port 10006"
2021-09-06T18:25:48.400505547-04:00 time="2021-09-06T22:25:48Z" level=info msg="Creating Ssync service"
2021-09-06T18:25:48.405411884-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:48Z" level=info msg="open: receiving fileSize: 5368709120, setting up directIO: true"
2021-09-06T18:25:48.417674345-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:48Z" level=info msg="Closing ssync server"
2021-09-06T18:25:48.422987260-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:48Z" level=info msg="Done running ssync server for file volume-snap-75602406-f5d3-4151-93c7-460f837ae5ee.img.meta at port 10005"
2021-09-06T18:25:48.434845198-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:25:48Z" level=info msg="Ssync server opened and ready"
2021-09-06T18:26:01.002596440-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:26:01Z" level=info msg="Reloading the revision counter before processing the first write, the current revision cache is 0, the latest revision counter in file is 0"
2021-09-06T18:28:40.905866259-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:28:40Z" level=info msg="Running ssync server for file volume-snap-fea970e6-9d30-4f76-a63a-a82b5713da55.img.meta at port 10007"
2021-09-06T18:28:40.906007033-04:00 time="2021-09-06T22:28:40Z" level=info msg="Creating Ssync service"
2021-09-06T18:28:40.914147219-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:28:40Z" level=info msg="Closing ssync server"
2021-09-06T18:28:40.914308899-04:00 time="2021-09-06T22:28:40Z" level=info msg="Done running ssync server for file volume-snap-fea970e6-9d30-4f76-a63a-a82b5713da55.img at port 10006"
2021-09-06T18:28:40.922196223-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:28:40Z" level=info msg="open: receiving fileSize: 158, setting up directIO: false"
2021-09-06T18:28:40.983747818-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:28:40Z" level=info msg="Ssync server opened and ready"
2021-09-06T18:28:40.999582648-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:28:40Z" level=info msg="Running ssync server for file volume-snap-cdf57078-7b1a-4c95-853a-ce93fad04b40.img at port 10008"
2021-09-06T18:28:41.004586334-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:28:40Z" level=info msg="Creating Ssync service"
2021-09-06T18:28:41.008950632-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:28:41Z" level=info msg="open: receiving fileSize: 5368709120, setting up directIO: true"
2021-09-06T18:28:41.017433345-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:28:41Z" level=error msg="open failed, err: open: Failed to open/create local source file, path: volume-snap-cdf57078-7b1a-4c95-853a-ce93fad04b40.img, err: open volume-snap-cdf57078-7b1a-4c95-853a-ce93fad04b40.img: invalid argument"
2021-09-06T18:28:41.023538462-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:28:41Z" level=info msg="Closing ssync server"
2021-09-06T18:28:41.023616645-04:00 2021/09/06 22:28:41 http: panic serving 10.42.2.213:35766: runtime error: invalid memory address or nil pointer dereference
2021-09-06T18:28:41.023651385-04:00 goroutine 8255 [running]:
2021-09-06T18:28:41.023684717-04:00 net/http.(*conn).serve.func1(0x400014eaa0)
2021-09-06T18:28:41.023715753-04:00 	/usr/local/go/src/net/http/server.go:1772 +0xfc
2021-09-06T18:28:41.023746678-04:00 panic(0xc311a0, 0x1541010)
2021-09-06T18:28:41.023777029-04:00 	/usr/local/go/src/runtime/panic.go:975 +0x378
2021-09-06T18:28:41.023809047-04:00 github.com/longhorn/sparse-tools/sparse/rest.(*SyncServer).close(0x4000180140, 0xf54ac0, 0x40000e6620, 0x4000346f00)
2021-09-06T18:28:41.023839398-04:00 	/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go:119 +0x58
2021-09-06T18:28:41.023871526-04:00 net/http.HandlerFunc.ServeHTTP(0x40000b52b0, 0xf54ac0, 0x40000e6620, 0x4000346f00)
2021-09-06T18:28:41.023903303-04:00 	/usr/local/go/src/net/http/server.go:2012 +0x40
2021-09-06T18:28:41.023933432-04:00 github.com/gorilla/mux.(*Router).ServeHTTP(0x40005ba180, 0xf54ac0, 0x40000e6620, 0x4000346d00)
2021-09-06T18:28:41.023964449-04:00 	/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/gorilla/mux/mux.go:212 +0xb4
2021-09-06T18:28:41.023994615-04:00 net/http.serverHandler.ServeHTTP(0x40003aa000, 0xf54ac0, 0x40000e6620, 0x4000346d00)
2021-09-06T18:28:41.024024429-04:00 	/usr/local/go/src/net/http/server.go:2807 +0xbc
2021-09-06T18:28:41.024134463-04:00 net/http.(*conn).serve(0x400014eaa0, 0xf599c0, 0x4000416640)
2021-09-06T18:28:41.024166036-04:00 	/usr/local/go/src/net/http/server.go:1895 +0x70c
2021-09-06T18:28:41.024192684-04:00 created by net/http.(*Server).Serve
2021-09-06T18:28:41.024219831-04:00 	/usr/local/go/src/net/http/server.go:2933 +0x2e8
2021-09-06T18:28:41.024255774-04:00 time="2021-09-06T22:28:41Z" level=error msg="Sync agent gRPC server failed to rebuild replica/sync files: replica tcp://10.42.2.213:10015 failed to send file volume-snap-cdf57078-7b1a-4c95-853a-ce93fad04b40.img to 10.42.3.189:10008: failed to send file volume-snap-cdf57078-7b1a-4c95-853a-ce93fad04b40.img to 10.42.3.189:10008: rpc error: code = Unknown desc = openServer failed, err: resp.StatusCode(500) != http.StatusOK"
2021-09-06T18:28:41.024292718-04:00 ERROR: 2021/09/06 22:28:41 grpc: server failed to encode response:  rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil
2021-09-06T18:28:41.024321606-04:00 time="2021-09-06T22:28:41Z" level=info msg="Done running ssync server for file volume-snap-fea970e6-9d30-4f76-a63a-a82b5713da55.img.meta at port 10007"
2021-09-06T18:28:41.051377847-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:28:41Z" level=info msg="Closing volume"
2021-09-06T18:28:41.093086342-04:00 [longhorn-instance-manager] time="2021-09-06T22:28:41Z" level=debug msg="Process Manager: prepare to delete process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813"
2021-09-06T18:28:41.093210227-04:00 [longhorn-instance-manager] time="2021-09-06T22:28:41Z" level=debug msg="Process Manager: deleted process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813"
2021-09-06T18:28:41.093622715-04:00 [longhorn-instance-manager] time="2021-09-06T22:28:41Z" level=debug msg="Process Manager: trying to stop process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813"
2021-09-06T18:28:41.093697639-04:00 [longhorn-instance-manager] time="2021-09-06T22:28:41Z" level=debug msg="Process Manager: wait for process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813 to shutdown before unregistering process"
2021-09-06T18:28:41.093777896-04:00 [longhorn-instance-manager] time="2021-09-06T22:28:41Z" level=info msg="wait for process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813 to shutdown"
2021-09-06T18:28:41.095114708-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813] time="2021-09-06T22:28:41Z" level=warning msg="Received signal interrupt to shutdown"
2021-09-06T18:28:41.095184040-04:00 time="2021-09-06T22:28:41Z" level=warning msg="Starting to execute registered shutdown func github.com/longhorn/longhorn-engine/app/cmd.startReplica.func4"
2021-09-06T18:28:41.113215398-04:00 [longhorn-instance-manager] time="2021-09-06T22:28:41Z" level=info msg="Process Manager: process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813 stopped"
2021-09-06T18:28:41.147364060-04:00 [longhorn-instance-manager] time="2021-09-06T22:28:41Z" level=debug msg="Process Manager: prepare to delete process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813"
2021-09-06T18:28:41.147456761-04:00 [longhorn-instance-manager] time="2021-09-06T22:28:41Z" level=debug msg="Process Manager: deleted process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813"
2021-09-06T18:28:41.147700032-04:00 [longhorn-instance-manager] time="2021-09-06T22:28:41Z" level=info msg="Process Manager: successfully unregistered process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813"
2021-09-06T18:28:41.414684196-04:00 [longhorn-instance-manager] time="2021-09-06T22:28:41Z" level=debug msg="Process Manager: prepare to delete process pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-be9d4813"

**Comment by vinid223** [comment]
Hello @shuo-wu 

I've just enabled the Direct IO feature of my NAS and rebooted/remounted the SMB share and I still get the same error (see below)

I do not know how to check for the Sparse file/file extent feature, but my NAS OS seems to support sparse files.

Is there anything else I can check ?

> 2021-09-07T23:04:48.867790784-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-0df06a26] time="2021-09-08T03:04:48Z" level=error msg="open failed, err: open: Failed to open/create local source file, path: volume-snap-1c1540ac-ed76-4a65-a1e0-9ed80b8c0001.img, err: open volume-snap-1c1540ac-ed76-4a65-a1e0-9ed80b8c0001.img: invalid argument"
2021-09-07T23:04:48.872620630-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-0df06a26] 2021/09/08 03:04:48 http: panic serving 10.42.3.8:59726: runtime error: invalid memory address or nil pointer dereference
2021-09-07T23:04:48.872687315-04:00 goroutine 5573 [running]:
2021-09-07T23:04:48.872706019-04:00 net/http.(*conn).serve.func1(0x40001b6c80)
2021-09-07T23:04:48.872726334-04:00 	/usr/local/go/src/net/http/server.go:1772 +0xfc
2021-09-07T23:04:48.872741871-04:00 panic(0xc33860, 0x1548020)
2021-09-07T23:04:48.872757278-04:00 	/usr/local/go/src/runtime/panic.go:975 +0x378
2021-09-07T23:04:48.872772352-04:00 github.com/longhorn/sparse-tools/sparse/rest.(*SyncServer).close(0x400007e0f0, 0xf587e0, 0x40003bc2a0, 0x4000176700)
2021-09-07T23:04:48.872788667-04:00 	/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go:119 +0x58
2021-09-07T23:04:48.872803260-04:00 net/http.HandlerFunc.ServeHTTP(0x4000064840, 0xf587e0, 0x40003bc2a0, 0x4000176700)
2021-09-07T23:04:48.872818352-04:00 	/usr/local/go/src/net/http/server.go:2012 +0x40
2021-09-07T23:04:48.872832519-04:00 github.com/gorilla/mux.(*Router).ServeHTTP(0x40001cc000, 0xf587e0, 0x40003bc2a0, 0x4000194400)
2021-09-07T23:04:48.872847760-04:00 	/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/gorilla/mux/mux.go:212 +0xb4
2021-09-07T23:04:48.872862167-04:00 net/http.serverHandler.ServeHTTP(0x40000ae000, 0xf587e0, 0x40003bc2a0, 0x4000194400)
2021-09-07T23:04:48.872927574-04:00 	/usr/local/go/src/net/http/server.go:2807 +0xbc
2021-09-07T23:04:48.872943945-04:00 net/http.(*conn).serve(0x40001b6c80, 0xf5d720, 0x40004b0600)
2021-09-07T23:04:48.872959093-04:00 	/usr/local/go/src/net/http/server.go:1895 +0x70c
2021-09-07T23:04:48.872973315-04:00 created by net/http.(*Server).Serve
2021-09-07T23:04:48.872988111-04:00 	/usr/local/go/src/net/http/server.go:2933 +0x2e8
2021-09-07T23:04:48.873002871-04:00 time="2021-09-08T03:04:48Z" level=error msg="Sync agent gRPC server failed to rebuild replica/sync files: replica tcp://10.42.3.8:10000 failed to send file volume-snap-1c1540ac-ed76-4a65-a1e0-9ed80b8c0001.img to 10.42.1.13:10085: failed to send file volume-snap-1c1540ac-ed76-4a65-a1e0-9ed80b8c0001.img to 10.42.1.13:10085: rpc error: code = Unknown desc = openServer failed, err: resp.StatusCode(500) != http.StatusOK"
2021-09-07T23:04:48.873022537-04:00 ERROR: 2021/09/08 03:04:48 grpc: server failed to encode response:  rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil
2021-09-07T23:04:48.902130337-04:00 [pvc-8e0b3d44-592c-4ba2-a713-ea5243bb0cc4-r-0df06a26] time="2021-09-08T03:04:48Z" level=info msg="Closing volume"

**Comment by shuo-wu** [comment]
You can try to export the extent of a file via the tool mentioned in [this comment](https://github.com/longhorn/longhorn/issues/2507#issuecomment-857195496). If the fiemap, aka the extent map of a sparse file, can be exported for a file in the CIFS mount point, I will consider the filesystem supports sparse file.

**Comment by vinid223** [comment]
I wanted to do a follow up.

I finally made the command to run and I get the following error

> Cannot determine file size, errno=75 (Value too large for defined data type)

When I run `ls -lsah` on the file, I can see it is smaller then the actual size.

**Comment by vinid223** [comment]
I abandoned the idea of using my NAS for storage.

I started using additional hard drive, but now I have an issue with it. I guess is should be an other issue for that since is it not related.

**Comment by PhanLe1010** [comment]
Yeah, we never tested Longhorn on SMB storage so we don't know if it satisfies the requirement. We can keep this issue open to see if there are many users interested in this topic.
