### ISSUE TITLE
[BUG] Instance Manager is running out of pthread resources

### ISSUE THREAD

**Issue by fkocik** [longhorn/longhorn#3178]
**Describe the bug**

Instance manager fails to allocate new replica reporting `runtime/cgo: pthread_create failed: Resource temporarily unavailable`.

**To Reproduce**

After a while of normal operating state.
Creating a PVC in longhorn related storage class.
The volume is successfully created and attached but remains in *Degraded* state with on replicas that won't initialize.

**Expected behavior**

The volume is in *Healthy* state.

**Log**

This is the error from one of **instance-manager-r** pod (the one on the node that did not initialize the replica) that is also reported in **longhorn-manager** :
```
[longhorn-instance-manager] time="2021-10-22T06:14:42Z" level=info msg="wait for gRPC service of process pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2 to start at localhost:10570"
[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] runtime/cgo: pthread_create failed: Resource temporarily unavailable
[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] SIGABRT: abort
PC=0xbfdd0b m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0xbfdd0b
stack: frame={sp:0x7ffe37bcd990, fp:0x0} stack=[0x7ffe373cef18,0x7ffe37bcdf50)
00007ffe37bcd890:  0000000000210808  0000002200000003
00007ffe37bcd8a0: [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]  00000000ffffffff  00007fe7d7872000
00007ffe37bcd8b0:  00007ffe37bcd8f8  00007ffe37bcd8e0
00007ffe37bcd8c0:  00007ffe37bcd8f0  0000000000bb775c
00007ffe37bcd8d0:  0000000000000000  00000000004680ce <runtime.callCgoMmap+62>
00007ffe37bcd8e0:  00007ffe37bcd8e0  0000000000000000
00007ffe37bcd8f0:  00007ffe37bcd930  000000000045fe38 [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] <runtime.mmap.func1+88>
00007ffe37bcd900:  00007fe7e9c03000  0000000000001000
00007ffe37bcd910[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] :  0000003200000003  00000000ffffffff
00007ffe37bcd920:  00007fe7e9c03000  00007ffe37bcd970
00007ffe37bcd930:  00007ffe37bcd9a8  0000000000404d3e[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]  <runtime.mmap+158>
00007ffe37bcd940:  [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 00007ffe37bcd978  00007ffe37bcd978
00007ffe37bcd950:  00007ffe37bcd988  0000000000bb775c[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]
00007ffe37bcd960:  00007fe7d7872000  00007ffe37bcd998 [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]
00007ffe37bcd970:  00007ffe37bcd9a8  0000000000bb775c
00007ffe37bcd980[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] :  00007fe7e9c03000  00000000004680ce <[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] runtime.callCgoMmap+62>
00007ffe37bcd990: <0000000000000000[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]   0000000000000000
00007ffe37bcd9a0:  0000000000100000  00007ffe37bcd9d0
00007ffe37bcd9b0:  [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 00007ffe37bcd9e0  00007ffe37bcda80
00007ffe37bcd9c0:  000000000042a48c <runtime.(*pageAlloc).update+604[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] >  00007ffe37bcda90
00007ffe37bcd9d0:  000000000042a48c <[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] runtime.(*pageAlloc).update+604>  00007fe7fe303c00
00007ffe37bcd9e0: [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]  0000000000000008  000000000000fe80
00007ffe37bcd9f0[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] :  0000000000000012  000000003b600000
00007ffe37bcda00[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] :  000000003c000000  000780003c000000
00007ffe37bcda10[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] :  fffffffe7fffffff  ffffffffffffffff
00007ffe37bcda20[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] :  ffffffffffffffff  ffffffffffffffff
00007ffe37bcda30:  ffffffffffffffff  ffffffffffffffff [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]
00007ffe37bcda40:  ffffffffffffffff  ffffffffffffffff
00007ffe37bcda50:  ffffffffffffffff [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]  ffffffffffffffff
00007ffe37bcda60:  ffffffffffffffff  [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] ffffffffffffffff
00007ffe37bcda70:  ffffffffffffffff  [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] ffffffffffffffff
00007ffe37bcda80:  ffffffffffffffff  [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] ffffffffffffffff
runtime: unknown pc 0xbfdd0b
stack: frame={sp:[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 0x7ffe37bcd990, fp:0x0} stack=[0x7ffe373cef18,0x7ffe37bcdf50)
00007ffe37bcd890[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] :  0000000000210808  0000002200000003
00007ffe37bcd8a0: [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]  00000000ffffffff  00007fe7d7872000
00007ffe37bcd8b0:  00007ffe37bcd8f8  00007ffe37bcd8e0
[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 00007ffe37bcd8c0:  00007ffe37bcd8f0  0000000000bb775c
00007ffe37bcd8d0[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] :  0000000000000000  00000000004680ce <[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] runtime.callCgoMmap+62>
00007ffe37bcd8e0:  00007ffe37bcd8e0  [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 0000000000000000
00007ffe37bcd8f0:  00007ffe37bcd930  [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 000000000045fe38 <runtime.mmap.func1+88>
00007ffe37bcd900: [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]  00007fe7e9c03000  0000000000001000
00007ffe37bcd910[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] :  0000003200000003  00000000ffffffff
00007ffe37bcd920[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] :  00007fe7e9c03000  00007ffe37bcd970
00007ffe37bcd930:  00007ffe37bcd9a8  0000000000404d3e [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] <runtime.mmap+158>
00007ffe37bcd940:  00007ffe37bcd978  [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 00007ffe37bcd978
00007ffe37bcd950:  00007ffe37bcd988  [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 0000000000bb775c
00007ffe37bcd960:  00007fe7d7872000  [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 00007ffe37bcd998
00007ffe37bcd970:  00007ffe37bcd9a8 [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]  0000000000bb775c
00007ffe37bcd980:  00007fe7e9c03000 [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]  00000000004680ce <runtime.callCgoMmap+62>
00007ffe37bcd990[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] : <0000000000000000  0000000000000000
[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 00007ffe37bcd9a0:  0000000000100000  00007ffe37bcd9d0
[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 00007ffe37bcd9b0:  00007ffe37bcd9e0  00007ffe37bcda80
00007ffe37bcd9c0:  000000000042a48c <runtime.(*pageAlloc).update+604>  00007ffe37bcda90 [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]
00007ffe37bcd9d0:  000000000042a48c <runtime.(*pageAlloc).update+604> [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]  00007fe7fe303c00
00007ffe37bcd9e0:  0000000000000008  [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 000000000000fe80
00007ffe37bcd9f0:  0000000000000012  [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 000000003b600000
00007ffe37bcda00:  000000003c000000  000780003c000000
[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 00007ffe37bcda10:  fffffffe7fffffff  ffffffffffffffff
[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 00007ffe37bcda20:  ffffffffffffffff  ffffffffffffffff
[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 00007ffe37bcda30:  ffffffffffffffff  ffffffffffffffff
00007ffe37bcda40:  ffffffffffffffff  ffffffffffffffff[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]
00007ffe37bcda50:  ffffffffffffffff  ffffffffffffffff
00007ffe37bcda60:  [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] ffffffffffffffff  ffffffffffffffff
00007ffe37bcda70:  ffffffffffffffff[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]   ffffffffffffffff
00007ffe37bcda80:  ffffffffffffffff  ffffffffffffffff

goroutine 1 [running]:
[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc00004e788 sp=0xc00004e780 pc=0x463f30
runtime.main()
	/usr/local/go/src/runtime/proc.go[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] :133 +0x70 fp=0xc00004e7e0 sp=0xc00004e788 pc=0x437910
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 0xc00004e7e8 sp=0xc00004e7e0 pc=0x466041

rax    0x0
rbx    [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 0x242a880
rcx    0xbfdd0b
rdx    0x0
rdi    [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 0x2
rsi    0x7ffe37bcd990
rbp    0x10c3fdb
rsp    [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 0x7ffe37bcd990
r8     0x0
r9     0x7ffe37bcd990
r10    [pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] 0x8
r11    0x246
r12    0x242bbf0
[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] r13    0x0
r14    0x105f81c
r15    0x0
[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2] rip    0xbfdd0b
rflags 0x246
cs     0x33[pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2]
fs     0x0
gs     0x0
[longhorn-instance-manager] time="2021-10-22T06:14:42Z" level=info msg="Process Manager: process pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2 error out, error msg: exit status 2"
[longhorn-instance-manager] time="2021-10-22T06:14:42Z" level=debug msg="Process update: pvc-f04220b3-0f93-458e-a17a-f4137f3c5d62-r-f797a9f2: state error: Error: exit status 2"
```

**Environment:**
 - Longhorn version: v1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Vanilla
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 5 (but only 3 for Longhorn)
 - Node config
   - OS type and version: Arch Linux with Kernel 5.14.11 / GLibC 2.33
   - Container Runtime : cri-o 1.22 / runc 1.0.2
   - CPU per node: 4
   - Memory per node: 32 GB
   - Disk type(e.g. SSD/NVMe): Mixed NVMe and HDD with two storageclasses using disklabels.
   - Network bandwidth between the nodes: 1000BASTX
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 34

**Additional context**

With a small sized cluster (3 bare-metal hosts with 4-core CPU / 32 Go RAM / 1TB storage) hosting 34 volumes.
All systems OK for 7 days and then creating a new volume : the volume enters a *Degraded* state and one of the replicas could not be scheduled.
Looking at the **instance-manager-r** pod logs show the error above. When restarting the affected pod : all volumes went in Degraded state and full resync was triggered. But, at the end of the process, another (not the same) **instance-manager-r** reports the same error. After waiting the sync to go as far as it cans and restarting all instance-manager-r pods, the cluster went back in stable state.

Seems to be a goroutines leak race condition ?

**Comment by fkocik** [comment]
Hi,

Got a new crash today, here are the CPU/Memory stats for the last three hours :

![im-r-1](https://user-images.githubusercontent.com/34087769/139524823-071467ef-714c-4ab2-b7fe-2015ea13d70d.jpg)
![im-r-3](https://user-images.githubusercontent.com/34087769/139524826-86c29bc1-680a-4fb3-b2f8-9cd3777d9edc.jpg)
![im-r-2](https://user-images.githubusercontent.com/34087769/139524825-6cc0b4c9-9145-4f41-9787-5aad498af0ae.jpg)

Only the last instance above (image im-r-2) is healthy and provide replicas to the others.

**Comment by fkocik** [comment]
Hi,

After removing a volume, my cluster seems to be stable more time (+/- one day).
It seems load related : I cannot host more than 10 replicas by node (currently 33 volumes for 3 nodes).

But, this morning, one of the node is starting to randomly loose replicas and rebuild them (after one or two retries).

Hopefully, I was able to capture a more complete log dump that you can see here (the affected node is Promethee) :

[atlas.txt](https://github.com/longhorn/longhorn/files/7480740/atlas.txt)
[epimethee.txt](https://github.com/longhorn/longhorn/files/7480743/epimethee.txt)
[promethee.txt](https://github.com/longhorn/longhorn/files/7480744/promethee.txt)

The cluster is still up : I'm going to try to generate a support bundle to provide more information.

Regards.

**Comment by fkocik** [comment]
Here is the support bundle :

[longhorn-support-bundle_3f8db42e-6f4b-4e7f-a084-8ae9040adcd8_2021-11-05T05-27-58Z.zip](https://github.com/longhorn/longhorn/files/7480841/longhorn-support-bundle_3f8db42e-6f4b-4e7f-a084-8ae9040adcd8_2021-11-05T05-27-58Z.zip)

**Comment by innobead** [comment]
cc @PhanLe1010 @kaxing

**Comment by jenting** [comment]
Did look at the support bundle, the number of goroutines inside the replica instance manager is not much (63 goroutines).

We did not have a test on Arch Linux, not sure if it is related to OS issue _or_ glibc issue.
If possible, could you please add new nodes with another OS like ubuntu? To see if it's reproducible or not.

**Comment by joshimoo** [comment]
Some additional steps for helping us diagnose this issue:
- check and post the `ulimit -a` inside of the instance-manager pod as well as on the node where you are having this issue
- provide us with the archive generated by https://gist.github.com/joshimoo/afcfa1ebec8a1c0d59f0419d33a1dd38 (need to replace the pid with the pid from an instance-manager that is close to exhaustion, then run this from the same node outside of the instance-manager pod)

**Comment by fkocik** [comment]
Here the results on affected node epimethee today :

```
root@instance-manager-r-8ce321d6:/# ss -na | wc -l
159

root@instance-manager-r-8ce321d6:/# ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 127837
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4194304
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

[root@epimethee lh-trace]# ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 127837
max locked memory           (kbytes, -l) 64
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1048576
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 127837
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```
https://github.com/fkocik/lh-support/blob/main/lh-trace.tar.gz?raw=true

It's a bare-metal setup so I do not have enough resources to reproduce on another Linux distro. I can try to downgrade kernel in order to switch to LTS stream. Don't know if it may help ?

Another interesting result I found is this parameter of the runtime engine (**CRI-O**) : 
```
--pids-limit value    Maximum number of processes allowed in a container (default: 1024) [$CONTAINER_PIDS_LIMIT]
```
Do you think it can be the root cause ?

**Comment by jenting** [comment]
@joshimoo Do you have time to see/analyze the lh-trace result?

**Comment by n0rad** [comment]
I just hit the problem when scaling up my cluster to 5 nodes 23 volumes 3 replicas, using crio too.

```bash
cat /etc/crio/crio.conf
...
[crio.runtime]
pids_limit = 2048
...

systemctl restart crio
```

and restarting controllers fixed the problem on my side

**Comment by n0rad** [comment]
I think I shout victory too fast. After 24hours, the problem comes again on multiple nodes :disappointed:

**Comment by fkocik** [comment]
No incident for 17 days now using :

```
[crio.runtime]
pids_limit = 4096
```
I will now upgrade to **1.2.3** and so reset this counter :-P

**Comment by n0rad** [comment]
Same here (with still 2048) after restarting all nodes to upgrade kube with now 14 to 16 days uptime. 
It was maybe because restarting controllers only was just not enough.

**Comment by strahe** [comment]
Some issue for me, version: v1.2.4.

```
time="2022-05-26T08:37:25Z" level=info msg="Creating Ssync service"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="open: receiving fileSize: 178, setting up directIO: false"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="Ssync server opened and ready"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="Closing ssync server"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="Done running ssync server for file volume-snap-619ccc9d-c366-44e6-9f22-01a4113de938.img.meta at port 10050"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="Running ssync server for file volume-snap-cf936925-c394-4d32-b5b1-e189ec413ca4.img at port 10051"
time="2022-05-26T08:37:25Z" level=info msg="Creating Ssync service"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="open: receiving fileSize: 214748364800, setting up directIO: true"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="Ssync server opened and ready"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="Closing ssync server"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="Done running ssync server for file volume-snap-cf936925-c394-4d32-b5b1-e189ec413ca4.img at port 10051"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="Running ssync server for file volume-snap-cf936925-c394-4d32-b5b1-e189ec413ca4.img.meta at port 10052"
time="2022-05-26T08:37:25Z" level=info msg="Creating Ssync service"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="open: receiving fileSize: 178, setting up directIO: false"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="Ssync server opened and ready"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="Closing ssync server"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="Done running ssync server for file volume-snap-cf936925-c394-4d32-b5b1-e189ec413ca4.img.meta at port 10052"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="Running ssync server for file volume-snap-7763eb0d-4acf-469b-baa8-522c9b40a958.img at port 10053"
time="2022-05-26T08:37:25Z" level=info msg="Creating Ssync service"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="open: receiving fileSize: 214748364800, setting up directIO: true"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] time="2022-05-26T08:37:25Z" level=info msg="Ssync server opened and ready"
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] runtime/cgo: pthread_create failed: Resource temporarily unavailable
runtime/cgo: pthread_create failed: Resource temporarily unavailable
[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] SIGABRT: abort
PC=0xbfa66b m=2 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0xbfa66b
stack: frame={sp:0x7fe32aa5f700, fp:0x0[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] } stack=[0x7fe32a260148,0x7fe32aa5fd48)
00007fe32aa5f600:  0000000000000000  0000000000000000 
00007fe32aa5f610:  0000000000000000  0000000000000000 
00007fe32aa5f620:  0000000000000000  0000000000000000 
00007fe32aa5f630:  0000000000000000  0000000000000000 
00007fe32aa5f640:  0000000000000000  0000000000000000 
00007fe32aa5f650:  0000000000000000  0000000000000000 
00007fe32aa5f660:  0000000000000000  0000000000000000 
00007fe32aa5f670:  0000000000000000  0000000000000000 
00007fe32aa5f680:  0000000000000000  0000000000000000 
00007fe32aa5f690:  0000000000000000  0000000000000000 
00007fe32aa5f6a0:  0000000000000000  0000000000000000 
00007fe32aa5f6b0:  0000000000000000  0000000000000000 
00007fe32aa5f6c0:  0000000000000000  0000000000000000 
00007fe32aa5f6d0:  0000000000000000  0000000000000000 
00007fe32aa5f6e0:  0000000000000000  0000000000000000 
00007fe32aa5f6f0:  0000000000000000  0000000000000000 
00007fe32aa5f700: <0000000000000000  0000000000000000 
00007fe32aa5f710:  0000000000000000  0000000000000000 
00007fe32aa5f720:  0000000000000000  0000000000000000 
00007fe32aa5f730:  0000000000000000  0000000000000000 
00007fe32aa5f740:  0000000000000000  0000000000000000 
00007fe32aa5f750:  0000000000000000  00007fe32aa5f788 
00007fe32aa5f760:  00007fe32aa5f798  0000000000bb42dc 
00007fe32aa5f770:  0000000000000000  00000000004680ce <runtime.callCgoMmap+62> 
00007fe32aa5f780:  fffffffe7fffffff  ffffffffffffffff 
00007fe32aa5f790:  ffffffffffffffff  ffffffffffffffff 
00007fe32aa5f7a0:  ffffffffffffffff  ffffffffffffffff 
00007fe32aa5f7b0:  ffffffffffffffff  ffffffffffffffff 
00007fe32aa5f7c0:  ffffffffffffffff  ffffffffffffffff 
00007fe32aa5f7d0:  ffffffffffffffff  ffffffffffffffff 
00007fe32aa5f7e0:  ffffffffffffffff  ffffffffffffffff 
00007fe32aa5f7f0:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0xbfa66b
stack: frame={sp:[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] 0x7fe32aa5f700, fp:0x0} stack=[0x7fe32a260148,0x7fe32aa5fd48)
00007fe32aa5f600:  0000000000000000  0000000000000000 
00007fe32aa5f610:  0000000000000000  0000000000000000 
00007fe32aa5f620:  0000000000000000  0000000000000000 
00007fe32aa5f630:  0000000000000000  0000000000000000 
00007fe32aa5f640:  0000000000000000  0000000000000000 
00007fe32aa5f650:  0000000000000000  0000000000000000 
00007fe32aa5f660:  0000000000000000  0000000000000000 
00007fe32aa5f670:  0000000000000000  0000000000000000 
00007fe32aa5f680:  0000000000000000  0000000000000000 
00007fe32aa5f690:  0000000000000000  0000000000000000 
00007fe32aa5f6a0:  0000000000000000  0000000000000000 
00007fe32aa5f6b0:  0000000000000000  0000000000000000 
00007fe32aa5f6c0:  0000000000000000  0000000000000000 
00007fe32aa5f6d0:  0000000000000000  0000000000000000 
00007fe32aa5f6e0:  0000000000000000  0000000000000000 
00007fe32aa5f6f0:  0000000000000000  0000000000000000 
00007fe32aa5f700: <0000000000000000  0000000000000000 
00007fe32aa5f710:  0000000000000000  0000000000000000 
00007fe32aa5f720:  0000000000000000  0000000000000000 
00007fe32aa5f730:  0000000000000000  0000000000000000 
00007fe32aa5f740:  0000000000000000  0000000000000000 
00007fe32aa5f750:  0000000000000000  00007fe32aa5f788 
00007fe32aa5f760:  00007fe32aa5f798  0000000000bb42dc 
00007fe32aa5f770:  0000000000000000  00000000004680ce <runtime.callCgoMmap+62> 
00007fe32aa5f780:  fffffffe7fffffff  ffffffffffffffff 
00007fe32aa5f790:  ffffffffffffffff  ffffffffffffffff 
00007fe32aa5f7a0:  ffffffffffffffff  ffffffffffffffff 
00007fe32aa5f7b0:  ffffffffffffffff  ffffffffffffffff 
00007fe32aa5f7c0:  ffffffffffffffff  ffffffffffffffff 
00007fe32aa5f7d0: [pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6]  ffffffffffffffff  ffffffffffffffff 
00007fe32aa5f7e0:  ffffffffffffffff  ffffffffffffffff 
00007fe32aa5f7f0:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7fe32922f2a0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0001b6598, 0x72, 0x0, 0x0, 0xe790a6)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0001b6580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc0001b6580, 0x37e11d600, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0003d60e0, 0xc00058e090, 0xc00058e098, 0x18)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0003d60e0, 0xeb6480, 0xc000182a80, 0x1098ba0, 0xc000430040)
	/usr/local/go/src/net/tcpsock.go:261 +0x64
google.golang.org/grpc.(*Server).Serve(0xc000182a80, 0x108cca0, 0xc0003d60e0, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:587 +0x210
github.com/longhorn/longhorn-engine/app/cmd.startSyncAgent(0xc0001cef20, 0xe7723d, 0x0)
	/go/src/github.com/longhorn/longhorn-engine/app/cmd/sync_agent.go:89 +0x503
github.com/longhorn/longhorn-engine/app/cmd.SyncAgentCmd.func1(0xc0001cef20)
	/go/src/github.com/longhorn/longhorn-engine/app/cmd/sync_agent.go:40 +0x2f
github.com/urfave/cli.HandleAction(0xd158e0, 0xeb5de8, 0xc0001cef20[pvc-65504d53-8d4f-41e1-af34-6fece21ee633-r-0525f3f6] , 0xc0001cef20, 0x0)
	/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/app.go:525 +0x7c
github.com/urfave/cli.Command.Run(0xe7c42f, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe92b0b, ...)
	/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/command.go:174 +0x56e
github.com/urfave/cli.(*App).Run(0xc00024a1c0, 0xc0001b6000, 0x8, 0x8, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/app.go:276 +0x7ae
main.longhornCli()
```

**Comment by PhanLe1010** [comment]
@strahe Did you try https://github.com/longhorn/longhorn/issues/3178#issuecomment-998090624 ?
