### ISSUE TITLE
[BUG] Longhorn manager NPE due to the nil engine during the backup creation

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3484]
## Describe the bug

When the backup creation is started, the longhorn manager pod may encounter the NPE issue once the engine somehow is removed.

## To Reproduce

I am not sure if there is a straightforward way to reproduce this issue. The below steps are almost impossible for common users. 

1. Create and attach a volume.
2. Create a backup for the volume.
3. Detach the volume.
4. Create a backup via YAML and delete the engine simultaneously. It's better to operate the resources via a (golang/python/...) client rather than `kubectl` in the following steps.
5. Check if there are NPE logs in the longhorn manager pods

## Expected behavior

No NPE logs

## Log or Support bundle

```
[longhorn-manager-2k5rr] goroutine 743 [running]:
[longhorn-manager-2k5rr] k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
[longhorn-manager-2k5rr] 	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
[longhorn-manager-2k5rr] panic(0x1931a20, 0x2c92950)
[longhorn-manager-2k5rr] 	/usr/local/go/src/runtime/panic.go:967 +0x166
[longhorn-manager-2k5rr] github.com/longhorn/longhorn-manager/controller.(*BackupController).getEngineClient(0xc0003fdc00, 0xc0011d3840, 0x17, 0x0, 0x0, 0x0, 0x0)
[longhorn-manager-2k5rr] 	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:416 +0x7d
[longhorn-manager-2k5rr] github.com/longhorn/longhorn-manager/controller.(*BackupController).checkMonitor(0xc0003fdc00, 0xc000323b80, 0xc001948400, 0xc000fcf380, 0x0, 0x0, 0x0)
[longhorn-manager-2k5rr] 	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:469 +0x182
[longhorn-manager-2k5rr] github.com/longhorn/longhorn-manager/controller.(*BackupController).reconcile(0xc0003fdc00, 0xc000480700, 0x12, 0x0, 0x0)
[longhorn-manager-2k5rr] 	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:305 +0x1263
[longhorn-manager-2k5rr] github.com/longhorn/longhorn-manager/controller.(*BackupController).syncHandler(0xc0003fdc00, 0xc0004806f0, 0x22, 0x0, 0x0)
[longhorn-manager-2k5rr] 	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:170 +0x182
[longhorn-manager-2k5rr] github.com/longhorn/longhorn-manager/controller.(*BackupController).processNextWorkItem(0xc0003fdc00, 0x203000)
[longhorn-manager-2k5rr] 	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:136 +0xcc
[longhorn-manager-2k5rr] github.com/longhorn/longhorn-manager/controller.(*BackupController).worker(0xc0003fdc00)
[longhorn-manager-2k5rr] 	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:126 +0x2b
[longhorn-manager-2k5rr] k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000d6d280)
[longhorn-manager-2k5rr] 	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
[longhorn-manager-2k5rr] k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000d6d280, 0x1e6faa0, 0xc0005db500, 0xc00013a401, 0xc0003ae240)
[longhorn-manager-2k5rr] 	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
[longhorn-manager-2k5rr] k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000d6d280, 0x3b9aca00, 0x0, 0x100000000000001, 0xc0003ae240)
[longhorn-manager-2k5rr] 	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
[longhorn-manager-2k5rr] k8s.io/apimachinery/pkg/util/wait.Until(0xc000d6d280, 0x3b9aca00, 0xc0003ae240)
[longhorn-manager-2k5rr] 	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
[longhorn-manager-2k5rr] created by github.com/longhorn/longhorn-manager/controller.(*BackupController).Run
[longhorn-manager-2k5rr] 	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:120 +0x1c9
```

## Environment

 - Longhorn version: v1.2.3

## Additional context
- This issue is reported by [this comment](https://github.com/longhorn/longhorn/issues/3466#issuecomment-1001488807)
- The cause of this issue is that the engine [here](https://github.com/longhorn/longhorn-manager/blob/master/controller/backup_controller.go#L414) may be a nil variable.

**Comment by kaxing** [comment]
Validation - **PASSED**

master-head is able to pass the crash-test script mentioned in the new doc.

```
root@longhorn-test:/integration/tests# bash run.sh test_npe.py
+ flake8
+ pytest -v test_npe.py
========================================================================================= test session starts =========================================================================================
platform linux -- Python 3.9.9, pytest-5.3.1, py-1.11.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /integration, inifile: pytest.ini
plugins: repeat-0.9.1
collected 2 items

test_npe.py::test_backup_npe[s3] PASSED                                                                                                                                                         [ 50%]
test_npe.py::test_backup_npe[nfs] PASSED                                                                                                                                                        [100%]

==================================================================================== 2 passed in 341.20s (0:05:41) ====================================================================================
root@longhorn-test:/integration/tests#
```

Node spec.:
- 1 + 3 local k3s v1.21.

**Comment by kaxing** [comment]
Validation - **PASSED**

master-head is able to pass the crash-test script mentioned in the new doc.

```
root@longhorn-test:/integration/tests# bash run.sh test_npe.py
+ flake8
+ pytest -v test_npe.py
========================================================================================= test session starts =========================================================================================
platform linux -- Python 3.9.9, pytest-5.3.1, py-1.11.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /integration, inifile: pytest.ini
plugins: repeat-0.9.1
collected 2 items

test_npe.py::test_backup_npe[s3] PASSED                                                                                                                                                         [ 50%]
test_npe.py::test_backup_npe[nfs] PASSED                                                                                                                                                        [100%]

==================================================================================== 2 passed in 341.20s (0:05:41) ====================================================================================
root@longhorn-test:/integration/tests#
```

Test spec.:
- 1 + 3 local VMs cluster with k3s v1.22.5+k3s1
- fresh install of longhorn master-head via manifests under longhorn-manger repo

Additional note: 
The failure can be reproduced with Longhorn v1.2.3 on k3s v1.18
