### ISSUE TITLE
[QUESTION] Spring Boot service discovery fails due to headless service introduced in Longhorn 1.2.3

### ISSUE THREAD

**Issue by jeroenhartgers** [longhorn/longhorn#3589]
## Describe the bug

After upgrading from Longhorn 1.2.2 to 1.2.3, a Spring Boot application that uses Kubernetes Service Discovery, the application starts misbehaving after a redeploy. This application behavior is consistent on at least three different k8s clusters. After downgrading Longhorn to 1.2.2, the redeployed application immediately starts behaving correctly again.

Current cluster role rules (yes, they should be condensed):
```
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get","watch","list"]
```

## To Reproduce

1. Go to Rancher App Store -> Apps & Market Place -> Installed Apps
2. Click on Longhorn -> Edit/Upgrade -> Upgrade to version "100.1.1+up1.2.3"
3. Redeploy the Spring Boot v2.4.6 application
4. See errors:
`2022-02-02 15:17:53.064 ERROR [gateway,,] 1 --- [oundedElastic-6] reactor.core.publisher.Operators : Operator called default onErrorDropped
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get] for kind: [Service] with name: [longhorn-engine-manager] in namespace: [longhorn-system] failed.
at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:225)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:186)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:84)
at org.springframework.cloud.kubernetes.fabric8.discovery.KubernetesDiscoveryClient.getNamespaceServiceInstances(KubernetesDiscoveryClient.java:139)
at org.springframework.cloud.kubernetes.fabric8.discovery.KubernetesDiscoveryClient.getInstances(KubernetesDiscoveryClient.java:119)
at org.springframework.cloud.kubernetes.fabric8.discovery.reactive.KubernetesReactiveDiscoveryClient.lambda$getInstances$0(KubernetesReactiveDiscoveryClient.java:54)
at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)
at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:193)
at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.InterruptedIOException: null
at okhttp3.internal.http2.Http2Stream.waitForIo(Http2Stream.java:663)
at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:151)
at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at io.fabric8.kubernetes.client.utils.OIDCTokenRefreshInterceptor.intercept(OIDCTokenRefreshInterceptor.java:41)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:151)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
at okhttp3.RealCall.execute(RealCall.java:81)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:472)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:402)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:384)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:935)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:220)
... 14 common frames omitted
`

## Expected behavior

That the Spring Boot application continues working

## Log or Support bundle

Empty

## Environment

 - Longhorn version: 1.2.3 release
 - Installation method: Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.3.3 with k8s v1.21.7 
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: RHEL 8.5 kernel 4.18.0-305.19.1.el8_4.x86_64
   - CPU per node:
   - Memory per node: 64 GB
   - Disk type(e.g. SSD/NVMe): NAS storage with SCSI 
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 8

## Additional context

**When manually deleting the 2 new HEADLESS services as in the yaml for 1.2.3, my application works perfectly again !!!**
Assumption: _It looks like Spring Boot does NOT fancy headless services very much, as it does not find an IP during DNS lookup._

The two new services:

```apiVersion: v1
kind: Service
metadata:
  name: longhorn-engine-manager
  namespace: longhorn-system
spec:
  clusterIP: None
  selector:
    longhorn.io/component: instance-manager
    longhorn.io/instance-manager-type: engine
```
```apiVersion: v1
kind: Service
metadata:
  name: longhorn-replica-manager
  namespace: longhorn-system
spec:
  clusterIP: None
  selector:
    longhorn.io/component: instance-manager
    longhorn.io/instance-manager-type: replica
```

**Comment by joshimoo** [comment]
@jeroenhartgers this seems to be an application problem during the service discovery independent from Longhorn.
- can you share the spring boot version
- relevant dependencies versions for service discovery
- any reason you are doing service discovery in the "longhorn-system" namespace, i.e. are you running an operator inside of that namespace?

**Comment by innobead** [comment]
It seems it works after you removed our deployed headless services, and it means Sprint boot/cloud service discovery does not support headless services and it seems reasonable because headless services are actually unable to discover.

Like @joshimoo said, this is not related to Longhorn but instead how the discovery client works and I would suggest checking Spring configurations to exclude headless services to discover or even skip the longhorn namespace.

**Comment by jeroenhartgers** [comment]
Thank @joshimoo and @innobead for your support. I have continued investigation and I wholeheartedly agree that headless services are not an option for Spring Boot service discovery. As @innobead claims, they are undiscoverable "The definition of a headless service is to not provide a DNS record and (to) provide internal load balancing" 

I have asked the developers of my team to come up with a solution to (preferred) exclude headless discovery or (less preferred) avoid the longhorn-system namespace. 

I will make sure to post a result within the next week, as I am waiting for approval for devs to start the investigation.

**Comment by jeroenhartgers** [comment]
Issue is being fixed by my colleagues developers.
