### ISSUE TITLE
[Backport v1.1.4] Scalability issue in Longhorn

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3610]
https://github.com/longhorn/longhorn/issues/3083

**Comment by kaxing** [comment]
Validation in progress,

Tested with v1.1.x-head (pre v1.1.4) on 3 + 10 rke2 cluster:
- non_io: will able remain stable at 600 (pods, volumes):
  - ![v11x-non_io-630](https://user-images.githubusercontent.com/602540/160133437-712c3b9b-5e44-4317-9836-d0687557247a.png)

- io_1: can only monitor up to 65 volumes(due to the test script having some problem):
  - ![v11x-io1-46](https://user-images.githubusercontent.com/602540/160133428-480bc9a0-65f6-4b6c-9f0b-1d0df311fa18.png)

A snapshot of cpu/mem usage of the worker nodes and longhorn manager pods (for io1 with 65 volumes):
```
NAME            CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
ip-10-0-0-119   1945m        97%    2753Mi          35%
ip-10-0-0-128   1941m        97%    3177Mi          40%
ip-10-0-0-130   1954m        97%    3770Mi          48%
ip-10-0-0-134   1947m        97%    3366Mi          42%
ip-10-0-0-160   1945m        97%    4046Mi          51%
ip-10-0-0-184   1945m        97%    3604Mi          45%
ip-10-0-0-213   243m         12%    2232Mi          28%
ip-10-0-0-239   191m         9%     2054Mi          26%
ip-10-0-0-247   254m         12%    2142Mi          27%
ip-10-0-0-34    1956m        97%    4110Mi          52%
ip-10-0-0-49    1933m        96%    4418Mi          56%
ip-10-0-0-67    1937m        96%    3507Mi          44%
ip-10-0-0-84    1948m        97%    3471Mi          44%

NAME                     CPU(cores)   MEMORY(bytes)
longhorn-manager-2ltdx   45m          125Mi
longhorn-manager-7hpkn   26m          282Mi
longhorn-manager-7rbrw   38m          110Mi
longhorn-manager-cf8l9   51m          113Mi
longhorn-manager-mw55p   25m          116Mi
longhorn-manager-qvh9d   70m          110Mi
longhorn-manager-qvqd5   58m          117Mi
longhorn-manager-rfv87   27m          121Mi
longhorn-manager-wspxg   37m          118Mi
longhorn-manager-xck5h   82m          121Mi
```

---

Can still resume the monitor cc @PhanLe1010
```
longhorn-tests/scalability_test/script$ ./scale-test.py
Choose an operation (scale, monitor, all, dry_draw): monitor
preload (yes)? yes
running monitoring loop ...
Exception when calling custom_objects_api->list_cluster_custom_object: (503)
Reason: Service Unavailable
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'f1693da1-8c73-43b5-a247-31ba19363278', 'X-Kubernetes-Pf-Prioritylevel-Uid': '09b6c862-4463-4a74-bda1-ae01ff0c989f', 'Date': 'Fri, 25 Mar 2022 13:48:54 GMT', 'Content-Length': '20'})
HTTP response body: service unavailable



Will set node metrics to 0
Traceback (most recent call last):
  File "/Users/user/Workspaces/Longhorn/Issues/3083-the-scalibity-issue/longhorn-tests/scalability_test/script/./scale-test.py", line 252, in <module>
    m.run()
  File "/Users/user/Workspaces/Longhorn/Issues/3083-the-scalibity-issue/longhorn-tests/scalability_test/script/monitor.py", line 218, in run
    self.update_data()
  File "/Users/user/Workspaces/Longhorn/Issues/3083-the-scalibity-issue/longhorn-tests/scalability_test/script/monitor.py", line 87, in update_data
    for node in node_list['items']:
TypeError: list indices must be integers or slices, not str
```

**Comment by PhanLe1010** [comment]
@kaxing 

It seems that the test script is hitting an expectation while listing the node for CPU and mem calculation. 

Can you resume by running monitoring without preload?

**Comment by PhanLe1010** [comment]
I saw that we can push up to 800 volumes with the same cluster config in Longhorn v1.2.x. We can only push to 600 in v1.1.x?

**Comment by kaxing** [comment]
@PhanLe1010 v1.1.x-head can hold 800 volumes, but it requires closer to 1.4 hour to build all the volumes:
![v11x-non_io-800](https://user-images.githubusercontent.com/602540/160355475-d07163ac-f757-4191-b179-2e6eaf867bcc.png) which on v1.2.4 is about an hour with the same parameters.

And for monitoring after crash, yes, I can either resume or start a new monitoring session without problem.
