### ISSUE TITLE
[BUG] Longhorn Manager can't start after deleting volumes/stuck

### ISSUE THREAD

**Issue by timmy59100** [longhorn/longhorn#3634]
## Describe the bug

After deleting a few volumes, which are now stuck in deleting, 3 out of 5 longhorn managers are in a restart loop.

## Log or Support bundle

[longhorn-support-bundle_55903fa6-26ed-4355-a4bf-17d3650572cc_2022-02-17T11-24-39Z.zip](https://github.com/longhorn/longhorn/files/8088217/longhorn-support-bundle_55903fa6-26ed-4355-a4bf-17d3650572cc_2022-02-17T11-24-39Z.zip)

`ime="2022-02-17T11:14:50Z" level=debug msg="Can't find share manager, may have been deleted" controller=longhorn-share-manager node=pax-p-96 shareManager=pvc-78321e92-5090-424b-b939-2d8fe51710f5

time="2022-02-17T11:14:50Z" level=warning msg="Error syncing Longhorn backup longhorn-system/backup-272a790321bc48d6" controller=longhorn-backup error="longhorn-backup: fail to sync backup longhorn-system/backup-272a790321bc48d6: cannot get client for engine pvc-b377393f-f5f4-4b99-aac1-2d92009f1d35-e-08080876: engine is not running" node=pax-p-96

time="2022-02-17T11:14:50Z" level=debug msg="Start monitoring instance manager instance-manager-r-9c410d90" controller=longhorn-instance-manager instance manager=instance-manager-r-9c410d90 node=pax-p-96

time="2022-02-17T11:14:50Z" level=warning msg="Error syncing Longhorn backup longhorn-system/backup-bdfd1847958b4fca" controller=longhorn-backup error="longhorn-backup: fail to sync backup longhorn-system/backup-bdfd1847958b4fca: cannot get client for engine pvc-b377393f-f5f4-4b99-aac1-2d92009f1d35-e-08080876: engine is not running" node=pax-p-96

E0217 11:14:50.203577       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

goroutine 1297 [running]:

k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1931a20, 0x2c92950)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3

k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82

panic(0x1931a20, 0x2c92950)

	/usr/local/go/src/runtime/panic.go:967 +0x166

github.com/longhorn/longhorn-manager/controller.(*BackupController).getEngineClient(0xc000845780, 0xc0015139e0, 0x28, 0x0, 0x0, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:416 +0x7d

github.com/longhorn/longhorn-manager/controller.(*BackupController).checkMonitor(0xc000845780, 0xc005541180, 0xc005492800, 0xc0000acb60, 0x0, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:469 +0x182

github.com/longhorn/longhorn-manager/controller.(*BackupController).reconcile(0xc000845780, 0xc003225810, 0x17, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:305 +0x1263

github.com/longhorn/longhorn-manager/controller.(*BackupController).syncHandler(0xc000845780, 0xc003225800, 0x27, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:170 +0x182

github.com/longhorn/longhorn-manager/controller.(*BackupController).processNextWorkItem(0xc000845780, 0x203000)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:136 +0xcc

github.com/longhorn/longhorn-manager/controller.(*BackupController).worker(0xc000845780)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:126 +0x2b

k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0017a6db0)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f

k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0017a6db0, 0x1e6faa0, 0xc0007a1320, 0x1, 0xc0003a4000)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3

k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0017a6db0, 0x3b9aca00, 0x0, 0x6207594d00000001, 0xc0003a4000)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98

k8s.io/apimachinery/pkg/util/wait.Until(0xc0017a6db0, 0x3b9aca00, 0xc0003a4000)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d

created by github.com/longhorn/longhorn-manager/controller.(*BackupController).Run

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:120 +0x1c9

panic: runtime error: invalid memory address or nil pointer dereference [recovered]

	panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x1f0 pc=0x161662d]

goroutine 1297 [running]:

k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105

panic(0x1931a20, 0x2c92950)

	/usr/local/go/src/runtime/panic.go:967 +0x166

github.com/longhorn/longhorn-manager/controller.(*BackupController).getEngineClient(0xc000845780, 0xc0015139e0, 0x28, 0x0, 0x0, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:416 +0x7d

github.com/longhorn/longhorn-manager/controller.(*BackupController).checkMonitor(0xc000845780, 0xc005541180, 0xc005492800, 0xc0000acb60, 0x0, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:469 +0x182

github.com/longhorn/longhorn-manager/controller.(*BackupController).reconcile(0xc000845780, 0xc003225810, 0x17, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:305 +0x1263

github.com/longhorn/longhorn-manager/controller.(*BackupController).syncHandler(0xc000845780, 0xc003225800, 0x27, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:170 +0x182

github.com/longhorn/longhorn-manager/controller.(*BackupController).processNextWorkItem(0xc000845780, 0x203000)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:136 +0xcc

github.com/longhorn/longhorn-manager/controller.(*BackupController).worker(0xc000845780)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:126 +0x2b

k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0017a6db0)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f

k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0017a6db0, 0x1e6faa0, 0xc0007a1320, 0x1, 0xc0003a4000)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3

k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0017a6db0, 0x3b9aca00, 0x0, 0x6207594d00000001, 0xc0003a4000)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98

k8s.io/apimachinery/pkg/util/wait.Until(0xc0017a6db0, 0x3b9aca00, 0xc0003a4000)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d

created by github.com/longhorn/longhorn-manager/controller.(*BackupController).Run

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:120 +0x1c9`

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.23
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 8
   - Memory per node: 32GB
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster: ~50 active

## Additional context

![grafik](https://user-images.githubusercontent.com/7300669/154471991-ce0e7534-df07-4058-8a4a-4e5e739acea8.png)

**Comment by timmy59100** [comment]
Update: After ~5 hours the managers recovered and the volumes got deleted.

**Comment by shuo-wu** [comment]
Thank you for reporting. This issue is a duplication of https://github.com/longhorn/longhorn/issues/3484. And it's already fixed.
