### ISSUE TITLE
[BUG] longhorn-csi-plugin segmentation violation  [arm64]

### ISSUE THREAD

**Issue by deB4SH** [longhorn/longhorn#4020]
## Describe the bug

Wanted to add a rpi4 64bit (raspian) to my existing x86 cluster.
Everything starts accordingly but longhorn-csi-plugin errors with

```
unexpected fault address 0x8d4f70
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8d4f70 pc=0x81ab4]

goroutine 1 [running, locked to thread]:
runtime.throw(0x64a7c4, 0x5)
	/usr/local/go/src/runtime/panic.go:1117 +0x54 fp=0x4000104810 sp=0x40001047e0 pc=0x435b4
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:741 +0x230 fp=0x4000104850 sp=0x4000104810 pc=0x5a0d0
internal/oserror.init()
	/usr/local/go/src/internal/oserror/errors.go:15 +0x104 fp=0x4000104890 sp=0x4000104860 pc=0x81ab4
runtime.doInit(0xa72800)
	/usr/local/go/src/runtime/proc.go:6265 +0xdc fp=0x40001049f0 sp=0x4000104890 pc=0x538cc
runtime.doInit(0xa75880)
	/usr/local/go/src/runtime/proc.go:6242 +0x60 fp=0x4000104b50 sp=0x40001049f0 pc=0x53850
runtime.doInit(0xa74b00)
	/usr/local/go/src/runtime/proc.go:6242 +0x60 fp=0x4000104cb0 sp=0x4000104b50 pc=0x53850
runtime.doInit(0xa74d40)
	/usr/local/go/src/runtime/proc.go:6242 +0x60 fp=0x4000104e10 sp=0x4000104cb0 pc=0x53850
runtime.doInit(0xa7a1c0)
	/usr/local/go/src/runtime/proc.go:6242 +0x60 fp=0x4000104f70 sp=0x4000104e10 pc=0x53850
runtime.main()
	/usr/local/go/src/runtime/proc.go:208 +0x214 fp=0x4000104fd0 sp=0x4000104f70 pc=0x45aa4
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1130 +0x4 fp=0x4000104fd0 sp=0x4000104fd0 pc=0x76e44
```

## To Reproduce

1. Add RPI4 with 64bit raspian to cluster
2. Wait for deployments
3. See error

## Expected behavior

Starting longhorn-csi-plugin container.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3S
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: raspbian 64bit latest
   - CPU per node: 4
   - Memory per node: 8gb
   - Disk type(e.g. SSD/NVMe): ssd
   - Network bandwidth between the nodes: 1Gbit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: <100

## Additional context

<nothing>

**Comment by PhanLe1010** [comment]
cc @keithalucas Do you have any idea?

@deB4SH So is it only happened with the [Raspberry Pi OS](https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/)? What is the OS of other nodes in the cluster?

**Comment by keithalucas** [comment]
I think the segfault is occurring because of [this](https://github.com/golang/go/blob/9baddd3f21230c55f0ad2a10f5f20579dcf0a0bb/src/runtime/proc.go#L6265) which looks like it's trying to treat a value linked into the program as a function pointer and call it.  I'll try to look into it more.

**Comment by keithalucas** [comment]
@deB4SH There are two containers in the longhorn-csi-plugin pods:  longhorn-csi-plugin and csi-node-driver-registrar.  I want to see which one the segfault is occuring in.

**Comment by deB4SH** [comment]
Hi all,
thanks for picking this up so quickly.

@PhanLe1010 : this only happens on my raspberry pi os 64bit. all other x86 nodes in my cluster are working fine. 

@keithalucas the issue occures withing the container "node-driver-registrar"

the longhorn-csi-plugin looks fine for me
```
2022/05/24 08:53:17 proto: duplicate proto type registered: VersionResponse
time="2022-05-24T08:53:17Z" level=info msg="CSI Driver: driver.longhorn.io version: v1.2.4, manager URL http://longhorn-backend:9500/v1"
time="2022-05-24T08:53:17Z" level=info msg="Enabling node service capability: GET_VOLUME_STATS"
time="2022-05-24T08:53:17Z" level=info msg="Enabling node service capability: STAGE_UNSTAGE_VOLUME"
time="2022-05-24T08:53:17Z" level=info msg="Enabling controller service capability: CREATE_DELETE_VOLUME"
time="2022-05-24T08:53:17Z" level=info msg="Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME"
time="2022-05-24T08:53:17Z" level=info msg="Enabling controller service capability: EXPAND_VOLUME"
time="2022-05-24T08:53:17Z" level=info msg="Enabling controller service capability: CREATE_DELETE_SNAPSHOT"
time="2022-05-24T08:53:17Z" level=info msg="Enabling controller service capability: CLONE_VOLUME"
time="2022-05-24T08:53:17Z" level=info msg="Enabling volume access mode: SINGLE_NODE_WRITER"
time="2022-05-24T08:53:17Z" level=info msg="Enabling volume access mode: MULTI_NODE_MULTI_WRITER"
time="2022-05-24T08:53:17Z" level=info msg="Listening for connections on address: &net.UnixAddr{Name:\"//csi/csi.sock\", Net:\"unix\"}"
```

**Comment by keithalucas** [comment]
@deB4SH The node-driver-registrar container is a copy of k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0 which is part of kubernetes.  The error looks there is a problem with the executable in that container running on the raspberry pi.  I couldn't find any indication of a problem in running csi-node-driver-registrar on raspberry pis in that project's github.  I don't know if running something like `docker run k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0 --help` versus `docker run k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0 --help` would work with the raspberry pi.

**Comment by deB4SH** [comment]
@keithalucas 

sadly - seems to work with both images

```
$ docker run k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0 --help
Unable to find image 'k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0' locally
v2.3.0: Pulling from sig-storage/csi-node-driver-registrar
5f8c69dfd0d4: Pull complete 
831c59e1c309: Pull complete 
Digest: sha256:f9bcee63734b7b01555ee8fc8fb01ac2922478b2c8934bf8d468dd2916edc405
Status: Downloaded newer image for k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
Usage of /csi-node-driver-registrar:
  -add_dir_header
        If true, adds the file directory to the header of the log messages
  -alsologtostderr
        log to standard error as well as files
  -connection-timeout duration
        The --connection-timeout flag is deprecated
  -csi-address string
        Path of the CSI driver socket that the node-driver-registrar will connect to. (default "/run/csi/socket")
  -health-port --health-port
        (deprecated) TCP port for healthz requests. Set to 0 to disable the healthz server. Only one of --health-port and `--http-endpoint` can be set.
  -http-endpoint :8080
        The TCP network address where the HTTP server for diagnostics, including the health check indicating whether the registration socket exists, will listen (example: :8080). The default is empty string, which means the server is disabled. Only one of `--health-port` and `--http-endpoint` can be set.
  -kubelet-registration-path string
        Path of the CSI driver socket on the Kubernetes host machine.
  -log_backtrace_at value
        when logging hits line file:N, emit a stack trace
  -log_dir string
        If non-empty, write log files in this directory
  -log_file string
        If non-empty, use this log file
  -log_file_max_size uint
        Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
  -logtostderr
        log to standard error instead of files (default true)
  -mode string
        The running mode of node-driver-registrar. "registration" runs node-driver-registrar as a long running process. "kubelet-registration-probe" runs as a health check and returns a status code of 0 if the driver was registered successfully, in the probe definition make sure that the value of --kubelet-registration-path is the same as in the container. (default "registration")
  -one_output
        If true, only write logs to their native severity level (vs also writing to each lower severity level)
  -plugin-registration-path string
        Path to Kubernetes plugin registration directory. (default "/registration")
  -skip_headers
        If true, avoid header prefixes in the log messages
  -skip_log_headers
        If true, avoid headers when opening log files
  -stderrthreshold value
        logs at or above this threshold go to stderr (default 2)
  -timeout duration
        Timeout for waiting for communication with driver (default 1s)
  -v value
        number for the log level verbosity
  -version
        Show version.
  -vmodule value
        comma-separated list of pattern=N settings for file-filtered logging
```

```
docker run longhornio/csi-node-driver-registrar:v2.3.0 --help
Unable to find image 'longhornio/csi-node-driver-registrar:v2.3.0' locally
v2.3.0: Pulling from longhornio/csi-node-driver-registrar
Digest: sha256:10fe9cd400fd409f43e89f3287446db7b946f5a30b9ceafcd2ef1936b8208a2f
Status: Downloaded newer image for longhornio/csi-node-driver-registrar:v2.3.0
Usage of /csi-node-driver-registrar:
  -add_dir_header
        If true, adds the file directory to the header of the log messages
  -alsologtostderr
        log to standard error as well as files
  -connection-timeout duration
        The --connection-timeout flag is deprecated
  -csi-address string
        Path of the CSI driver socket that the node-driver-registrar will connect to. (default "/run/csi/socket")
  -health-port --health-port
        (deprecated) TCP port for healthz requests. Set to 0 to disable the healthz server. Only one of --health-port and `--http-endpoint` can be set.
  -http-endpoint :8080
        The TCP network address where the HTTP server for diagnostics, including the health check indicating whether the registration socket exists, will listen (example: :8080). The default is empty string, which means the server is disabled. Only one of `--health-port` and `--http-endpoint` can be set.
  -kubelet-registration-path string
        Path of the CSI driver socket on the Kubernetes host machine.
  -log_backtrace_at value
        when logging hits line file:N, emit a stack trace
  -log_dir string
        If non-empty, write log files in this directory
  -log_file string
        If non-empty, use this log file
  -log_file_max_size uint
        Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
  -logtostderr
        log to standard error instead of files (default true)
  -mode string
        The running mode of node-driver-registrar. "registration" runs node-driver-registrar as a long running process. "kubelet-registration-probe" runs as a health check and returns a status code of 0 if the driver was registered successfully, in the probe definition make sure that the value of --kubelet-registration-path is the same as in the container. (default "registration")
  -one_output
        If true, only write logs to their native severity level (vs also writing to each lower severity level)
  -plugin-registration-path string
        Path to Kubernetes plugin registration directory. (default "/registration")
  -skip_headers
        If true, avoid header prefixes in the log messages
  -skip_log_headers
        If true, avoid headers when opening log files
  -stderrthreshold value
        logs at or above this threshold go to stderr (default 2)
  -timeout duration
        Timeout for waiting for communication with driver (default 1s)
  -v value
        number for the log level verbosity
  -version
        Show version.
  -vmodule value
        comma-separated list of pattern=N settings for file-filtered logging
```

**Comment by PhanLe1010** [comment]
@deB4SH 
What is the Kubernetes version?

Can you try with the newer `k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0` image by following the below steps:
1. If you are installing Longhorn using Helm, try to set it [here](https://github.com/longhorn/longhorn/blob/59f3c3b647d162dce483586faaec105ea50a9add/chart/values.yaml#L35-L37)
2. If you are using kubectl apply. Try to set it [here](https://github.com/longhorn/longhorn/blob/59f3c3b647d162dce483586faaec105ea50a9add/deploy/longhorn.yaml#L3566)

**Comment by deB4SH** [comment]
Hi @PhanLe1010 
this seems to resolve the issue.


logs: node-driver-registrar
```
> k logs longhorn-csi-plugin-9ksf6 -c node-driver-registrar
I0526 08:57:05.799525 1777751 main.go:166] Version: v2.5.0
I0526 08:57:05.799743 1777751 main.go:167] Running node-driver-registrar in mode=registration
I0526 08:57:05.801778 1777751 main.go:191] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0526 08:57:06.805052 1777751 main.go:198] Calling CSI driver to discover driver name
I0526 08:57:06.815234 1777751 main.go:208] CSI driver name: "driver.longhorn.io"
I0526 08:57:06.815581 1777751 node_register.go:53] Starting Registration Server at: /registration/driver.longhorn.io-reg.sock
I0526 08:57:06.816250 1777751 node_register.go:62] Registration Server started at: /registration/driver.longhorn.io-reg.sock
I0526 08:57:06.816756 1777751 node_register.go:92] Skipping HTTP server because endpoint is set to: ""
I0526 08:57:07.584339 1777751 main.go:102] Received GetInfo call: &InfoRequest{}
I0526 08:57:07.585286 1777751 main.go:109] "Kubelet registration probe created" path="/var/lib/kubelet/plugins/driver.longhorn.io/registration"
I0526 08:57:07.885963 1777751 main.go:120] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
```

logs: longhorn-csi-plugin
```
> k logs longhorn-csi-plugin-9ksf6 -c longhorn-csi-plugin  
2022/05/26 08:57:06 proto: duplicate proto type registered: VersionResponse
time="2022-05-26T08:57:06Z" level=info msg="CSI Driver: driver.longhorn.io version: v1.2.4, manager URL http://longhorn-backend:9500/v1"
time="2022-05-26T08:57:06Z" level=info msg="Enabling node service capability: GET_VOLUME_STATS"
time="2022-05-26T08:57:06Z" level=info msg="Enabling node service capability: STAGE_UNSTAGE_VOLUME"
time="2022-05-26T08:57:06Z" level=info msg="Enabling controller service capability: CREATE_DELETE_VOLUME"
time="2022-05-26T08:57:06Z" level=info msg="Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME"
time="2022-05-26T08:57:06Z" level=info msg="Enabling controller service capability: EXPAND_VOLUME"
time="2022-05-26T08:57:06Z" level=info msg="Enabling controller service capability: CREATE_DELETE_SNAPSHOT"
time="2022-05-26T08:57:06Z" level=info msg="Enabling controller service capability: CLONE_VOLUME"
time="2022-05-26T08:57:06Z" level=info msg="Enabling volume access mode: SINGLE_NODE_WRITER"
time="2022-05-26T08:57:06Z" level=info msg="Enabling volume access mode: MULTI_NODE_MULTI_WRITER"
time="2022-05-26T08:57:06Z" level=info msg="Listening for connections on address: &net.UnixAddr{Name:\"//csi/csi.sock\", Net:\"unix\"}"
time="2022-05-26T08:57:06Z" level=info msg="GetPluginInfo: req: {}"
time="2022-05-26T08:57:06Z" level=info msg="GetPluginInfo: rsp: {\"name\":\"driver.longhorn.io\",\"vendor_version\":\"v1.2.4\"}"
time="2022-05-26T08:57:07Z" level=info msg="NodeGetInfo: req: {}"
time="2022-05-26T08:57:07Z" level=info msg="NodeGetInfo: rsp: {\"node_id\":\"ciel\"}"
time="2022-05-26T08:57:44Z" level=info msg="NodeStageVolume: req: {\"staging_target_path\":\"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ec9a93d1-9c9c-4d3c-9df4-012e698caf4e/globalmount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":5}},\"volume_context\":{\"fromBackup\":\"\",\"fsType\":\"ext4\",\"numberOfReplicas\":\"2\",\"share\":\"true\",\"staleReplicaTimeout\":\"2880\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1647161011386-8081-driver.longhorn.io\"},\"volume_id\":\"pvc-ec9a93d1-9c9c-4d3c-9df4-012e698caf4e\"}"
time="2022-05-26T08:57:44Z" level=debug msg="trying to ensure mount point /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ec9a93d1-9c9c-4d3c-9df4-012e698caf4e/globalmount"
time="2022-05-26T08:57:44Z" level=debug msg="mount point /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ec9a93d1-9c9c-4d3c-9df4-012e698caf4e/globalmount try reading dir to make sure it's healthy"
time="2022-05-26T08:57:44Z" level=info msg="mounted shared volume pvc-ec9a93d1-9c9c-4d3c-9df4-012e698caf4e on node ciel via share endpoint nfs://10.43.129.123/pvc-ec9a93d1-9c9c-4d3c-9df4-012e698caf4e"
time="2022-05-26T08:57:44Z" level=info msg="NodeStageVolume: rsp: {}"

[... and so on ...]

```

Thanks for the help @PhanLe1010 @keithalucas 

I'm installing via kustomize and kubectl directly from here: https://github.com/longhorn/longhorn/blob/v1.2.4/deploy/longhorn.yaml

Maybe 1.2.5 with an upgraded image? Or is it upgraded in 1.3 anyway?

Thanks again!

**Comment by PhanLe1010** [comment]
> Maybe 1.2.5 with an upgraded image? Or is it upgraded in 1.3 anyway?

It is upgraded in 1.3

**Comment by deB4SH** [comment]
That's fine for me tbh. :)
Closing this issue - it is resolved with upgrading the image. 

Thanks a lot!
