### ISSUE TITLE
[BUG] updateSettingDefinitions throws concurrent map write

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4021]
## Describe the bug

While running e2e `test_basic.py::test_restore_basic` for https://github.com/longhorn/longhorn-manager/pull/1338, found this panic occasionally happens, but I've not verified it on the master branch.

https://github.com/longhorn/longhorn-manager/blob/master/datastore/longhorn.go#L113

## To Reproduce

1. Run e2e `test_basic.py::test_restore_basic` couple of times.

## Expected behavior

No panic

## Log or Support bundle

```
concurrent map writes

goroutine 1 [running]:
runtime.throw({0x1ff69cf, 0x14f5125})
        /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc0012307d0 sp=0xc0012307a0 pc=0x435811
runtime.mapassign_faststr(0x1cc4400, 0x2018819, {0x2018819, 0x26})
        /usr/local/go/src/runtime/map_faststr.go:211 +0x39c fp=0xc001230838 sp=0xc0012307d0 pc=0x41305c
github.com/longhorn/longhorn-manager/datastore.(*DataStore).updateSettingDefinitions(0x0, 0xc00005202e, 0xc0002d0dc0)
        /go/src/github.com/longhorn/longhorn-manager/datastore/longhorn.go:113 +0x2f1 fp=0xc0012309f0 sp=0xc001230838 pc=0x15d0c31
github.com/longhorn/longhorn-manager/datastore.(*DataStore).UpdateCustomizedSettings(0xc0004e8d80, 0xc001230c30)
        /go/src/github.com/longhorn/longhorn-manager/datastore/longhorn.go:56 +0x66 fp=0xc001230a38 sp=0xc0012309f0 pc=0x15d0686

```

## Environment

`N/A`

## Additional context

`None`

**Comment by innobead** [comment]
Thanks @c3y1huang !

This part should be protected because datastore needs thread safe.

**Comment by kaxing** [comment]
Validation - **PASSED**

The error can be reproduced with longhorn-manager image built on commit 9fb0cda2: `longhornio/longhorn-manager:master-head-amd64@sha256:2fb01d7de50af86f5b74b45b2f9cd4cfce73a56a965b31e53b5fb116af7b7dbf` 

With the latest master-head image: `longhornio/longhorn-manager:master-head-amd64@sha256:35dbecda9f3c052831a10265c218e9ab12136821c4fbf742322198810c1afb58`
(commit: fb4e45e7), longhorn-manager pods will no longer have identical errors and restart itself.
