### ISSUE TITLE
[BUG] longhorn-manager pods backoff: snapshot controller failed to get volume

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#4056]
## Describe the bug

This is found during [the scalability test](https://github.com/longhorn/longhorn-tests/tree/master/scalability_test) with io_1 test set to 80 replicas on 3+20 cluster

## To Reproduce

1. Launch cluster with 3 control nodes and 20 worker nodes
3. Run scale-test.py
4. Wati and observe

## Expected behavior

Should be no crash/backoff errors

## Log or Support bundle

```
time="2022-05-31T12:27:48Z" level=debug msg="Found storage-network setting is empty, use instance-manager-r-b884eca3 pod IP 10.42.9.13"
E0531 12:27:48.914570       1 snapshot_controller.go:112] snapshot controller failed to get volume pvc-2c538612-f6eb-4815-9ffa-5bfe30c9c9b5 when enqueuing engine pvc-2c538612-f6eb-4815-9ffa-5bfe30c9c9b5-e-d0ec103f: volume.longhorn.io "pvc-2c538612-f6eb-4815-9ffa-5bfe30c9c9b5" not found
E0531 12:27:48.914651       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 309 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1cef3e0, 0x344d060})
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe})
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1cef3e0, 0x344d060})
    /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/longhorn/longhorn-manager/controller.(*SnapshotController).enqueueEngineChange(0xc000153000, {0x1f93e80, 0xc009962300}, {0x1f93e80, 0xc009547800})
    /go/src/github.com/longhorn/longhorn-manager/controller/snapshot_controller.go:115 +0x1c2
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:238
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:785 +0x127
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f8a993a2438)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00072c738, {0x2299ea0, 0xc000289710}, 0x1, 0xc0005b2c00)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000153100)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:781 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x88
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x258 pc=0x18f3d22]

goroutine 309 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe})
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x1cef3e0, 0x344d060})
    /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/longhorn/longhorn-manager/controller.(*SnapshotController).enqueueEngineChange(0xc000153000, {0x1f93e80, 0xc009962300}, {0x1f93e80, 0xc009547800})
    /go/src/github.com/longhorn/longhorn-manager/controller/snapshot_controller.go:115 +0x1c2
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:238
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:785 +0x127
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f8a993a2438)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00072c738, {0x2299ea0, 0xc000289710}, 0x1, 0xc0005b2c00)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000153100)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:781 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x88
Stream closed EOF for longhorn-system/longhorn-manager-g448b (longhorn-manager)
```

## Environment

 - Longhorn version: v1.3.0-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubecl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.21.5+rke2r1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 20
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): EC2
 - Number of Longhorn volumes in the cluster: 999 volumes

## Additional context

n/a

**Comment by kaxing** [comment]
No more snapshot controller issue with latest master-head.
