### ISSUE TITLE
[BUG] Longhorn manager nil pointer dereference from proxy SnapshotBackup

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4061]
## Describe the bug

This error showed sometimes midway through full regression.
```
E0601 02:14:33.415803       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 835 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1cef3e0, 0x344d060})
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0005d0eb0})
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1cef3e0, 0x344d060})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/longhorn/longhorn-manager/engineapi.(*Proxy).SnapshotBackup(0xc001229d58, 0x0, {0xc000d14f60, 0x2d}, {0xc00115bd88, 0x17}, {0xc000d8ec60, 0x27}, {0x0, 0x0}, ...)
	/go/src/github.com/longhorn/longhorn-manager/engineapi/proxy_backup.go:28 +0x3b9
github.com/longhorn/longhorn-manager/engineapi.NewBackupMonitor({0x233a830, 0xc0006ced90}, 0xc000dd9180, 0xc0018a3c00, 0xc001229d70, {0x0, 0x0}, 0x0, {0x233d540, 0xc001229d58}, ...)
	/go/src/github.com/longhorn/longhorn-manager/engineapi/backup_monitor.go:74 +0x3ee
```

## To Reproduce

Run e2e regression, but not reproducible every time.

## Expected behavior

Longhorn manager shouldn't panic with nil pointer dereference.

## Log or Support bundle

`N/A`

## Environment

`N/A`

## Additional context

https://github.com/longhorn/longhorn/issues/3546

**Comment by NicklasWallgren** [comment]
@innobead @c3y1huang We are still seeing this particular bug in our cluster running longhorn 1.3.1


```
I1216 08:29:06.740172       1 controller.go:1472] delete "pvc-07057ace-caf3-4124-8835-27dfa1ad9b26": started
E1216 08:29:06.740311       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 322 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1776c20, 0x25e29d0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1776c20, 0x25e29d0)
	/go/pkg/csiprow.XXXXJBiJKk/go-1.15/src/runtime/panic.go:969 +0x175
github.com/kubernetes-csi/external-provisioner/pkg/controller.(*csiProvisioner).Delete(0xc00035e000, 0x1ba5be0, 0xc000154340, 0xc000bcaa00, 0x0, 0x0)
	/workspace/pkg/controller/controller.go:1146 +0x522
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).deleteVolumeOperation(0xc000457680, 0x1ba5be0, 0xc000154340, 0xc000bcaa00, 0xc000344801, 0xc000035ef0)
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:1474 +0x206
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).syncVolume(0xc000457680, 0x1ba5be0, 0xc000154340, 0x195ab40, 0xc000bcaa00, 0xc0006bc701, 0x0)
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:1128 +0xde
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).syncVolumeHandler(0xc000457680, 0x1ba5be0, 0xc000154340, 0xc000657710, 0x28, 0xc000046928, 0xc000813cb0)
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:1069 +0x8c
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).processNextVolumeWorkItem.func1(0xc000457680, 0xc000d05618, 0x1702c00, 0xc000477ae0, 0x0, 0x0)
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:1011 +0x125
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).processNextVolumeWorkItem(0xc000457680, 0x1ba5be0, 0xc000154340, 0x0)
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:1028 +0x71
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).runVolumeWorker(0xc000457680, 0x1ba5be0, 0xc000154340)
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:929 +0x3f
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1.3()
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:881 +0x3c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0003ca180)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0003ca180, 0x1b67260, 0xc000465110, 0x1, 0xc0000a4f60)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003ca180, 0x3b9aca00, 0x0, 0x1, 0xc0000a4f60)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0003ca180, 0x3b9aca00, 0xc0000a4f60)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:881 +0x3d6
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x15ef422]

goroutine 322 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1776c20, 0x25e29d0)
	/go/pkg/csiprow.XXXXJBiJKk/go-1.15/src/runtime/panic.go:969 +0x175
github.com/kubernetes-csi/external-provisioner/pkg/controller.(*csiProvisioner).Delete(0xc00035e000, 0x1ba5be0, 0xc000154340, 0xc000bcaa00, 0x0, 0x0)
	/workspace/pkg/controller/controller.go:1146 +0x522
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).deleteVolumeOperation(0xc000457680, 0x1ba5be0, 0xc000154340, 0xc000bcaa00, 0xc000344801, 0xc000035ef0)
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:1474 +0x206
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).syncVolume(0xc000457680, 0x1ba5be0, 0xc000154340, 0x195ab40, 0xc000bcaa00, 0xc0006bc701, 0x0)
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:1128 +0xde
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).syncVolumeHandler(0xc000457680, 0x1ba5be0, 0xc000154340, 0xc000657710, 0x28, 0xc000046928, 0xc000813cb0)
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:1069 +0x8c
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).processNextVolumeWorkItem.func1(0xc000457680, 0xc000d05618, 0x1702c00, 0xc000477ae0, 0x0, 0x0)
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:1011 +0x125
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).processNextVolumeWorkItem(0xc000457680, 0x1ba5be0, 0xc000154340, 0x0)
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:1028 +0x71
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).runVolumeWorker(0xc000457680, 0x1ba5be0, 0xc000154340)
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:929 +0x3f
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1.3()
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:881 +0x3c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0003ca180)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0003ca180, 0x1b67260, 0xc000465110, 0x1, 0xc0000a4f60)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003ca180, 0x3b9aca00, 0x0, 0x1, 0xc0000a4f60)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0003ca180, 0x3b9aca00, 0xc0000a4f60)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:881 +0x3d6
```

**Comment by innobead** [comment]
@NicklasWallgren is this log from longhorn-manager? where is the log from? external provisioner?

````
created by sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1
	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:881 +
````

**Comment by innobead** [comment]
yeah, then it's an issue of the upstream instead. https://github.com/kubernetes-csi/external-provisioner 

All CSI side cars Longhorn is using all from upstream w/o any changes, so suggest reporting the issue there to see if there is any similar issue or actually it has been fixed in which version. Basically, the problem you mentioned is different from this issue.

Or either create another Longhorn issue, so we can track this new issue with the upstream status.

**Comment by NicklasWallgren** [comment]
@innobead Great, thanks.

I have created a issue here, https://github.com/kubernetes-csi/external-provisioner/issues/839.
I'm a bit unsure which version of external-provisioner that is bundled with Longhorn 1.3.1 thought.

**Comment by innobead** [comment]
> @innobead Great, thanks.
> 
> I have created a issue here, [kubernetes-csi/external-provisioner#839](https://github.com/kubernetes-csi/external-provisioner/issues/839). I'm a bit unsure which version of external-provisioner that is bundled with Longhorn 1.3.1 thought.

It's 2.1.2. https://github.com/longhorn/longhorn/blob/v1.3.1/deploy/longhorn-images.txt#L2
