### ISSUE TITLE
[BUG] longhorn-manager crashed due to "close of closed channel"

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4106]
## Describe the bug

While downloading a backing image on v1.2.4 and then upgrade longhorn to master-head,
longhorn-manager status becomes CrashLoopBackOff.

## To Reproduce

1. Install longhorn-manager v1.2.4
2. Download one backing image
3. While downloading the backing image, upgrade to master-head branch
4. longhorn-manager status becomes CrashLoopBackOff 

log
```
time="2022-06-13T07:39:57Z" level=warning msg="Stop monitoring since monitor test1 sync reaches the max retry count 10" backingImageDataSource=test1 controller=longhorn-backing-image-data-source diskUUID=d216b4ee-ae87-4f32-a2fd-cabb12f14e71 node=rancher60-worker1 nodeID=rancher60-worker1 parameters="map[url:https://github.com/rancher/k3os/releases/download/v0.21.5-k3s2r1/k3os-amd64.iso]" sourceType=download
time="2022-06-13T07:39:57Z" level=info msg="Stopping monitoring" backingImageDataSource=test1 controller=longhorn-backing-image-data-source node=rancher60-worker1
panic: close of closed channel

goroutine 723 [running]:
github.com/longhorn/longhorn-manager/controller.(*BackingImageDataSourceController).stopMonitoring(0xc00037def0, {0xc00005ad26, 0x5})
	/go/src/github.com/longhorn/longhorn-manager/controller/backing_image_data_source_controller.go:918 +0x145
github.com/longhorn/longhorn-manager/controller.(*BackingImageDataSourceController).startMonitoring.func1()
	/go/src/github.com/longhorn/longhorn-manager/controller/backing_image_data_source_controller.go:958 +0x4c
created by github.com/longhorn/longhorn-manager/controller.(*BackingImageDataSourceController).startMonitoring
	/go/src/github.com/longhorn/longhorn-manager/controller/backing_image_data_source_controller.go:956 +0x465
```
## Expected behavior

no panic

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.23.6+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
cc @shuo-wu

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by derekbit** [comment]
Verified with master-head image 2022/06/13
Validation - PASSED

Steps:
1. Install longhorn-manager v1.2.4
2. Download one backing image
3. While downloading the backing image, upgrade to master-head branch
4. longhorn-manager can start as expected
