### ISSUE TITLE
[BUG] Suspected bug: Longhorn + Lucene - Lucene can't delete segment copies

### ISSUE THREAD

**Issue by chillwinston** [longhorn/longhorn#4161]
## Describe the bug

Jackrabbit Oak re-indexing failing due to an inability to delete Longhorn mounted Lucene index (data).  Does Longhorn prevent file deletions ?  We've moved Elastic off Longhorn due to similar log errors related to file locks.  I believe we're using an iSCSI target for longhorn clients.

java.io.IOException: Unable to delete file: /opt/aem/crx-quickstart/repository/index/customerRequirements-1650595584424/data/.nfs0000000000200fd300039d68
at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2400)

## To Reproduce

1. Within Adobe AEM with embedded Jackrabbit Oak
2. Jackrabbit Oak + AEM installed on RKE + Longhorn
3. Perform a repository reindex - this causes Lucene to reindex the content

## Expected behavior

Lucene reindex would occur as normal.  Note that Elastic (also using Lucene) does not recommend running Elastic on Longhorn / NFS mounted volumes:

## Log or Support bundle

22.04.2022 12:55:39.427 INFO [async-index-update-async] org.apache.jackrabbit.oak.plugins.index.IndexUpdate Reindexing will be performed for following indexes: [/oak:index/customerRequirements]
22.04.2022 12:55:39.427 INFO [async-index-update-async] org.apache.jackrabbit.oak.plugins.index.progress.NodeCounterMBeanEstimator Paths to be traversed includedPath : [/content/reports/refdata], excludedPaths : []
22.04.2022 12:55:39.427 INFO [async-index-update-async] org.apache.jackrabbit.oak.plugins.index.IndexUpdate Estimated node count to be traversed for reindexing under / is [0]
22.04.2022 12:55:40.965 WARN [oak-lucene-462] org.apache.jackrabbit.oak.plugins.index.lucene.IndexCopier Not able to remove old version of copied index at /opt/aem/crx-quickstart/repository/index/customerRequirements-1650595584424/data
java.io.IOException: Unable to delete file: /opt/aem/crx-quickstart/repository/index/customerRequirements-1650595584424/data/.nfs0000000000200fd300039d68
at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2400)
at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
at org.apache.jackrabbit.oak.plugins.index.lucene.IndexCopier$DeleteOldDirOnClose.close(IndexCopier.java:469) [org.apache.jackrabbit.oak-lucene:1.22.8]
at org.apache.jackrabbit.oak.plugins.index.lucene.directory.CopyOnReadDirectory$2.run(CopyOnReadDirectory.java:304) [org.apache.jackrabbit.oak-lucene:1.22.8]

## Environment

 - Longhorn version: Longhorn engine v1.2.2
 - Installation method (e.g. Rancher Catalog App:
 - Kubernetes distro (e.g. RKE) and version: v2.6.2
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster:2
 - Node config
   - OS type and version:
   - CPU per node: 8
   - Memory per node: 32G
   - Disk type(e.g. SSD/NVMe): SSD / Azure
   - Network bandwidth between the nodes: Azure gigabit
 - Underlying Infrastructure (Azure):
 - Number of Longhorn volumes in the cluster: 6

**Comment by derekbit** [comment]
@chillwinston Can you check`dmesg` and check if the file/dir is hold or locked by other process?

**Comment by chillwinston** [comment]
This is a Jackrabbit Oak component within Adobe AEM.  No other processes
would know of the existence of the Lucene index file, and Adobe AEM is an
Enterprise product that is unlikely to have such an issue.  Separately on
local copies of AEM (SSD) the issue doesn't occur.  I'll check once the
issue re-occurs, however the likelihood is that it isn't another process.

**Comment by chillwinston** [comment]
Some insight into the conditions under which Longhorn would prevent a file
from being deleted would be welcomed.  It seems very odd given Linux's
default non-locking style that Longhorn would by default lock files or
prevent file deletion.  I'm assuming a large test suite of common
filesystem use-cases have been used to test Longhorn ?

**Comment by derekbit** [comment]
Did you access the volume via NFS, right? If yes, I mean the .nfs000… is usually renamed from another file after the deletion for a nfs folder. In the case, the file cannot be deleted by another process. So, you can check if the file is really locked by fuser utility.

Longhorn provides the block storage, formats the file system and mounts it. It does not handle the file system stuff.

**Comment by davidfordaus** [comment]
Yes, the volume was accessed via NFS, however there are two possible causes of the bug:
1) Longhorn is inexplicably preventing files from being deleted possibly due to it preventing some blocks from being updated
2) NFS has an internal bug (regardless of the underlying block device; normal local disk or Longhorn) in which files/ folders are being prevented from deletion

I somehow doubt that there's a long-running defect within NFS , which leaves a Longhorn bug of some form.   The key question here is:
**A) Is there some case where Longhorn will prevent updates (or deletions) to blocks ?**

**Comment by chillwinston** [comment]
Greetings - as mentioned, this is still critical for us to understand why this process is failing under Longhorn, as otherwise we will be forced to choose an alternative technology to Longhorn.  We already have Rancher, so would prefer to stay within that technology stack, though if we can't trust Longhorn then we will be forced to move.   We may also be fine with purchasing support to resolve this, however I'm unsure if your support would be able to resolve this issue, and hence purchasing support would not be worthwhile.  

A) If we purchase Support will it be able to guarantee resolving this issue ?
B) As mentioned in my previous (unanswered) comment, are there any cases where Longhorn will prevent updates or deletions to blocks ?  If so - this would highlight the issue that we're seeing.

**Comment by derekbit** [comment]
> Is there some case where Longhorn will prevent updates (or deletions) to blocks ?

No, as I mentioned, Longhorn won't prevent the updates or deletion of blocks or files.

One exception is that if the connection between the engine and the replicas is not stable, the filesystem will be remounted to read-only filesystem. In the case, you can check if you can write or delete files in the filesystem. It rarely happen, but you can check this first.

Additionally, two things you need to check
1. If the software can work well using Longhorn volume but without through NFS?
2. Does the software support NFS?

**Comment by chillwinston** [comment]
Thanks for the response.  A key question revolves around the "connection between engine and replica's is not stable" - we're using Azure standard networking on a single Azure subnet; beyond that is the local Linux firewalls.  It theory both of these are stable, however it's possible they're not.  We'll check - thanks for that update.
Though it does raise a question of how Longhorn determines the "not stable" situation you mention (to drop to read-only mode), as well as whether the system then drops back out of read-only mode at a later date and if so, under what conditions.

As a preference we'd likely prefer that instead of dropping to read-only mode it just logs (I'm assuming there's a log?) changes locally and brings the replica's back up to date once they come back online - eg that it never goes to read only mode.

As to the software (Jackrabbit Oak), it appears that it does support NFS.  We're not easily able to shift to a different drive model other than NFS, though we may try that next to see if that'll resolve the issue.

**Comment by derekbit** [comment]
Usually, the the unstable connection can be handled by Longhorn. Longhorn marks the replica ERR and rebuilds it on another node. But in a very few situation, the filesystem is remounted to read-only mode, and Longhorn cannot handle this case currently. We still try to find a way to reproduce it and to investigate it.

**Comment by shuo-wu** [comment]
Do you mean that the filesystem becoming read-only is triggered by the rebuilding rather than the volume reattachment?
