### ISSUE TITLE
engine: tgtd sometime crashed, result in engine crash

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#424]
Collect this log from log of #411 

```
2019-02-19T04:27:34.256232851Z time="2019-02-19T04:27:34Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:27:34.424570832Z 10.42.1.166 - - [19/Feb/2019:04:27:34 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:27:34.424507357Z time="2019-02-19T04:27:34Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:28:06.184482826Z time="2019-02-19T04:28:06Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:28:06.3658069Z time="2019-02-19T04:28:06Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:28:06.600243815Z time="2019-02-19T04:28:06Z" level=info msg="Snapshot: 10.42.0.172:9502 734c462c-cc70-4bb0-a8ea-3b9d57b667a3 UserCreated false Created at 2019-02-19T04:28:06Z, Labels map[]"
2019-02-19T04:28:06.65359489Z time="2019-02-19T04:28:06Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:28:06.759919085Z time="2019-02-19T04:28:06Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:28:06.767859042Z 10.42.1.166 - - [19/Feb/2019:04:28:06 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:28:39.956542843Z time="2019-02-19T04:28:39Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:28:40.206701196Z time="2019-02-19T04:28:40Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:28:40.293256604Z time="2019-02-19T04:28:40Z" level=info msg="Snapshot: 10.42.0.172:9502 ea3e16f0-7811-4ce8-8e30-5a91d62f4d16 UserCreated false Created at 2019-02-19T04:28:40Z, Labels map[]"
2019-02-19T04:28:40.301154418Z time="2019-02-19T04:28:40Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:28:40.345739251Z time="2019-02-19T04:28:40Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:28:40.398780528Z 10.42.1.166 - - [19/Feb/2019:04:28:39 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:29:11.980285391Z time="2019-02-19T04:29:11Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:29:12.05609112Z time="2019-02-19T04:29:12Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:29:12.082782422Z time="2019-02-19T04:29:12Z" level=info msg="Snapshot: 10.42.0.172:9502 a36096a3-29c1-4dd3-bd73-2e507a8f2d63 UserCreated false Created at 2019-02-19T04:29:12Z, Labels map[]"
2019-02-19T04:29:12.086439962Z time="2019-02-19T04:29:12Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:29:12.090228619Z time="2019-02-19T04:29:12Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:29:12.093611873Z 10.42.1.166 - - [19/Feb/2019:04:29:11 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:29:45.948146312Z time="2019-02-19T04:29:45Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:29:46.036633639Z time="2019-02-19T04:29:46Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:29:46.051013742Z time="2019-02-19T04:29:46Z" level=info msg="Snapshot: 10.42.0.172:9502 a091228a-192d-499c-a541-07392a6b9c02 UserCreated false Created at 2019-02-19T04:29:46Z, Labels map[]"
2019-02-19T04:29:46.056051581Z time="2019-02-19T04:29:46Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:29:46.063745863Z time="2019-02-19T04:29:46Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:29:46.06671122Z 10.42.1.166 - - [19/Feb/2019:04:29:45 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:30:21.361635036Z time="2019-02-19T04:30:21Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:30:21.443979465Z time="2019-02-19T04:30:21Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:30:21.493726622Z time="2019-02-19T04:30:21Z" level=info msg="Snapshot: 10.42.0.172:9502 72431587-46a9-471b-bcc3-8f5bcae226f3 UserCreated false Created at 2019-02-19T04:30:21Z, Labels map[]"
2019-02-19T04:30:21.498519144Z time="2019-02-19T04:30:21Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:30:21.510217416Z time="2019-02-19T04:30:21Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:30:21.525397056Z 10.42.1.166 - - [19/Feb/2019:04:30:21 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:30:56.006462872Z time="2019-02-19T04:30:55Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:30:56.925303105Z time="2019-02-19T04:30:56Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:30:57.527949064Z time="2019-02-19T04:30:57Z" level=info msg="Snapshot: 10.42.0.172:9502 e6895906-c197-4e21-89ac-a980a65eb406 UserCreated false Created at 2019-02-19T04:30:57Z, Labels map[]"
2019-02-19T04:30:57.657015592Z time="2019-02-19T04:30:57Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:30:57.794431655Z time="2019-02-19T04:30:57Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:30:57.796456745Z 10.42.1.166 - - [19/Feb/2019:04:30:55 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:31:29.091635797Z time="2019-02-19T04:31:29Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:31:29.37102101Z time="2019-02-19T04:31:29Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:31:29.602397693Z time="2019-02-19T04:31:29Z" level=info msg="Snapshot: 10.42.0.172:9502 6488f8c4-3c32-4b72-9314-7e1249c281cc UserCreated false Created at 2019-02-19T04:31:29Z, Labels map[]"
2019-02-19T04:31:29.610449316Z time="2019-02-19T04:31:29Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:31:29.860847747Z time="2019-02-19T04:31:29Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:31:29.861427048Z 10.42.1.166 - - [19/Feb/2019:04:31:29 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:32:01.462029945Z time="2019-02-19T04:32:01Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:32:01.560438611Z time="2019-02-19T04:32:01Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:32:01.672336382Z time="2019-02-19T04:32:01Z" level=info msg="Snapshot: 10.42.0.172:9502 56f78fc4-d1ee-4822-90e7-e0d679aea5d2 UserCreated false Created at 2019-02-19T04:32:01Z, Labels map[]"
2019-02-19T04:32:01.678365457Z time="2019-02-19T04:32:01Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:32:01.678382507Z time="2019-02-19T04:32:01Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:32:01.672425777Z 10.42.1.166 - - [19/Feb/2019:04:32:01 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:32:33.185615189Z time="2019-02-19T04:32:33Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:32:33.315507347Z time="2019-02-19T04:32:33Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:32:33.605112956Z time="2019-02-19T04:32:33Z" level=info msg="Snapshot: 10.42.0.172:9502 44939934-168e-4409-a41e-3d7f6d0d5ae3 UserCreated false Created at 2019-02-19T04:32:33Z, Labels map[]"
2019-02-19T04:32:33.609791966Z time="2019-02-19T04:32:33Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:32:33.714890672Z time="2019-02-19T04:32:33Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:32:33.722415617Z 10.42.1.166 - - [19/Feb/2019:04:32:33 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:33:05.286997228Z time="2019-02-19T04:33:05Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:33:05.287818595Z time="2019-02-19T04:33:05Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:33:05.345999447Z time="2019-02-19T04:33:05Z" level=info msg="Snapshot: 10.42.0.172:9502 b15b117d-cd03-4881-a8a3-11a877c127ee UserCreated false Created at 2019-02-19T04:33:05Z, Labels map[]"
2019-02-19T04:33:05.347951603Z time="2019-02-19T04:33:05Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:33:05.356108508Z time="2019-02-19T04:33:05Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:33:05.361057715Z 10.42.1.166 - - [19/Feb/2019:04:33:05 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:33:37.203286016Z time="2019-02-19T04:33:37Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:33:37.524633163Z time="2019-02-19T04:33:37Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:33:37.762016792Z time="2019-02-19T04:33:37Z" level=info msg="Snapshot: 10.42.0.172:9502 87a57461-b3ac-4420-8e7e-7e875a98232c UserCreated false Created at 2019-02-19T04:33:37Z, Labels map[]"
2019-02-19T04:33:37.782475621Z time="2019-02-19T04:33:37Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:33:38.173397914Z time="2019-02-19T04:33:38Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:33:38.277938662Z 10.42.1.166 - - [19/Feb/2019:04:33:37 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:34:08.362508853Z time="2019-02-19T04:34:08Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:34:08.447351251Z time="2019-02-19T04:34:08Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:34:08.527528419Z time="2019-02-19T04:34:08Z" level=info msg="Snapshot: 10.42.0.172:9502 da3b8675-dd46-493a-a53e-d2596751a2c1 UserCreated false Created at 2019-02-19T04:34:08Z, Labels map[]"
2019-02-19T04:34:08.527583106Z time="2019-02-19T04:34:08Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:34:08.541694676Z time="2019-02-19T04:34:08Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:34:08.544174802Z 10.42.1.166 - - [19/Feb/2019:04:34:08 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:34:40.448375782Z time="2019-02-19T04:34:40Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:34:40.529134031Z time="2019-02-19T04:34:40Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:34:40.533989295Z time="2019-02-19T04:34:40Z" level=info msg="Snapshot: 10.42.0.172:9502 1c71c347-acd2-4085-aee3-276ddbfd2706 UserCreated false Created at 2019-02-19T04:34:40Z, Labels map[]"
2019-02-19T04:34:40.547931811Z time="2019-02-19T04:34:40Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:34:40.570339924Z 10.42.1.166 - - [19/Feb/2019:04:34:40 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:34:40.570492896Z time="2019-02-19T04:34:40Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:35:14.985422053Z time="2019-02-19T04:35:14Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:35:15.081763551Z time="2019-02-19T04:35:15Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:35:15.303503369Z time="2019-02-19T04:35:15Z" level=info msg="Snapshot: 10.42.0.172:9502 648e8b19-4f37-446e-9277-194bf96d2c5e UserCreated false Created at 2019-02-19T04:35:15Z, Labels map[]"
2019-02-19T04:35:15.410807575Z time="2019-02-19T04:35:15Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:35:15.701594371Z time="2019-02-19T04:35:15Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:35:15.762395064Z 10.42.1.166 - - [19/Feb/2019:04:35:14 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T04:35:48.901951461Z time="2019-02-19T04:35:48Z" level=info msg="Connecting to remote: 10.42.1.181:9502"
2019-02-19T04:35:49.510304928Z time="2019-02-19T04:35:49Z" level=info msg="Opening: 10.42.1.181:9502"
2019-02-19T04:35:50.532142969Z time="2019-02-19T04:35:50Z" level=info msg="Snapshot: 10.42.0.172:9502 851cfbab-1e06-4f70-85df-106c9ee5df15 UserCreated false Created at 2019-02-19T04:35:50Z, Labels map[]"
2019-02-19T04:35:50.887835508Z time="2019-02-19T04:35:50Z" level=info msg="Closing: 10.42.1.181:9502"
2019-02-19T04:35:51.511601635Z time="2019-02-19T04:35:51Z" level=error msg="Error in request: tcp://10.42.0.172:9502: Bad status: 500 500 Internal Server Error"
2019-02-19T04:35:51.52689584Z 10.42.1.166 - - [19/Feb/2019:04:35:48 +0000] "POST /v1/replicas HTTP/1.1" 500 210\
2019-02-19T05:40:45.425729257Z panic: signal: segmentation fault (core dumped)\
2019-02-19T05:40:45.426266601Z
2019-02-19T05:40:45.426279845Z goroutine 38 [running]:\
2019-02-19T05:40:45.429570488Z github.com/rancher/longhorn-engine-launcher/vendor/github.com/rancher/go-iscsi-helper/iscsi.startDaemon(0xc4200a4168, 0x0)\
2019-02-19T05:40:45.429591479Z\t/go/src/github.com/rancher/longhorn-engine-launcher/vendor/github.com/rancher/go-iscsi-helper/iscsi/target.go:193 +0x1df\
2019-02-19T05:40:45.431077746Z created by github.com/rancher/longhorn-engine-launcher/vendor/github.com/rancher/go-iscsi-helper/iscsi.StartDaemon\
2019-02-19T05:40:45.431099731Z\t/go/src/github.com/rancher/longhorn-engine-launcher/vendor/github.com/rancher/go-iscsi-helper/iscsi/target.go:163 +0x7d\
```

**Comment by yasker** [comment]
Cannot reproduce this recently.

**Comment by yasker** [comment]
Close this one. Feel free to reopen if the issue happens again in the latest release (v0.6.0).
