### ISSUE TITLE
[TEST] Jenkins broken icons, stylesheets/scripts not loaded

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#4426]
## What's the test to develop? Please describe

Jenkins broken icons, stylesheets/scripts not loaded:

`Refused to apply style from 'http://localhost:3000/assets/styles/custom-style.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

**Comment by yangchiu** [comment]
Don't modify anything but redeploy Jenkins fixes the issue temporarily.
So it's not related to incorrect config when startup the service, but there could be some operations mess up the config during the service running. Need to check if it happens after specific operations.

**Comment by yangchiu** [comment]
There are some `Java Heap Space Out of Memory` errors in jenkins logs:

```
2022-10-17 03:39:24.366+0000 [id=36568]	WARNING	h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID c874e295-301f-4c7c-be74-9a9f34591aaa
org.apache.commons.jelly.JellyTagException: jar:file:/var/jenkins_home/plugins/workflow-job/WEB-INF/lib/workflow-job.jar!/org/jenkinsci/plugins/workflow/job/WorkflowRun/console.jelly:74:27: <j:whitespace> Java heap space
	at org.apache.commons.jelly.impl.TagScript.handleException(TagScript.java:745)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:289)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:101)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
	at org.apache.commons.jelly.tags.core.OtherwiseTag.doTag(OtherwiseTag.java:41)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
	at org.apache.commons.jelly.tags.core.ChooseTag.doTag(ChooseTag.java:38)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:101)
	at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$1.run(CoreTagLibrary.java:98)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
	at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:122)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:101)
	at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:101)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:101)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:101)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:101)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:101)
	at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
	at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:122)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
	at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:122)
	at org.kohsuke.stapler.jelly.CompressTag.doTag(CompressTag.java:45)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
	at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:99)
	at org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:66)
	at org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:55)
	at org.kohsuke.stapler.jelly.ScriptInvoker.execute(ScriptInvoker.java:56)
	at org.kohsuke.stapler.jelly.ScriptInvoker.execute(ScriptInvoker.java:43)
	at org.kohsuke.stapler.Facet$1.dispatch(Facet.java:240)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:475)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:289)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:289)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:289)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:157)
	at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:81)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:129)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:160)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:160)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:94)
	at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:54)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:102)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:219)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:213)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:211)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getLogInputStream(WorkflowRun.java:1109)
	at hudson.model.Run.writeLogTo(Run.java:1533)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.commons.jexl.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:258)
	at org.apache.commons.jexl.parser.ASTMethod.execute(ASTMethod.java:104)
	at org.apache.commons.jexl.parser.ASTReference.execute(ASTReference.java:83)
	at org.apache.commons.jexl.parser.ASTReference.value(ASTReference.java:57)
	at org.apache.commons.jexl.parser.ASTReferenceExpression.value(ASTReferenceExpression.java:51)
	at org.apache.commons.jexl.ExpressionImpl.evaluate(ExpressionImpl.java:80)
	at hudson.ExpressionFactory2$JexlExpression.evaluate(ExpressionFactory2.java:76)
	at org.apache.commons.jelly.parser.EscapingExpression.evaluate(EscapingExpression.java:24)
	at org.apache.commons.jelly.impl.ExpressionScript.run(ExpressionScript.java:66)
	at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
	at org.apache.commons.jelly.tags.core.WhitespaceTag.doTag(WhitespaceTag.java:48)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:101)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
	at org.apache.commons.jelly.tags.core.OtherwiseTag.doTag(OtherwiseTag.java:41)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
	at org.apache.commons.jelly.tags.core.ChooseTag.doTag(ChooseTag.java:38)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:101)
```

If we printed out the JVM min/max heap size, they're quite small:

```
$ java -XX:+PrintFlagsFinal -version | grep HeapSize
   size_t ErgoHeapSizeLimit                        = 0                                         {product} {default}
   size_t HeapSizePerGCThread                      = 43620760                                  {product} {default}
   size_t InitialHeapSize                          = 67108864                                  {product} {ergonomic}
   size_t LargePageHeapSizeThreshold               = 134217728                                 {product} {default}
   size_t MaxHeapSize                              = 1073741824                                {product} {ergonomic}
    uintx NonNMethodCodeHeapSize                   = 5825164                                {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 122916538                              {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 122916538                              {pd product} {ergonomic}
   size_t ShenandoahSoftMaxHeapSize                = 0                                      {manageable} {default}
```

The initial heap size is 64 MB only, and the max heap size is 1024 MB only.

Tried to specify pod resource limit and java options in jenkins/values.xml like:

```
  resources:
    requests:
      cpu: "2000m"
      memory: "2048Mi"
    limits:
      cpu: "4000m"
      memory: "4096Mi"
  javaOpts: "-Xms2048M -Xmx4096M"
```

But somehow it doesn't work, the heap size doesn't change after these values applied, need more experiments.

**Comment by yangchiu** [comment]
https://stackoverflow.com/a/64410587

```
  resources:
    limits:
      memory: "8Gi"
```

`resources.limits.memory` is the actual value controls the init/max heap size in JVM.
By default, The init heap size would be set to 1/64 of this value, and the max heap size would be set to 1/4 of this value.

MaxRAMFraction, MaxRAMPercentage, InitialRAMFraction, InitialRAMPercentage should be able to adjust to affect the above values, but somehow it's not working. Seems like javaOpts in jenkins helm chart doesn't work.

**Comment by innobead** [comment]
Could you check if the settings have been applied to the process command? These options should be together with the command line which is used to start the process.

**Comment by yangchiu** [comment]
Yes, the command is `java -Duser.home=/var/jenkins_home -Dcasc.reload.token=myjenkins-0 -XX:MaxRAMFraction=2 -XX:InitialRAMFraction=8 -Djenkins.model.Jenkins.slaveAgentPort=50000 -jar /usr/share/jenkins/jenkins.war --webroot=/var/jenkins_cache/war --httpPort=8080`

But somehow the values didn't set to JVM:
```
$ java -XX:+PrintFlagsFinal -version | grep Fraction
     intx CMSInitiatingOccupancyFraction           = -1                                        {product} {default}
    uintx InitialRAMFraction                       = 64                                        {product} {default}
    uintx MaxRAMFraction                           = 4                                         {product} {default}
    uintx MinRAMFraction                           = 2                                         {product} {default}
    uintx TLABRefillWasteFraction                  = 64                                        {product} {default}
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)

```

**Comment by yangchiu** [comment]
https://stackoverflow.com/a/2011420: `The key thing to understand here is that arguments to java that come before the -jar analyse.jar bit will only affect the JVM and won't be passed along to your program.`

https://stackoverflow.com/a/11615960: `setup _JAVA_OPTIONS instead of JAVA_OPTS.`

https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/VALUES_SUMMARY.md: `use controller.containerEnv to set Environment variables for Jenkins Container`

sum it up, the actual right way to do this should be:
```
  resources:
    requests:
      cpu: "2000m"
      memory: "4Gi"
    limits:
      cpu: "4000m"
      memory: "10Gi"
  containerEnv:
    - name: _JAVA_OPTIONS
      value: "-Xms2048M -Xmx8192M"
```

**Comment by yangchiu** [comment]
After enlarge java heap size, this issue is still present:
```
$ java -XX:+PrintFlagsFinal -version | grep HeapSize
Picked up _JAVA_OPTIONS: -Xms2048M -Xmx8192M
   size_t ErgoHeapSizeLimit                        = 0                                         {product} {default}
   size_t HeapSizePerGCThread                      = 43620760                                  {product} {default}
   size_t InitialHeapSize                          = 2147483648                                {product} {command line}
   size_t LargePageHeapSizeThreshold               = 134217728                                 {product} {default}
   size_t MaxHeapSize                              = 8589934592                                {product} {command line}
    uintx NonNMethodCodeHeapSize                   = 5830732                                {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 122913754                              {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 122913754                              {pd product} {ergonomic}
   size_t ShenandoahSoftMaxHeapSize                = 0                                      {manageable} {default}
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
```

```
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/echarts.min.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
Loading failed for the <script> with source “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/echarts.min.js”. longhorn-tests-regression:61:1
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/jquery3-api/webjars/jquery.min.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/jquery3-api/plugins/visible.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/css/jenkins-style.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/echarts-scope.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/trend-chart.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/zoomable-trend-chart.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/chart-configuration.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/configurable-trend-chart.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/progress-chart.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/pie-chart.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/jquery3-api/webjars/jquery.min.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
Loading failed for the <script> with source “https://ci.longhorn.io/static/6f16a922/plugin/jquery3-api/webjars/jquery.min.js”. longhorn-tests-regression:64:1
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/jquery3-api/plugins/visible.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
Loading failed for the <script> with source “https://ci.longhorn.io/static/6f16a922/plugin/jquery3-api/plugins/visible.js”. longhorn-tests-regression:64:1
Uncaught TypeError: jQuery3.noConflict is not a function
    <anonymous> https://ci.longhorn.io/job/private/job/longhorn-tests-regression/:66
longhorn-tests-regression:66:13
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/css/jenkins-style.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/echarts-scope.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
Loading failed for the <script> with source “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/echarts-scope.js”. longhorn-tests-regression:67:1
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/chart-configuration.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
Loading failed for the <script> with source “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/chart-configuration.js”. longhorn-tests-regression:67:1
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/trend-chart.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
Loading failed for the <script> with source “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/trend-chart.js”. longhorn-tests-regression:67:1
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/zoomable-trend-chart.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
Loading failed for the <script> with source “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/zoomable-trend-chart.js”. longhorn-tests-regression:67:1
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/configurable-trend-chart.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
Loading failed for the <script> with source “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/configurable-trend-chart.js”. longhorn-tests-regression:67:1
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/pie-chart.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
longhorn-tests-regression
Loading failed for the <script> with source “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/pie-chart.js”. longhorn-tests-regression:67:1
The resource from “https://ci.longhorn.io/static/6f16a922/plugin/echarts-api/js/progress-chart.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```
The broken icon, css, js files are located in `/var/jenkins_home/war` or `/var/jenkins_home/plugins`, let's see if files still exist in the folders or not when this issue happened again.

**Comment by yangchiu** [comment]
Before this issue happened, js and css files can be found in `/var/jenkins_home/plugins` folder:
```
$ find . -name visible.js
./plugins/jquery3-api/plugins/visible.js
$ find . -name jquery.min.js
./plugins/jquery3-api/webjars/jquery.min.js
$ find . -name svg-sprite-navigation-symbol.svg
./var/jenkins_cache/war/images/material-icons/svg-sprite-navigation-symbol.svg
./var/jenkins_home/war/images/material-icons/svg-sprite-navigation-symbol.svg
$ find . -name jenkins-style.css
./var/jenkins_home/plugins/bootstrap5-api/css/jenkins-style.css
./var/jenkins_home/plugins/font-awesome-api/css/jenkins-style.css
./var/jenkins_home/plugins/echarts-api/css/jenkins-style.css
./var/jenkins_home/plugins/bootstrap4-api/css/jenkins-style.css
```
And there are lots of files in `var/jenkins+home/plugins` folder:
```
$ cd plugins
$ ls
ace-editor
ace-editor.jpi
ace-editor.jpi.pinned
ace-editor.jpi.version_from_image
ant
ant.jpi
ant.jpi.pinned
ant.jpi.version_from_image
antisamy-markup-formatter
antisamy-markup-formatter.jpi
antisamy-markup-formatter.jpi.pinned
antisamy-markup-formatter.jpi.version_from_image
apache-httpcomponents-client-4-api
apache-httpcomponents-client-4-api.jpi
apache-httpcomponents-client-4-api.jpi.pinned
apache-httpcomponents-client-4-api.jpi.version_from_image
authentication-tokens
authentication-tokens.jpi
authentication-tokens.jpi.pinned
authentication-tokens.jpi.version_from_image
...
```

After this issue happened, `var/jenkins+home/plugins` folder become empty:
```
$ find . -name svg-sprite-navigation-symbol.svg
./war/images/material-icons/svg-sprite-navigation-symbol.svg
$ find . -name jenkins-style.css
$ find . -name jquery.min.js
$ find . -name visible.js
$ cd plugins
$ ls
```

Someone said it's because of running out of disk space: https://github.com/jenkins-x/jx/issues/2522#issuecomment-535023865

And after looked up jenkins Longhorn volume, it's indeed running out of space (Size = 40G, Actual Size = 47G) and there are lots of redundant old backups.

After removed old backups, jenkins Longhorn volume usage becomes Size = 40G, Actual Size = 33G. Let see if this issue will happen again.

**Comment by yangchiu** [comment]
Doesn't happen for more than 1 week. Close this ticket for now, but still needs a discarding old builds mechanism https://github.com/longhorn/longhorn/issues/5390 in https://github.com/longhorn/infra.

Once old builds accumulates and run out of volume space, this issue would happen again.

**Comment by yangchiu** [comment]
This issue happened again even though there are still free volume space. Reopen it.

**Comment by yangchiu** [comment]
Fixed by disabling Jenkins automatic plugin updates which could install incompatible plugins and potentially break Jenkins:

https://stackoverflow.com/questions/53756840/how-to-disable-updates-in-jenkins

```
To disable autoupdate of plugins, you need to go to Manage Jenkins -> Manage Plugins -> Advanced -> scroll down to the Update Site section, remove the default value from the URL box, and save changes (i.e. hit Enter or click the Submit button).

https://updates.jenkins-ci.org/current/update-center.json is points to the Jenkins update center. And the update center is used by Jenkins to download and install plugins, and it is updated regularly with new plugin releases. 
```
