### ISSUE TITLE
[BUG] Some volumes fail to backup

### ISSUE THREAD

**Issue by mateuszdrab** [longhorn/longhorn#4539]
## Describe the bug

Some longhorn volumes fail to backup to S3 (Minio). When a backup is trigerred, the instance 'dies' and restarts, this triggers a rebuild of the instance.
One specific volume I tried it one had one backup succeed a month ago but all subsequent backups fail.
I deleted all old backups and tried again to no avail.

Also also tried backing up from an existing snapshot with the same/similar outcome as above.

## Expected behavior

A backup should be taken to S3

## Log or Support bundle

Attaching some logs, I've capture a full support bundle and happy to provide it.

```
[longhorn-instance-manager] time="2022-09-08T11:13:11Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:11Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:11Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:11Z" level=debug msg="Getting volume" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:11Z" level=debug msg="Getting replica rebuilding status" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:11Z" level=debug msg="Get snapshot purge status" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:11Z" level=debug msg="Getting backup restore status" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:11Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:12Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:12Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:12Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:12Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:12Z" level=debug msg="Getting volume" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:12Z" level=debug msg="Getting replica rebuilding status" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:12Z" level=debug msg="Get snapshot purge status" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:12Z" level=debug msg="Getting volume" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:12Z" level=debug msg="Getting replica rebuilding status" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:12Z" level=debug msg="Get snapshot purge status" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:12Z" level=debug msg="Getting backup restore status" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Getting backup restore status" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10001"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10001"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Getting volume" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Getting replica rebuilding status" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Get snapshot purge status" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Getting volume" serviceURL="10.42.10.197:10001"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Getting replica rebuilding status" serviceURL="10.42.10.197:10001"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Get snapshot purge status" serviceURL="10.42.10.197:10001"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Getting backup restore status" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:13Z" level=debug msg="Getting backup restore status" serviceURL="10.42.10.197:10001"
[longhorn-instance-manager] time="2022-09-08T11:13:14Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:14Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10001"
[longhorn-instance-manager] time="2022-09-08T11:13:15Z" level=debug msg="Snapshotting volume " serviceURL="10.42.10.197:10004"
[pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c-e-1d8a9715] time="2022-09-08T11:13:15Z" level=info msg="Starting snapshot" snapshot= volume=pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c
[pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c-e-1d8a9715] time="2022-09-08T11:13:15Z" level=info msg="Requesting system sync before snapshot" snapshot= volume=pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c
[longhorn-instance-manager] time="2022-09-08T11:13:15Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:15Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10005"
[pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c-e-1d8a9715] time="2022-09-08T11:13:15Z" level=info msg="Starting to snapshot: 10.42.8.141:10000 657dfc93-269b-45c0-aea6-05f1b57521e3 UserCreated true Created at 2022-09-08T11:13:15Z, Labels map[]"
[pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c-e-1d8a9715] time="2022-09-08T11:13:15Z" level=info msg="Finished to snapshot: 10.42.8.141:10000 657dfc93-269b-45c0-aea6-05f1b57521e3 UserCreated true Created at 2022-09-08T11:13:15Z, Labels map[]"
[pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c-e-1d8a9715] time="2022-09-08T11:13:15Z" level=info msg="Finished snapshot" snapshot= volume=pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c
[longhorn-instance-manager] time="2022-09-08T11:13:15Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:15Z" level=debug msg="Getting volume" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:15Z" level=debug msg="Getting replica rebuilding status" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:15Z" level=debug msg="Get snapshot purge status" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:15Z" level=debug msg="Getting backup restore status" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:15Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:16Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:16Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:16Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:16Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:16Z" level=debug msg="Getting volume" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:16Z" level=debug msg="Getting replica rebuilding status" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:16Z" level=debug msg="Get snapshot purge status" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:16Z" level=debug msg="Getting backup restore status" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:16Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:17Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:17Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:17Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:17Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:17Z" level=debug msg="Getting volume" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:17Z" level=debug msg="Getting replica rebuilding status" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:17Z" level=debug msg="Get snapshot purge status" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:17Z" level=debug msg="Getting volume" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:17Z" level=debug msg="Getting replica rebuilding status" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:17Z" level=debug msg="Get snapshot purge status" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:17Z" level=debug msg="Getting backup restore status" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Getting backup restore status" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10001"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10001"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Getting volume" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Getting replica rebuilding status" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Get snapshot purge status" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Getting volume" serviceURL="10.42.10.197:10001"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Getting replica rebuilding status" serviceURL="10.42.10.197:10001"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Get snapshot purge status" serviceURL="10.42.10.197:10001"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Getting backup restore status" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:18Z" level=debug msg="Getting backup restore status" serviceURL="10.42.10.197:10001"
[longhorn-instance-manager] time="2022-09-08T11:13:19Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10003"
[longhorn-instance-manager] time="2022-09-08T11:13:19Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10001"
[pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c-e-1d8a9715] time="2022-09-08T11:13:19Z" level=error msg="Error reading from wire: EOF"
response_process: Receive error for response 3 of seq 297
tgtd: bs_longhorn_request(105) fail to read at 17371136 for 4096
tgtd: bs_longhorn_request(150) io error 0x2cac1d0 28 -14 4096 17371136, Success
[pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c-e-1d8a9715] time="2022-09-08T11:13:20Z" level=error msg="RemovePendingOp: OpID already removed0"
time="2022-09-08T11:13:20Z" level=error msg="Replicator.ReadAt:0 EOF"
response_process: Receive error for response 3 of seq 298
tgtd: bs_longhorn_request(91) fail to write at 0 for 4096
tgtd: bs_longhorn_request(150) io error 0x2cac1d0 2a -14 4096 0, Success
[pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c-e-1d8a9715] time="2022-09-08T11:13:20Z" level=error msg="Setting replica tcp://10.42.8.141:10000 to ERR due to: EOF"
time="2022-09-08T11:13:20Z" level=info msg="Set replica tcp://10.42.8.141:10000 to mode ERR"
time="2022-09-08T11:13:20Z" level=error msg="I/O error: tcp://10.42.8.141:10000: EOF"
time="2022-09-08T11:13:20Z" level=info msg="Monitoring stopped tcp://10.42.8.141:10000"
time="2022-09-08T11:13:20Z" level=error msg="I/O error: no backend available"
response_process: Receive error for response 3 of seq 299
tgtd: bs_longhorn_request(105) fail to read at 17371136 for 4096
tgtd: bs_longhorn_request(150) io error 0x2cac1d0 28 -14 4096 17371136, Success
[pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c-e-1d8a9715] time="2022-09-08T11:13:20Z" level=error msg="I/O error: no backend available"
[pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c-e-1d8a9715] time="2022-09-08T11:13:20Z" level=error msg="I/O error: no backend available"
response_process: Receive error for response 3 of seq 300
tgtd: bs_longhorn_request(91) fail to write at 0 for 4096
tgtd: bs_longhorn_request(150) io error 0x2cac1d0 2a -14 4096 0, Success
[pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c-e-1d8a9715] time="2022-09-08T11:13:20Z" level=error msg="I/O error: no backend available"
response_process: Receive error for response 3 of seq 301
tgtd: bs_longhorn_request(105) fail to read at 17371136 for 4096
tgtd: bs_longhorn_request(150) io error 0x2cac1d0 28 -14 4096 17371136, Success
[pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c-e-1d8a9715] time="2022-09-08T11:13:20Z" level=error msg="I/O error: no backend available"
response_process: Receive error for response 3 of seq 302
tgtd: bs_longhorn_request(91) fail to write at 0 for 4096
tgtd: bs_longhorn_request(150) io error 0x2cac1d0 2a -14 4096 0, Success
[longhorn-instance-manager] time="2022-09-08T11:13:20Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:20Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:20Z" level=debug msg="Getting volume" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:20Z" level=debug msg="Getting replica rebuilding status" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:20Z" level=debug msg="Get snapshot purge status" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:20Z" level=debug msg="Getting backup restore status" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:21Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10005"
[longhorn-instance-manager] time="2022-09-08T11:13:21Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:21Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:21Z" level=debug msg="Getting volume" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:21Z" level=debug msg="Getting replica rebuilding status" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:21Z" level=debug msg="Get snapshot purge status" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:21Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:21Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:21Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:21Z" level=debug msg="Getting backup restore status" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:21Z" level=debug msg="Getting snapshot clone status" serviceURL="10.42.10.197:10004"
[longhorn-instance-manager] time="2022-09-08T11:13:21Z" level=debug msg="Process Manager: start getting logs for process pvc-7e9d77b1-8313-4cfd-bb7f-6550d317507c-e-1d8a9715"
[longhorn-instance-manager] time="2022-09-08T11:13:22Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:22Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10002"
[longhorn-instance-manager] time="2022-09-08T11:13:22Z" level=debug msg="Listing replicas" serviceURL="10.42.10.197:10000"
[longhorn-instance-manager] time="2022-09-08T11:13:22Z" level=debug msg="Listing snapshots" serviceURL="10.42.10.197:10000"
```

## Environment

 - Longhorn version: 1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 1.23.10
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 9
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 4+
   - Memory per node: 4+
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: Variable
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMware
 - Number of Longhorn volumes in the cluster: 15

**Comment by Parit99** [comment]
I would like to work on this enhancement.. Can I please get some kind of approval from any contributor to this repository?
About Me:
I am a student currently completing his Post Grad in Computer Science. I have been assigned a course component that involves contributing to any open-source project. I like this repository and would like to start from scratch to try to get this issue fixed

**Comment by mantissahz** [comment]
Hi @mateuszdrab it would be great if you provide the full support bundle. Thank you.

>I would like to work on this enhancement.. Can I please get some kind of approval from any contributor to this repository?

cc @innobead

**Comment by mateuszdrab** [comment]
@mantissahz Do you guys have some location where I can upload it without it being public?

**Comment by mantissahz** [comment]
@mateuszdrab You could send it to longhorn-support-bundle@Suse.com
Thank you.

**Comment by mateuszdrab** [comment]
Any update?

**Comment by mantissahz** [comment]
@mateuszdrab,
Sorry about that I did not receive the support bundle, could you please send that again?
You could send longhorn-support-bundle@rancher.com or longhorn-support-bundle@suse.com
Thank you

**Comment by mateuszdrab** [comment]
@mantissahz I sent it again, to both addresses :)

**Comment by mateuszdrab** [comment]
Any update please? @mantissahz 
Still have plenty of volumes with no backups...

**Comment by mantissahz** [comment]
@mateuszdrab 
Can you try to edit longhorn-manager daemonset by 
`kubectl -n longhorn-system edit daemonset longhorn-manager`
Add
```
            - name: GODEBUG
              value: netdns=go
```
to `env`.

ref: https://github.com/longhorn/longhorn/issues/1768, https://github.com/longhorn/longhorn/issues/4415

**Comment by mateuszdrab** [comment]
I've added that, I will observer the backups now and trigger some manually...
Currently the backup endpoint's dns name is a .local ending name but not within the cluster - I will be moving this to a public DNS record soon so it may fix it... but I will avoid making too many changes at the same time.

**Comment by mateuszdrab** [comment]
Still fails, with the following in the UI:
```
Name: eaceaefb-21fe-46f4-8f20-89a0815ffacc

Created: 2022-10-03T09:21:04Z

Size: 0 Bi

Created By User: True

Removed: False

Progress: 37%

Replicas: pvc-4e3fbafb-a539-4c3a-9d46-d60579d2a2c2-r-c9043637

Backups: backup-f38ba89c5b824d88

pvc-4e3fbafb-a539-4c3a-9d46-d60579d2a2c2-r-c9043637: proxyServer=10.42.7.242:8501 destination=10.42.10.112:10000: failed to get backup-f38ba89c5b824d88 backup status: rpc error: code = Unknown desc = failed to get backup-f38ba89c5b824d88 backup status on unknown replica tcp://10.42.10.111:10030
```

**Comment by mateuszdrab** [comment]
I'm sending another log bundle, I tried to restore a volume from a backup and it crashes out the entire node (all volumes restart on it)

**Comment by mantissahz** [comment]
There is still the problem with cgo
```text
2022-10-03T09:21:08.288524800Z [pvc-4e3fbafb-a539-4c3a-9d46-d60579d2a2c2-r-c9043637] time="2022-10-03T09:21:08Z" level=info msg="Done initiating backup creation, received backupID: backup-f38ba89c5b824d88"
2022-10-03T09:21:13.266708970Z [pvc-4e3fbafb-a539-4c3a-9d46-d60579d2a2c2-r-c9043637] fatal error: unexpected signal during runtime execution
2022-10-03T09:21:13.269178320Z [pvc-4e3fbafb-a539-4c3a-9d46-d60579d2a2c2-r-c9043637] [signal SIGSEGV: segmentation violation code=0x1 addr=0x47 pc=0x7f12b402d341]
2022-10-03T09:21:13.269214244Z
2022-10-03T09:21:13.269229144Z runtime stack:
2022-10-03T09:21:13.269241441Z runtime.throw(0xef29e8, 0x2a)
2022-10-03T09:21:13.271910654Z  /usr/local/go/src/runtime/panic.go:[pvc-4e3fbafb-a539-4c3a-9d46-d60579d2a2c2-r-c9043637] 1116 +0x72
2022-10-03T09:21:13.271946488Z runtime.sigpanic()
2022-10-03T09:21:13.271960307Z  /usr/local/go/src/runtime/signal_unix.go:701 +0x46a
2022-10-03T09:21:13.271971152Z
2022-10-03T09:21:13.271984541Z goroutine 580693 [syscall]:
2022-10-03T09:21:13.272003873Z runtime.cgocall(0xc080e0, 0xc000052dc0, 0xc000066040)
2022-10-03T09:21:13.272017178Z  /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000052d90 sp=0xc000052d58 pc=0x403fab
2022-10-03T09:21:13.272028484Z net._C2func_getaddrinfo(0xc00003f0c0, 0x0, 0xc0003e0d80, 0xc000066040, 0x0, 0x0, 0x0)
2022-10-03T09:21:13.272039670Z  _cgo_gotypes.go:92 +0x55 fp=0xc000052dc0 sp=0xc000052d90 pc=0x6a3e95
2022-10-03T09:21:13.272052745Z net.cgoLookupIPCNAME.func1(0xc00003f0c0, 0x35, 0x35, 0xc0003e0d80, 0xc000066040, 0x0, 0x0, 0x0)
2022-10-03T09:21:13.272063597Z  /usr/local/go/src/net/cgo_unix.go:161 +0xd2 fp=0xc000052e08 sp=0xc000052dc0 pc=0x6a99b2
2022-10-03T09:21:13.272075087Z net.cgoLookupIPCNAME(0xec9b58, 0x3, 0xc00003f040, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2022-10-03T09:21:13.272086950Z  /usr/local/go/src/net/cgo_unix.go:161 +0x183 fp=[pvc-4e3fbafb-a539-4c3a-9d46-d60579d2a2c2-r-c9043637] 0xc000052f18 sp=0xc000052e08 pc=0x6a5323
2022-10-03T09:21:13.272099522Z net.cgoIPLookup(0xc0003a7320, 0xec9b58, 0x3, 0xc00003f040, 0x34)
2022-10-03T09:21:13.272106760Z  /usr/local/go/src/net/cgo_unix.go:218 +0x67 fp=0xc000052fb8 sp=0xc000052f18 pc=0x6a5a57
2022-10-03T09:21:13.272113691Z runtime.goexit()
2022-10-03T09:21:13.272120679Z  /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000052fc0 sp=0xc000052fb8 pc=0x4653f1
2022-10-03T09:21:13.272127797Z created by net.cgoLookupIP
2022-10-03T09:21:13.272135005Z  /usr/local/go/src/net/cgo_unix.go:228 +0xc7
2022-10-03T09:21:13.272141552Z
2022-10-03T09:21:13.272148440Z goroutine 1 [IO wait]:
2022-10-03T09:21:13.272155301Z internal/poll.runtime_pollWait(0x7f12b4c54610, 0x72, 0x0)
2022-10-03T09:21:13.272162679Z  /usr/local/go/src/runtime/netpoll.go:203 +0x55
2022-10-03T09:21:13.272169411Z internal/poll.(*pollDesc).wait(0xc000132618, 0x72, 0x0, 0x0, 0xeccbbd)
2022-10-03T09:21:13.272176218Z  /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
2022-10-03T09:21:13.272182929Z internal/poll.(*pollDesc).waitRead(...)
2022-10-03T09:21:13.272189684Z  /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
2022-10-03T09:21:13.272196431Z internal/poll.(*FD).Accept(0xc000132600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2022-10-03T09:21:13.272203285Z  /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1d4
2022-10-03T09:21:13.272210023Z net.(*netFD).accept(0xc000132600, 0x37e11d600, 0x0, 0x0)
2022-10-03T09:21:13.272216714Z  /usr/local/go/src/net/fd_unix.go:238 +0x42
2022-10-03T09:21:13.272223532Z net.(*TCPListener).accept(0xc000386260, 0xc000228090, 0xc000228098, 0x18)
2022-10-03T09:21:13.272230186Z  /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
2022-10-03T09:21:13.272237321Z net.(*TCPListener).Accept(0xc000386260, 0xf0f1d8, 0xc000104780, 0x1153540, 0xc00012e068)
2022-10-03T09:21:13.272244188Z  /usr/local/go/src/net/tcpsock.go:261 +0x64
2022-10-03T09:21:13.272250886Z google.golang.org/grpc.(*Server).Serve(0xc000104780, 0x1146f00, 0xc000386260, 0x0, 0x0)
2022-10-03T09:21:13.272259949Z [pvc-4e3fbafb-a539-4c3a-9d46-d60579d2a2c2-r-c9043637]    /go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:587 +0x210
2022-10-03T09:21:13.272287517Z github.com/longhorn/longhorn-engine/app/cmd.startSyncAgent(0xc00014ab00, 0xecad20, 0x0)
2022-10-03T09:21:13.272299814Z  /go/src/github.com/longhorn/longhorn-engine/app/cmd/sync_agent.go:89 +0x503
2022-10-03T09:21:13.272312259Z github.com/longhorn/longhorn-engine/app/cmd.SyncAgentCmd.func1(0xc00014ab00)
2022-10-03T09:21:13.272322060Z  /go/src/github.com/longhorn/longhorn-engine/app/cmd/sync_agent.go:40 +0x2f
2022-10-03T09:21:13.272332709Z github.com/urfave/cli.HandleAction(0xd63a20, 0xf0eb40, 0xc00014ab00, 0xc00014ab00, 0x0)
2022-10-03T09:21:13.272342910Z  /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/app.go:525 +0x7c
2022-10-03T09:21:13.272355905Z github.com/urfave/cli.Command.Run(0xecffe1, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xee7c9f, ...)
2022-10-03T09:21:13.272365763Z  /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/command.go:174 +0x56e
2022-10-03T09:21:13.272372934Z github.com/urfave/cli.(*App).Run(0xc0001c21c0, 0xc000132000, 0x8, 0x8, 0x0, 0x0)
2022-10-03T09:21:13.272379759Z  /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/app.go:276 +0x7ae
2022-10-03T09:21:13.272386523Z main.longhornCli()
2022-10-03T09:21:13.272393334Z  /go/src/github.com/longhorn/longhorn-engine/main.go:126 +0xaa3
2022-10-03T09:21:13.272400348Z main.main()
2022-10-03T09:21:13.272407226Z  /go/src/github.com/longhorn/longhorn-engine/main.go:33 +0x13b
```

**Comment by mateuszdrab** [comment]
@mantissahz Got it, is this something new or already being worked on by the team?

**Comment by mateuszdrab** [comment]
I've migrated my minio instance to a DNS zone other than .local and I've been able to restore and take backups so far - will confirm overnight when the backup of everything job kicks in.

**Comment by mantissahz** [comment]
Keep track of https://github.com/longhorn/longhorn/issues/1768
