### ISSUE TITLE
[TEST] jenkins jobs failed to start: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#4703]
## What's the test to develop? Please describe

On 2022/10/11, most of our jenkins daily jobs failed to start with [the following error](https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-upgrade-tests-sles-arm64/112/console):
```
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.42.0.160/10.42.0.160:38828
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1785)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at hudson.FilePath.act(FilePath.java:1194)
		at hudson.FilePath.act(FilePath.java:1183)
		at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:126)
		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:907)
		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:838)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1291)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached 
```

After investigated on the servers, there are some `tgtd -f` processes utilizing 100% CPU.

Longhorn itself had this issue before: https://github.com/longhorn/longhorn/issues/3636

But in our current jenkins case, these `tgtd -f` processes actually aren't triggered by the Longhorn installed on the server, so upgrade Longhorn version didn't help. Turn out these `tgtd -f` processes are triggered by longhorn-engine integration tests, but somehow these integration test containers didn't being killed and live on the servers forever.

Solution:
(1) `top` to see if there is any high CPU `tgtd -f` process
(2) `ps aux --forest` to find out the parent process triggered the `tgtd -f` process, the corresponding container id should be shown
(3) `docker container ls` to check the container id, its entry point should be something like `/scripts ci` which indicates it's an integration test
(4) `docker container stop` the corresponding container

**Comment by innobead** [comment]
cc @shuo-wu @derekbit @joshimoo it seems some tgtd process leak?

> After investigated on the servers, there are some tgtd -f processes utilizing 100% CPU.

**Comment by yangchiu** [comment]
No, it seems like orphaned container not properly stopped. Yesterday I probably stopped 10 this kind of containers, some of them just live for tens of days, but some of them live for more than 10 months.
(I guess) if a drone job is manually forcibly stopped, its resources will not be properly released.

**Comment by derekbit** [comment]
Is it reproducible?

**Comment by ejweber** [comment]
This may be related to https://github.com/longhorn/longhorn/issues/3999 and a customer issue. The cause of the containers still being there (forcibly cancelled drone job) may be correct, but why is tgtd CPU usage at 100%? I am investigating. Please let me know if you have any ideas.
