### ISSUE TITLE
[BUG] share-manager for a given pvc keep restarting (other pvc are working fine)

### ISSUE THREAD

**Issue by viknet365** [longhorn/longhorn#5954]
## Describe the bug (🐛 if you encounter this issue)

the pod share manager keep restarting, end of share-manager logs look like (logs shortened):
nfs-ganesha-29[main] longhorn_recov_init :CLIENT ID :EVENT :Initialize recovery backend 'share-manager-pvc-XXXXX'
nfs-ganesha-29[main] http_call :CLIENT ID :EVENT :Failed to perform CURL operation: Server returned nothing (no headers, no data)
nfs-ganesha-29[main] longhorn_recov_init :CLIENT ID :FATAL :HTTP call error: res=-1 ((null))
 level=error msg="NFS server exited with error" encrypted=false error="ganesha.nfsd failed with error: exit status 2, output: " volume=pvc-XXX
mount_helper_common.go:133] Warning: "/export/pvc-e4b378af-2775-4a9b-be65-5b8c08c3770c" is not a mountpoint, deleting

## To Reproduce
always hapened on my 3 node home k8s cluster for this share 

## Expected behavior

share-manager  should work

## Log or Support bundle

will generate a support bundle ASAP

## Environment

 - Longhorn version: 1.4.1
 - Installation method : Kubectl
 - Kubernetes version 1.23 (updating to 1.26 did not resolv the issue)
   - Number of management node in the cluster: 3 
   - Number of worker node in the cluster: 3 (manager are the worker too)
 - Node config
   - OS type and version: ubuntu
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes: 1gb
 - Underlying Infrastructure baremetal, flannel, kubevip for the external IP 
 - Number of Longhorn volumes in the cluster: 23

## Additional context
does look like #5385 but I cannot find any remaining mounted nfs

**Comment by derekbit** [comment]
@viknet365 
Can you provide the dmesg of each worker node?

**Comment by derekbit** [comment]
```
2023-05-17T15:37:22.647559454+02:00 17/05/2023 13:37:22 : epoch 6464d892 : share-manager-pvc-e4b378af-2775-4a9b-be65-5b8c08c3770c : nfs-ganesha-30[main] http_call :CLIENT ID :EVENT :Failed to perform CURL operation: Server returned nothing (no headers, no data)
2023-05-17T15:37:22.648103364+02:00 17/05/2023 13:37:22 : epoch 6464d892 : share-manager-pvc-e4b378af-2775-4a9b-be65-5b8c08c3770c : nfs-ganesha-30[main] longhorn_recov_init :CLIENT ID :FATAL :HTTP call error: res=-1 ((null))
```
It seems that the nfs server cannot talk to the longhorn-recovery-backend service. Can you detach the RWX volume and attach it again?

**Comment by viknet365** [comment]
I am not sure how do I detach/reatach but scaling rhe deployment to 0 ensuring the workload pod is deleted and scaling back to 1 does not resolv the issue

**Comment by derekbit** [comment]
> I am not sure how do I detach/reatach but scaling rhe deployment to 0 ensuring the workload pod is deleted and scaling back to 1 does not resolv the issue

Can you scale down and scale up again, and provide us with the latest support bundle if the error remains? Thank you.

**Comment by viknet365** [comment]
I scaled down the deployment to 0, waited for the pod to be deleted and scaled back to 1, issue is still there
[supportbundle_5324d387-a423-4a96-97f6-096e80634490_2023-05-19T14-51-31Z.zip](https://github.com/longhorn/longhorn/files/11518048/supportbundle_5324d387-a423-4a96-97f6-096e80634490_2023-05-19T14-51-31Z.zip)
I can confirm that other rwx volume are working fine

**Comment by viknet365** [comment]
an update: the volume was trying to be mounted on node2 so I cordoned node2 to check if the issue existed on another node. and when trying to be mounted on node 3 issues still exist.
Bad news: while doing so I lost the replica on node2.  I tried to mount it in maintenance mode on node1 and now  the volume loop continuously between attaching then detaching, and is faulted. I attached a new support bundled if it can help
[supportbundle_5324d387-a423-4a96-97f6-096e80634490_2023-05-19T19-03-01Z.zip](https://github.com/longhorn/longhorn/files/11519754/supportbundle_5324d387-a423-4a96-97f6-096e80634490_2023-05-19T19-03-01Z.zip)

**Comment by viknet365** [comment]
upgrading to longhorn 1.4.2 does not solve the issue.

**Comment by derekbit** [comment]
@viknet365 
Can you scale the workload of the problematic volume to 0, delete the configmap `recovery-backend-share-manager-pvc-e4b378af-2775-4a9b-be65-5b8c08c3770c` by manual, and scale up the workload?

`kubectl  -n longhorn-system delete configmap recovery-backend-share-manager-pvc-e4b378af-2775-4a9b-be65-5b8c08c3770c`

The data of the share-manager configmap is somehow missing. We need to improve the resilience.
```
2023-05-19T17:01:07.945944249+02:00 time="2023-05-19T15:01:07Z" level=info msg="Creating a recovery backend share-manager-pvc-e4b378af-2775-4a9b-be65-5b8c08c3770c (version TJXAIAVR)"
2023-05-19T17:01:07.964126106+02:00 2023/05/19 15:01:07 http: panic serving 10.244.1.96:46514: assignment to entry in nil map
2023-05-19T17:01:07.964147633+02:00 goroutine 178611 [running]:
2023-05-19T17:01:07.964152197+02:00 net/http.(*conn).serve.func1()
2023-05-19T17:01:07.964156043+02:00 	/usr/local/go/src/net/http/server.go:1802 +0xb9
2023-05-19T17:01:07.964159553+02:00 panic({0x1d805a0, 0x2340280})
2023-05-19T17:01:07.964163141+02:00 	/usr/local/go/src/runtime/panic.go:1047 +0x266
2023-05-19T17:01:07.964167178+02:00 github.com/longhorn/longhorn-manager/recovery_backend/backend.(*RecoveryBackend).CreateConfigMap(0xc001a8b098, {0xc0017e2640, 0x36}, {0xc00236ea88, 0x8})
2023-05-19T17:01:07.964170697+02:00 	/go/src/github.com/longhorn/longhorn-manager/recovery_backend/backend/configmap.go:67 +0x199
2023-05-19T17:01:07.964174161+02:00 github.com/longhorn/longhorn-manager/recovery_backend/server.(*RecoveryBackendServer).Create(0xc00000fc40, {0xc001d305d0, 0xc002d41c00}, 0xedbf98633)
2023-05-19T17:01:07.964178023+02:00 	/go/src/github.com/longhorn/longhorn-manager/recovery_backend/server/recovery_backend.go:24 +0x1ae
2023-05-19T17:01:07.964181473+02:00 github.com/longhorn/longhorn-manager/api.HandleError.func1({0x2386340, 0xc00131e2a0}, 0x2386340)
2023-05-19T17:01:07.964185054+02:00 	/go/src/github.com/longhorn/longhorn-manager/api/router.go:18 +0x30
2023-05-19T17:01:07.964188479+02:00 net/http.HandlerFunc.ServeHTTP(0x2386340, {0x2386340, 0xc00131e2a0}, 0xc0000b3800)
2023-05-19T17:01:07.964191908+02:00 	/usr/local/go/src/net/http/server.go:2047 +0x2f
2023-05-19T17:01:07.964195347+02:00 github.com/rancher/go-rancher/api.ApiHandler.func1({0x2386340, 0xc00131e2a0}, 0x90)
2023-05-19T17:01:07.964198779+02:00 	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/rancher/go-rancher/api/handler.go:27 +0xcd
2023-05-19T17:01:07.964202198+02:00 net/http.HandlerFunc.ServeHTTP(0xc0008f4988, {0x2386340, 0xc00131e2a0}, 0xc001d30510)
2023-05-19T17:01:07.964205596+02:00 	/usr/local/go/src/net/http/server.go:2047 +0x2f
2023-05-19T17:01:07.964209049+02:00 github.com/gorilla/context.ClearHandler.func1({0x2386340, 0xc00131e2a0}, 0xc001d30540)
2023-05-19T17:01:07.964212530+02:00 	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/gorilla/context/context.go:141 +0x73
2023-05-19T17:01:07.964216027+02:00 net/http.HandlerFunc.ServeHTTP(0xc002d41b00, {0x2386340, 0xc00131e2a0}, 0xc0008f49f8)
2023-05-19T17:01:07.964219458+02:00 	/usr/local/go/src/net/http/server.go:2047 +0x2f
2023-05-19T17:01:07.964234726+02:00 github.com/gorilla/mux.(*Router).ServeHTTP(0xc00082e000, {0x2386340, 0xc00131e2a0}, 0xc002d41a00)
2023-05-19T17:01:07.964238438+02:00 	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/gorilla/mux/mux.go:210 +0x1cf
2023-05-19T17:01:07.964241851+02:00 net/http.serverHandler.ServeHTTP({0x2374c00}, {0x2386340, 0xc00131e2a0}, 0xc002d41a00)
2023-05-19T17:01:07.964245468+02:00 	/usr/local/go/src/net/http/server.go:2879 +0x43b
2023-05-19T17:01:07.964248898+02:00 net/http.(*conn).serve(0xc00051d400, {0x2392cb8, 0xc000c0e240})
2023-05-19T17:01:07.964252374+02:00 	/usr/local/go/src/net/http/server.go:1930 +0xb08
2023-05-19T17:01:07.964255795+02:00 created by net/http.(*Server).Serve
2023-05-19T17:01:07.964259344+02:00 	/usr/local/go/src/net/http/server.go:3034 +0x4e8
```

**Comment by viknet365** [comment]
I can't : I am now stuck in detaching/reattaching state after trying to manually attach to a node in maintenance mode
deleting the configmap recovery-backend-share-manager-pvc-e4b378af-2775-4a9b-be65-5b8c08c3770c did no change anything

**Comment by derekbit** [comment]
Weird...

If the configmap is deleted, a new configmap should be created and run into the error `assignment to entry in nil map`.
```
func (rb *RecoveryBackend) CreateConfigMap(hostname, version string) error {
	configMapName := types.GetConfigMapNameFromHostname(hostname)
	cm, err := rb.newConfigMap(rb.Namespace, configMapName, version, hostname)
	if err != nil {
		return err
	}

	if _, err := rb.Datastore.CreateConfigMap(cm); err != nil {
		if !apierrors.IsAlreadyExists(err) {
			return errors.Wrapf(err, "failed to create a configmap %v", configMapName)
		}

		cm, err := rb.Datastore.GetConfigMapWithoutCache(rb.Namespace, configMapName)
		if err != nil {
			return errors.Wrapf(err, "failed to get the configmap %v", configMapName)
		}

		cm.Data[version] = "{}"
		if _, err = rb.Datastore.UpdateConfigMap(cm); err != nil {
			return errors.Wrapf(err, "failed to update the configmap %v", configMapName)
		}
	}

	return nil
}

```

**Comment by derekbit** [comment]
> I can't : I am now stuck in detaching/reattaching state after trying to manually attach to a node in maintenance mode deleting the configmap recovery-backend-share-manager-pvc-e4b378af-2775-4a9b-be65-5b8c08c3770c did no change anything

Can you provide a support bundle again after deleting the configmap? Thank you.

**Comment by viknet365** [comment]
sorry my mistake: I did not scale up the deployment because the volume was stuck detaching/reattaching: but if I do with the configmap deleted, it solve the issue.
thanks

**Comment by yangchiu** [comment]
@derekbit I'm not sure how to verify this ticket. Delete the config map or remove the content of the config map? Should we need to scale down/up the workload? Can you help to elaborate more? Thank you!

**Comment by derekbit** [comment]
> @derekbit I'm not sure how to verify this ticket. Delete the config map or remove the content of the config map? Should we need to scale down/up the workload? Can you help to elaborate more? Thank you!

Yes, you can try the steps to reproduce.

**Comment by yangchiu** [comment]
> Yes, you can try the steps to reproduce.

@derekbit After the config map deleted or the content of the config map removed, it won't be re-generated or recovered automatically. Does it need manually scaling down/up to get the correct config map?

**Comment by derekbit** [comment]
>  Does it need manually scaling down/up to get the correct config map?
Yes, can you try it?

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 705e770) following the test steps:

1. Create RWX statefulset
2. Delete the config map or remove the content of the config map
3. Scale down/up the workload, the config map can be recovered
