### ISSUE TITLE
[BUG] es master pv error with nested: CorruptIndexException[codec footer mismatch (file truncated?)

### ISSUE THREAD

**Issue by ming12713** [longhorn/longhorn#7193]
## Describe the bug (🐛 if you encounter this issue)
The es master volume is a pv volume provided by longhorn. The server room experienced an abnormal power outage, and after k8s was restored, esmaster reported crc32 foot checksum error 

`
{"type": "server", "timestamp": "2023-11-21T09:52:52,412Z", "level": "ERROR", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "elasticsearch", "node.name": "elasticsearch-es-master-1", "message": "uncaught exception in thread [main]",
"stacktrace": ["org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: CorruptIndexException[codec footer mismatch (file truncated?): actual footer=0 vs expected footer=-1071082520 (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path=\"/usr/share/elasticsearch/data/nodes/0/_state/_1g1h.si\")))];",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:173) ~[elasticsearch-7.17.8.jar:7.17.8]",
"at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160) ~[elasticsearch-7.17.8.jar:7.17.8]",
"at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) ~[elasticsearch-7.17.8.jar:7.17.8]",
"at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) ~[elasticsearch-cli-7.17.8.jar:7.17.8]",
"at org.elasticsearch.cli.Command.main(Command.java:77) ~[elasticsearch-cli-7.17.8.jar:7.17.8]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125) ~[elasticsearch-7.17.8.jar:7.17.8]",
`

Is there a way to solve the crc32 foot checksum failed without a snapshot in longhorn?

<img width="1265" alt="屏幕快照 2023-11-22 08 35 25" src="https://github.com/longhorn/longhorn/assets/5196113/3fc5b44a-cc9d-4910-b78b-8d27695c1e68">

## Environment

 - Longhorn version: v1.5.1
 -k8s:  v1.26.6
 - Node config
   - OS type and version: 22.04
   - Kernel version: 5.15.0-88-generic

**Comment by derekbit** [comment]
Can you elaborate more on the crc32 foot checksum? A checksum of your application data?

**Comment by ming12713** [comment]
> Can you elaborate more on the crc32 foot checksum? A checksum of your application data?

hi,derekbit 
k8s cluster which uses longhorn for storage, has an es cluster deployed on top of it. The power outage caused the k8s cluster to go offline. After the power was restored and both k8s and longhorn were restored, we discovered that the es master could not be restored and reported a crc32 checksum error. We followed up on the es-related issues and failure description, which was caused by inconsistent writes and reads of the underlying file system crc32 checksum.
troubleshooting corruption https://www.elastic.co/guide/en/elasticsearch/reference/current/corruption-troubleshooting.html

**Comment by derekbit** [comment]
Would you be able to back up the volume and then run fsck?

**Comment by ming12713** [comment]
> Would you be able to back up the volume and then run fsck?

no snaphost and no backup

**Comment by derekbit** [comment]
I mean you can take a snapshot and back up the volume. After this, try to check the filesystem by fsck.

**Comment by ming12713** [comment]
3 replica

**Comment by ming12713** [comment]
@derekbit Hi, we have been trying to recover ES without considering the underlying file system. tried deleting the PV, but I have a full backup of the ES master information. The current PV is a newly created PV that was imported from the ES master. My understanding is that fsck will not work in this situation, right?

**Comment by ejweber** [comment]
Is it possible for you to upload a support bundle @ming12713? After reading https://www.elastic.co/guide/en/elasticsearch/reference/current/corruption-troubleshooting.html, it is difficult to understand exactly how this could have happened. Longhorn should not return success for writes that have not been persisted to all healthy replicas. I can imaging one possibility, which your support bundle could potentially help to confirm:

- Elasticsearch was still operational and writing to Longhorn when the power event occurred.
- Two out of three replicas failed during the power event.
- Elasticsearch wrote a file that was successfully persisted to the third replica.
- When the cluster came back online, only a node containing a replica WITHOUT the write became available first.
- Longhorn autosalvaged the volume from this replica.
- Now the volume is missing the expected write.

WDYT @derekbit?

**Comment by ejweber** [comment]
> The current PV is a newly created PV that was imported from the ES master. My understanding is that fsck will not work in this situation, right?

Can you expand on this a bit more? I am not sure I understand what you mean.

**Comment by ming12713** [comment]
@ejweber 
When there is a problem with the es master node, we only back up the es data and delete the pv volume no volume snapshot, try recreate the master node to connect to the es data node. that's mean the failed volume no longer exists, and only the es master data was backed up at the time

**Comment by ejweber** [comment]
So you started `elasticsearch-es-master-1` with a brand new Longhorn volume and are relying on Elasticsearch to repopulate it? 

In general, I think even if you had a Longhorn snapshot, it would not help you to restore from it. The Elasticsearch docs make it very clear that filesystem level backups are not an effective way of ensuring Elasticsearch data: https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshot-restore.html#other-backup-methods.

I am curious if we can see anything in Longhorn logs that might indicate an underlying reason for the corruption. Can we have a support bundle?

At this point, I think any actions you can take to recover will be at the application (Elasticsearch) level.

**Comment by ming12713** [comment]
@ejweber 
thanks， We restored it through snapshot, but we still lost a few days of data. 
I would like to know if longhorn encounters the situation I mentioned above, is there any way to avoid the CRC32 checksum mismatch problem? Use fsck? Or other methods? To avoid similar problems from happening again next time?

**Comment by ming12713** [comment]
> Is it possible for you to upload a support bundle @ming12713? After reading https://www.elastic.co/guide/en/elasticsearch/reference/current/corruption-troubleshooting.html, it is difficult to understand exactly how this could have happened. Longhorn should not return success for writes that have not been persisted to all healthy replicas. I can imaging one possibility, which your support bundle could potentially help to confirm:
> 
> * Elasticsearch was still operational and writing to Longhorn when the power event occurred.
> * Two out of three replicas failed during the power event.
> * Elasticsearch wrote a file that was successfully persisted to the third replica.
> * When the cluster came back online, only a node containing a replica WITHOUT the write became available first.
> * Longhorn autosalvaged the volume from this replica.
> * Now the volume is missing the expected write.
> 
> WDYT @derekbit?

The server room was powered off, the k8s cluster was offline, and longhorn and elasticsearch were also offline
When reading and writing ES,
* the elasticsearch  indices replica is 3, and es sharding has not been completed in time
* Es master pv (longhorn volume) replica 3 did not have time to complete synchronization

At this time, the power was cut off, causing inconsistent read and write data, and the es node crc32 checksum reported an error.

**Comment by ming12713** [comment]
> > thanks， We restored it through snapshot, but we still lost a few days of data.
> > I would like to know if longhorn encounters the situation I mentioned above, is there any way to avoid the CRC32 checksum mismatch problem? Use fsck? Or other methods? To avoid similar problems from happening again next time?
> 
> Unfortunately, for now I do not have any recommendations. This error message itself is very specific to the way that Elasticsearch writes out data. I think it's unlikely for `fsck` to work, though I won't discourage you from trying to use `fsck` if you run into it again (https://longhorn.io/kb/troubleshooting-volume-filesystem-corruption/#for-most-linux-distribution-versions). Taking frequent snapshots at either the Elasticsearch level or the Longhorn level is also a good idea.
> 
> If this happens again, please provide a support bundle for analysis. It may help to determine if you are hitting something like #6290.

Okay, thank you for your help
