### ISSUE TITLE
[TEST][BUG] longhorn-tests build docker image failed

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#8049]
## What's the test to develop? Please describe

master branch longhorn-tests build docker image failed:

https://drone-publish.longhorn.io/longhorn/longhorn-tests/1508/1/4

```
 ---> Running in 3daa24073d4b

Refreshing service 'container-suseconnect-zypp'.

Loading repository data...

Reading installed packages...

'tar' is already installed.

No update candidate for 'tar-1.34-150000.3.34.1.x86_64'. The highest available version is already installed.

'awk' not found in package names. Trying capabilities.

'gzip' is already installed.

No update candidate for 'gzip-1.10-150200.10.1.x86_64'. The highest available version is already installed.

'python39-devel' not found in package names. Trying capabilities.

No provider of 'python39-devel' found.

The command '/bin/sh -c zypper in -y vim-small nfs-client xfsprogs e2fsprogs util-linux-systemd gcc python39-devel gawk java-11-openjdk tar awk gzip wget unzip &&     rm -rf /var/cache/zypp/*' returned a non-zero code: 104

exit status 104

[0m
```

Could be relevant to `renovate` updating dependencies without validation.

cc @innobead

**Comment by innobead** [comment]
If that's due to renovate, we should have a PR check for each PR to prevent this.

**Comment by yangchiu** [comment]
> If that's due to renovate, we should have a PR check for each PR to prevent this.

Yes, it's caused by `renovate`.

**Comment by yangchiu** [comment]
Another error:
```
 => ERROR [ 7/15] RUN pip install -r requirements.txt                                                                                                          8.5s
------
 > [ 7/15] RUN pip install -r requirements.txt:
1.323 Collecting boto3==1.17.91
1.667   Downloading boto3-1.17.91-py2.py3-none-any.whl (131 kB)
1.817      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.5/131.5 kB 828.0 kB/s eta 0:00:00
1.929 Collecting requests==2.25.1
2.002   Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
2.020      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 3.5 MB/s eta 0:00:00
2.122 Collecting argcomplete==1.10.0
2.195   Downloading argcomplete-1.10.0-py2.py3-none-any.whl (31 kB)
2.291 Collecting directio==1.2
2.367   Downloading directio-1.2.tar.gz (3.1 kB)
2.375   Preparing metadata (setup.py): started
2.486   Preparing metadata (setup.py): finished with status 'done'
2.595 Collecting flake8
2.666   Downloading flake8-7.0.0-py2.py3-none-any.whl (57 kB)
2.679      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 4.3 MB/s eta 0:00:00
2.784 Collecting kubernetes==25.3.0
2.854   Downloading kubernetes-25.3.0-py2.py3-none-any.whl (1.4 MB)
3.096      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 5.8 MB/s eta 0:00:00
3.221 Collecting pytest==5.3.1
3.298   Downloading pytest-5.3.1-py3-none-any.whl (233 kB)
3.318      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.9/233.9 kB 15.0 MB/s eta 0:00:00
3.415 Collecting pytest-repeat==0.9.1
3.487   Downloading pytest_repeat-0.9.1-py2.py3-none-any.whl (4.3 kB)
3.584 Collecting pytest-order==1.0.1
3.664   Downloading pytest_order-1.0.1-py3-none-any.whl (13 kB)
3.770 Collecting six==1.12.0
3.843   Downloading six-1.12.0-py2.py3-none-any.whl (10 kB)
3.946 Collecting minio==5.0.10
4.020   Downloading minio-5.0.10-py2.py3-none-any.whl (75 kB)
4.029      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.9/75.9 kB 13.8 MB/s eta 0:00:00
4.153 Collecting pyyaml==5.4.1
4.232   Downloading PyYAML-5.4.1.tar.gz (175 kB)
4.245      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 14.6 MB/s eta 0:00:00
4.322   Installing build dependencies: started
8.237   Installing build dependencies: finished with status 'done'
8.238   Getting requirements to build wheel: started
8.384   Getting requirements to build wheel: finished with status 'error'
8.388   error: subprocess-exited-with-error
8.388   
8.388   × Getting requirements to build wheel did not run successfully.
8.388   │ exit code: 1
8.388   ╰─> [54 lines of output]
8.388       running egg_info
8.388       writing lib3/PyYAML.egg-info/PKG-INFO
8.388       writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
8.388       writing top-level names to lib3/PyYAML.egg-info/top_level.txt
8.388       Traceback (most recent call last):
8.388         File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
8.388           main()
8.388         File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
8.388           json_out['return_val'] = hook(**hook_input['kwargs'])
8.388                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8.388         File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
8.388           return hook(config_settings)
8.388                  ^^^^^^^^^^^^^^^^^^^^^
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
8.388           return self._get_build_requires(config_settings, requirements=['wheel'])
8.388                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
8.388           self.run_setup()
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
8.388           exec(code, locals())
8.388         File "<string>", line 271, in <module>
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
8.388           return distutils.core.setup(**attrs)
8.388                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
8.388           return run_commands(dist)
8.388                  ^^^^^^^^^^^^^^^^^^
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
8.388           dist.run_commands()
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
8.388           self.run_command(cmd)
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
8.388           super().run_command(command)
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
8.388           cmd_obj.run()
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run
8.388           self.find_sources()
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
8.388           mm.run()
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 550, in run
8.388           self.add_defaults()
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
8.388           sdist.add_defaults(self)
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
8.388           super().add_defaults()
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
8.388           self._add_defaults_ext()
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
8.388           self.filelist.extend(build_ext.get_source_files())
8.388                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8.388         File "<string>", line 201, in get_source_files
8.388         File "/tmp/pip-build-env-h_z_2_kk/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
8.388           raise AttributeError(attr)
8.388       AttributeError: cython_sources
8.388       [end of output]
8.388   
8.388   note: This error originates from a subprocess, and is likely not a problem with pip.
8.390 error: subprocess-exited-with-error
8.390 
8.390 × Getting requirements to build wheel did not run successfully.
8.390 │ exit code: 1
8.390 ╰─> See above for output.
8.390 
8.390 note: This error originates from a subprocess, and is likely not a problem with pip.
------
Dockerfile:35
--------------------
  33 |     
  34 |     ADD manager/integration/tests/requirements.txt .
  35 | >>> RUN pip install -r requirements.txt
  36 |     
  37 |     ADD manager/integration /integration
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
```

Need more time to investigate.
