### ISSUE TITLE
manager NPE on tearing down

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#870]
```
[longhorn-manager-67nhs] time="2019-11-12T21:58:14Z" level=debug msg="Stop monitoring instance manager instance-manager-r-fdf37b32"
[longhorn-manager-67nhs] E1112 21:58:14.037140       1 runtime.go:69] Observed a panic: "send on closed channel" (send on closed channel)
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
[longhorn-manager-67nhs] /usr/local/go/src/runtime/panic.go:679
[longhorn-manager-67nhs] /usr/local/go/src/runtime/chan.go:252
[longhorn-manager-67nhs] /usr/local/go/src/runtime/chan.go:127
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/controller/instance_manager_controller.go:806
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/controller/instance_manager_controller.go:446
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/controller/instance_manager_controller.go:297
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/controller/instance_manager_controller.go:235
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/controller/instance_manager_controller.go:223
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
[longhorn-manager-67nhs] /usr/local/go/src/runtime/asm_amd64.s:1357
[longhorn-manager-67nhs] panic: send on closed channel [recovered]
[longhorn-manager-67nhs] panic: send on closed channel
[longhorn-manager-67nhs]
[longhorn-manager-67nhs] goroutine 285 [running]:
[longhorn-manager-67nhs] k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
[longhorn-manager-67nhs] panic(0x162b6e0, 0x1a71db0)
[longhorn-manager-67nhs] /usr/local/go/src/runtime/panic.go:679 +0x1b2
[longhorn-manager-67nhs] github.com/longhorn/longhorn-manager/controller.(*InstanceManagerController).stopMonitoring(0xc00003b290, 0xc001400b60)
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/controller/instance_manager_controller.go:806 +0xa9
[longhorn-manager-67nhs] github.com/longhorn/longhorn-manager/controller.(*InstanceManagerController).cleanupInstanceManager(0xc00003b290, 0xc001400b60, 0x16, 0xc001400b01)
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/controller/instance_manager_controller.go:446 +0x3cc
[longhorn-manager-67nhs] github.com/longhorn/longhorn-manager/controller.(*InstanceManagerController).syncInstanceManager(0xc00003b290, 0xc000ced260, 0x2b, 0x0, 0x0)
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/controller/instance_manager_controller.go:297 +0x446
[longhorn-manager-67nhs] github.com/longhorn/longhorn-manager/controller.(*InstanceManagerController).processNextWorkItem(0xc00003b290, 0x0)
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/controller/instance_manager_controller.go:235 +0xf4
[longhorn-manager-67nhs] github.com/longhorn/longhorn-manager/controller.(*InstanceManagerController).worker(0xc00003b290)
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/controller/instance_manager_controller.go:223 +0x2b
[longhorn-manager-67nhs] k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000b1db00)
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
[longhorn-manager-67nhs] k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b1db00, 0x3b9aca00, 0x0, 0x1, 0xc00009c300)
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
[longhorn-manager-67nhs] k8s.io/apimachinery/pkg/util/wait.Until(0xc000b1db00, 0x3b9aca00, 0xc00009c300)
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
[longhorn-manager-67nhs] created by github.com/longhorn/longhorn-manager/controller.(*InstanceManagerController).Run
[longhorn-manager-67nhs] /go/src/github.com/longhorn/longhorn-manager/controller/instance_manager_controller.go:216 +0x20a
```

**Comment by yasker** [comment]
Not easy to reproduce. Move to v0.8.0.

**Comment by yasker** [comment]
Update to `impact/middle` due to manager should restart by itself.

If the manager is going to stuck in the reboot loop, it would be readjusted to `impact/high`.

**Comment by yasker** [comment]
Reproduced it while overcommitted instance manager's CPU when working on #1318 .

**Comment by yasker** [comment]
The fix is too intrusive for v1.0.0. Move to v1.0.1.

1. The issue is hard to hit
2. If the manager crashed as the result, the manager will restart automatically, which shouldn't impact the user.

**Comment by shuo-wu** [comment]
Manual test:
1. Deploy Longhorn.
2. Set `Guaranteed Engine CPU` to 10 (10 vcpus).
3. Instance(engine/replica) manager pods will be recreated again and again. Check the managers' log. (Use `kubetail longhorn-manager -n longhorn-system` to check the log)
4. Set `Guaranteed Engine CPU` to 0.25 and wait for instance manager pods running.
5. Create and attach a volume. Then use the volume to r/w data.
6. Repeat step2 to step5 for 5 times.
    There shouldn't be the NPE log in step 3 and the volume in step5 should work fine.

After merging the code and validating the above test, I will add this test to the manual test plan.

**Comment by shuo-wu** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged?
The PR is at https://github.com/longhorn/longhorn-manager/pull/588

* [x] Is the reproduce steps/test steps documented?
The test steps are the same as the reproduce steps.

* [x] ~~**If the fix introduces the code for backward compatibility** Has a separate issue been filed with the label `release/obsolete-compatibility`?~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?~~

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by khushboo-rancher** [comment]
@shuo-wu Can you please help me in reproducing this issue on v1.0.0 or v0.8.1?
I tried on v1.0.0 and v0.81, ```instance engine/replica manager pods``` kept recreating after setting ```Guaranteed engine cpu``` to 10. But I didn't see any panic logs.

**Comment by shuo-wu** [comment]
Sorry, I may miss one step: Create and attach a volume before modifying the setting. Then it's hard to trigger the race condition.
And please use v1.0.0 to reproduce the bug.

**Comment by khushboo-rancher** [comment]
Validated on master - 06-15-2020, no panic logs are seen.

Validation - **Passed**

Followed the below steps to reproduce the issue in v1.0.0 where there was panic logs present and on master no panic logs are seen
1. Create a volume and attach to a pod
2. Set ```Guaranteed engine cpu``` to 10, when volume goes into detaching status and  ```instance engine/replica manager pods``` kept recreating, set the ```Guaranteed engine cpu``` to 0.25
3. Keep observing the logs and when logs shows below info, set ```Guaranteed engine cpu``` to 10 again.
```
[longhorn-manager-x98mj] time="2020-06-15T20:45:06Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"pvc-4aa831d8-6f3e-48e8-9d40-71d80a967da0-e-853b87bb\", UID:\"1713a9ee-3aba-41ae-9ee3-c3a6a173a3ba\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"52948\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedStopping' Error stopping pvc-4aa831d8-6f3e-48e8-9d40-71d80a967da0-e-853b87bb: failed to delete process pvc-4aa831d8-6f3e-48e8-9d40-71d80a967da0-e-853b87bb: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.42.3.90:8500: i/o timeout\"" 
[longhorn-manager-x98mj] time="2020-06-15T20:45:06Z" level=debug msg="Prepare to delete instance pvc-4aa831d8-6f3e-48e8-9d40-71d80a967da0-e-853b87bb" 
[longhorn-manager-x98mj] time="2020-06-15T20:45:06Z" level=warning msg="Instance pvc-4aa831d8-6f3e-48e8-9d40-71d80a967da0-e-853b87bb is state error, error message: Instance Manager error" 
[longhorn-manager-x98mj] time="2020-06-15T20:45:06Z" level=warning msg="Instance pvc-4aa831d8-6f3e-48e8-9d40-71d80a967da0-e-853b87bb crashed on Instance Manager instance-manager-e-ea4bf92e at khush-test-lh-wk2, try to get log" 
[longhorn-manager-x98mj] time="2020-06-15T20:45:06Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"pvc-4aa831d8-6f3e-48e8-9d40-71d80a967da0-e-853b87bb\", UID:\"1713a9ee-3aba-41ae-9ee3-c3a6a173a3ba\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"52948\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops pvc-4aa831d8-6f3e-48e8-9d40-71d80a967da0-e-853b87bb" 
[longhorn-manager-x98mj] time="2020-06-15T20:45:06Z" level=error msg="failed to receive log for instance pvc-4aa831d8-6f3e-48e8-9d40-71d80a967da0-e-853b87bb: rpc error: code = NotFound desc = cannot find process pvc-4aa831d8-6f3e-48e8-9d40-71d80a967da0-e-853b87bb"
```

4. In v1.0.0, panic logs starts appearing as below
```
[longhorn-manager-5wptb] time="2020-06-15T20:45:15Z" level=warning msg="Dropping Longhorn instance manager longhorn-system/instance-manager-e-0986a35d out of the queue: fail to sync instance manager for longhorn-system/instance-manager-e-0986a35d: failed to create pod for instance manager instance-manager-e-0986a35d: object is being deleted: pods \"instance-manager-e-0986a35d\" already exists" 
[longhorn-manager-x98mj] 	panic: send on closed channel 
[longhorn-manager-5wptb] time="2020-06-15T20:45:15Z" level=warning msg="Error syncing Longhorn instance manager longhorn-system/instance-manager-r-476f0945: fail to sync instance manager for longhorn-system/instance-manager-r-476f0945: failed to create pod for instance manager instance-manager-r-476f0945: object is being deleted: pods \"instance-manager-r-476f0945\" already exists" 
[longhorn-manager-x98mj]  
[longhorn-manager-5wptb] time="2020-06-15T20:45:15Z" level=warning msg="Starts to clean up then recreates pod for instance manager instance-manager-r-476f0945 with state error" 
[longhorn-manager-x98mj] goroutine 366 [running]: 
[longhorn-manager-x98mj] k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0) 
[longhorn-manager-x98mj] 	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105 
[longhorn-manager-x98mj] panic(0x15f5e80, 0x1a361d0) 
[longhorn-manager-x98mj] 	/usr/local/go/src/runtime/panic.go:967 +0x166 
```


5. On master, there is no logs of panic
```
[longhorn-manager-94lzn] time="2020-06-15T21:56:24Z" level=warning msg="Starts to clean up then recreates pod for instance manager instance-manager-e-6a219631 with state error" 
[longhorn-manager-94lzn] time="2020-06-15T21:56:24Z" level=info msg="Created instance manager pod instance-manager-e-6a219631 for instance manager instance-manager-e-6a219631" 
[longhorn-manager-7pxt9] time="2020-06-15T21:56:24Z" level=error msg="Instance Manager instance-manager-r-31acd230 is state error but the related pod is pending." ```
