### ISSUE TITLE
longhorn-manager - panic: runtime error with containerd.io

### ISSUE THREAD

**Issue by STASiAN** [longhorn/longhorn#950]
Hi Guys!

Subj.

# kubectl version
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

# crictl --version
crictl version v1.16.1x

# rpm -qa|grep containerd
containerd.io-1.2.6-3.3.el7.x86_64 (also tried with containerd.io-1.2.10)

```
time="2019-12-06T09:57:55Z" level=info msg="Start Longhorn replica controller"
time="2019-12-06T09:57:55Z" level=debug msg="Engine image longhornio/longhorn-engine:v0.7.0 is ready"
time="2019-12-06T09:57:55Z" level=info msg="Start Longhorn node controller"
time="2019-12-06T09:57:55Z" level=info msg="Start Longhorn engine controller"
time="2019-12-06T09:57:55Z" level=info msg="Start Longhorn volume controller"
time="2019-12-06T09:57:55Z" level=info msg="Start Longhorn Engine Image controller"
time="2019-12-06T09:57:55Z" level=info msg="Start Longhorn Setting controller"
time="2019-12-06T09:57:55Z" level=info msg="Start Longhorn websocket controller"
time="2019-12-06T09:57:55Z" level=info msg="Start kubernetes controller"
time="2019-12-06T09:57:55Z" level=info msg="Starting Longhorn instance manager controller"
time="2019-12-06T09:57:55Z" level=info msg="Listening on 10.231.122.111:9500"
time="2019-12-06T09:57:55Z" level=debug msg="Start monitoring pvc-9df584fd-ace5-4413-a836-15bd38c93c90-e-fda23129"
time="2019-12-06T09:57:55Z" level=debug msg="Start monitoring instance manager instance-manager-r-669f4218"
time="2019-12-06T09:57:55Z" level=debug msg="Start monitoring instance manager instance-manager-e-d742f903"
E1206 09:57:55.594739       1 runtime.go:69] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:679
/usr/local/go/src/runtime/panic.go:75
/go/src/github.com/longhorn/longhorn-manager/util/util.go:660
/go/src/github.com/longhorn/longhorn-manager/controller/volume_controller.go:926
/go/src/github.com/longhorn/longhorn-manager/controller/volume_controller.go:335
/go/src/github.com/longhorn/longhorn-manager/controller/volume_controller.go:186
/go/src/github.com/longhorn/longhorn-manager/controller/volume_controller.go:174
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1357
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 403 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1751920, 0xc001068900)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/longhorn/longhorn-manager/util.RemountVolume(0xc000703650, 0x28, 0x178bb60, 0xc0000d7220)
	/go/src/github.com/longhorn/longhorn-manager/util/util.go:660 +0xcd8
github.com/longhorn/longhorn-manager/controller.(*VolumeController).ReconcileVolumeState(0xc0000d6280, 0xc0002d8600, 0xc0000eb900, 0xc000fc4c60, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/controller/volume_controller.go:926 +0x2091
github.com/longhorn/longhorn-manager/controller.(*VolumeController).syncVolume(0xc0000d6280, 0xc000c9e080, 0x31, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/controller/volume_controller.go:335 +0xd20
github.com/longhorn/longhorn-manager/controller.(*VolumeController).processNextWorkItem(0xc0000d6280, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/controller/volume_controller.go:186 +0x100
github.com/longhorn/longhorn-manager/controller.(*VolumeController).worker(0xc0000d6280)
	/go/src/github.com/longhorn/longhorn-manager/controller/volume_controller.go:174 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000f64750)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000f64750, 0x3b9aca00, 0x0, 0x1, 0xc0001000c0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000f64750, 0x3b9aca00, 0xc0001000c0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/longhorn/longhorn-manager/controller.(*VolumeController).Run
	/go/src/github.com/longhorn/longhorn-manager/controller/volume_controller.go:167 +0x228
```

**Comment by cr0** [comment]
I observed this after one of my nodes crashed. Longhorn did not seem to recover (longhorn-manager kept panicing on that node), hence I had to delete and recreate the pv from backup.

**Comment by yasker** [comment]
Thanks for the report, we will fix it in the next release.

@shuo-wu Can you find a workaround?

**Comment by shuo-wu** [comment]
This issue is caused by the empty line in the output of the command `mount | grep -v grep | grep ext4 | awk '{print $1,$3,$6}'`. Would you provide the mount records or the reproduce steps?

**Comment by STASiAN** [comment]
@shuo-wu 
on k8s node with ext4
`[root@n14 ~]# mount | grep -v grep | grep ext4 
/dev/mapper/vg0-lv_root on / type ext4 (rw,relatime,seclabel,stripe=256,data=ordered)
/dev/md0 on /boot type ext4 (rw,relatime,seclabel,data=ordered)
/dev/mapper/vg0-lv_root on /var/lib/kubelet/plugins/io.rancher.longhorn type ext4 (rw,relatime,seclabel,stripe=256,data=ordered)
/dev/mapper/vg0-lv_root on /var/lib/kubelet/pods/2c242fd0-f850-4e55-84e1-7d1167393964/volume-subpaths/config/dex-k8s-authenticator/0 type ext4 (rw,relatime,seclabel,stripe=256,data=ordered)
/dev/mapper/vg0-lv_root on /var/lib/kubelet/pods/dc4dec08-d503-4369-afe1-7bcaa20a204f/volume-subpaths/config/dex-k8s-authenticator/0 type ext4 (rw,relatime,seclabel,stripe=256,data=ordered)`

and there is no output on xfs
`# mount | grep -v grep | grep ext4 `
please keep in mind, that i your fix will not work on xfs filesystem
you should avoid `grep ext4` here
https://github.com/longhorn/longhorn-manager/pull/482/files#diff-99f38c7c07bfcc03a528180716bafab5R628

**Comment by shuo-wu** [comment]
We will add filesystem auto-detection for this remount feature: #982

**Comment by shuo-wu** [comment]
The root cause:
If there is no `ext4` filesystem on the cluster nodes, the mount records are `[""]` rather than an empty list. Then spitting an empty string and fetching elements from the result will trigger this issue.

**Comment by shuo-wu** [comment]
The auto remount doesn't work for `xfs` filesystem now. See [this commit](https://github.com/longhorn/longhorn-manager/pull/488/commits/0c32f7d6a915ae5dbc5d951a64cee7bc2e442f03) for details.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:  steps described in #982
